// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The Ebitengine Authors

//go:build ignore

// genfastfunc generates zero-allocation closures for RegisterFunc's fast path.
// The output file is zz_fast_func.go.
//
// All generated code is driven by a single declarative config (defaultConfig).
// To add a new fast-path pattern, add a fastPattern
// entry and re-run go generate.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
)

// fastPathConfig describes every fast-path pattern the generator should emit.
type fastPathConfig struct {
	MaxIntArgs   int           // max integer args (e.g. 15)
	MaxFloatArgs int           // max float register args (e.g. 8)
	Patterns     []fastPattern // patterns to emit, matched in order
}

type fastPattern struct {
	Name      string // "IntOnly", "TrailingFloat32x1", etc.
	MinInts   int    // min integer args (0 = no minimum)
	MaxInts   int    // max integer args (-1 = config.MaxIntArgs)
	NumFloats int    // exact float count (0 = int-only)
	FloatBits int    // 32 or 64 (0 = N/A for int-only)
	Layout    string // "trailing", "interleaved", "any" (empty = N/A for int-only)
}

var defaultConfig = fastPathConfig{
	MaxIntArgs:   15,
	MaxFloatArgs: 8,
	Patterns: []fastPattern{
		{Name: "IntOnly", MaxInts: -1, NumFloats: 0},
		{Name: "TrailingFloat32x1", MaxInts: -1, NumFloats: 1, FloatBits: 32, Layout: "trailing"},
		{Name: "TrailingFloat64x1", MaxInts: -1, NumFloats: 1, FloatBits: 64, Layout: "trailing"},
		{Name: "InterleavedFloat32x1", MinInts: 1, MaxInts: -1, NumFloats: 1, FloatBits: 32, Layout: "interleaved"},
	},
}

func main() {
	cfg := defaultConfig
	resolveConfig(&cfg)

	var buf bytes.Buffer
	buf.WriteString(`// Code generated by genfastfunc.go; DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The Ebitengine Authors

//go:build darwin || freebsd || linux || netbsd || windows

package purego

import (
	"math"
	"reflect"
	"runtime"
	"unsafe"
)

`)

	emitFastCallN(&buf, cfg)       // fastCall0..fastCallN pool-based backends
	emitFastCallIF(&buf, cfg)      // shared int+float backend
	emitPatternClosures(&buf, cfg) // per-pattern register* functions
	emitFloatNFallback(&buf, cfg)  // registerFastFuncFloatN MakeFunc fallback
	emitTryRegisterFastPath(&buf, cfg)
	emitForceFuncPtr(&buf)

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("gofmt: %v\n%s", err, buf.String())
	}
	if err := os.WriteFile("zz_fast_func.go", src, 0644); err != nil {
		log.Fatal(err)
	}
}

// resolveConfig expands MaxInts == -1 to cfg.MaxIntArgs.
func resolveConfig(cfg *fastPathConfig) {
	for i := range cfg.Patterns {
		if cfg.Patterns[i].MaxInts == -1 {
			cfg.Patterns[i].MaxInts = cfg.MaxIntArgs
		}
	}
}

func argList(n int) string {
	if n == 0 {
		return ""
	}
	parts := make([]string, n)
	for i := range n {
		parts[i] = fmt.Sprintf("a%d", i+1)
	}
	return strings.Join(parts, ", ")
}

func paramList(n int) string {
	if n == 0 {
		return ""
	}
	return argList(n) + " uintptr"
}

func floatParamList(n int, bits int) string {
	ty := "float32"
	if bits == 64 {
		ty = "float64"
	}
	parts := make([]string, n)
	for i := range n {
		parts[i] = fmt.Sprintf("f%d", i+1)
	}
	return strings.Join(parts, ", ") + " " + ty
}

// emitFastCallN emits fastCall0..fastCall{MaxIntArgs}: pool-based int-only backends.
func emitFastCallN(buf *bytes.Buffer, cfg fastPathConfig) {
	for n := 0; n <= cfg.MaxIntArgs; n++ {
		params := "cfn"
		if n > 0 {
			params += ", " + argList(n)
		}

		fmt.Fprintf(buf, "func fastCall%d(%s uintptr) uintptr {\n", n, params)
		buf.WriteString("\ts := thePool.Get().(*syscall15Args)\n")
		buf.WriteString("\ts.fn = cfn\n")

		// Set a1..a8
		if n == 0 {
			buf.WriteString("\ts.a1, s.a2, s.a3, s.a4, s.a5, s.a6, s.a7, s.a8 = 0, 0, 0, 0, 0, 0, 0, 0\n")
		} else if n <= 8 {
			parts := make([]string, 8)
			for i := range 8 {
				if i < n {
					parts[i] = fmt.Sprintf("a%d", i+1)
				} else {
					parts[i] = "0"
				}
			}
			fmt.Fprintf(buf, "\ts.a1, s.a2, s.a3, s.a4, s.a5, s.a6, s.a7, s.a8 = %s\n", strings.Join(parts, ", "))
		} else {
			buf.WriteString("\ts.a1, s.a2, s.a3, s.a4, s.a5, s.a6, s.a7, s.a8 = a1, a2, a3, a4, a5, a6, a7, a8\n")
		}

		// Set a9..a15 overflow (always zero unused slots since pool objects are reused)
		if n > 8 {
			overflow := make([]string, n-8)
			for i := 8; i < n; i++ {
				overflow[i-8] = fmt.Sprintf("a%d", i+1)
			}
			fields := []string{"s.a9", "s.a10", "s.a11", "s.a12", "s.a13", "s.a14", "s.a15"}
			if len(overflow) > 0 {
				usedFields := fields[:len(overflow)]
				fmt.Fprintf(buf, "\t%s = %s\n", strings.Join(usedFields, ", "), strings.Join(overflow, ", "))
			}
			remaining := fields[len(overflow):]
			if len(remaining) > 0 {
				zeros := make([]string, len(remaining))
				for i := range zeros {
					zeros[i] = "0"
				}
				fmt.Fprintf(buf, "\t%s = %s\n", strings.Join(remaining, ", "), strings.Join(zeros, ", "))
			}
		} else {
			buf.WriteString("\ts.a9, s.a10, s.a11, s.a12, s.a13, s.a14, s.a15 = 0, 0, 0, 0, 0, 0, 0\n")
		}

		buf.WriteString("\ts.f1, s.f2, s.f3, s.f4, s.f5, s.f6, s.f7, s.f8 = 0, 0, 0, 0, 0, 0, 0, 0\n")
		buf.WriteString("\ts.arm64_r8 = 0\n")
		buf.WriteString("\truntime_cgocall(syscall15XABI0, unsafe.Pointer(s))\n")
		buf.WriteString("\tr := s.a1\n")
		buf.WriteString("\tthePool.Put(s)\n")
		buf.WriteString("\treturn r\n")
		buf.WriteString("}\n\n")
	}
}

// emitFastCallIF emits the shared int+float backend.
func emitFastCallIF(buf *bytes.Buffer, cfg fastPathConfig) {
	fmt.Fprintf(buf, `// fastCallIF calls cfn with numInts integer args (in a1..a15) and numFloats
// float args (pre-converted to bits in f1..f8). This is the shared backend
// for all fast-path float closures.
func fastCallIF(cfn uintptr, ints [%d]uintptr, numInts int, floats [8]uintptr, numFloats int) uintptr {
	s := thePool.Get().(*syscall15Args)
	s.fn = cfn
	// Set integer args
	switch {
	case numInts >= 8:
		s.a1, s.a2, s.a3, s.a4, s.a5, s.a6, s.a7, s.a8 = ints[0], ints[1], ints[2], ints[3], ints[4], ints[5], ints[6], ints[7]
		switch numInts {
		case 8:
			s.a9, s.a10, s.a11, s.a12, s.a13, s.a14, s.a15 = 0, 0, 0, 0, 0, 0, 0
		case 9:
			s.a9 = ints[8]
			s.a10, s.a11, s.a12, s.a13, s.a14, s.a15 = 0, 0, 0, 0, 0, 0
`, cfg.MaxIntArgs)

	for ni := 10; ni <= cfg.MaxIntArgs; ni++ {
		fmt.Fprintf(buf, "\t\tcase %d:\n", ni)
		parts := make([]string, ni-8)
		for i := 8; i < ni; i++ {
			parts[i-8] = fmt.Sprintf("ints[%d]", i)
		}
		fields := []string{"s.a9", "s.a10", "s.a11", "s.a12", "s.a13", "s.a14", "s.a15"}
		usedFields := fields[:ni-8]
		fmt.Fprintf(buf, "\t\t\t%s = %s\n", strings.Join(usedFields, ", "), strings.Join(parts, ", "))
		remaining := fields[ni-8:]
		if len(remaining) > 0 {
			zeros := make([]string, len(remaining))
			for i := range zeros {
				zeros[i] = "0"
			}
			fmt.Fprintf(buf, "\t\t\t%s = %s\n", strings.Join(remaining, ", "), strings.Join(zeros, ", "))
		}
	}

	buf.WriteString(`		}
	default:
		s.a1 = ints[0]
		s.a2 = ints[1]
		s.a3 = ints[2]
		s.a4 = ints[3]
		s.a5 = ints[4]
		s.a6 = ints[5]
		s.a7 = ints[6]
		s.a8 = 0
		s.a9, s.a10, s.a11, s.a12, s.a13, s.a14, s.a15 = 0, 0, 0, 0, 0, 0, 0
	}
	// Set float args
	s.f1 = floats[0]
	s.f2 = floats[1]
	s.f3 = floats[2]
	s.f4 = floats[3]
	s.f5 = floats[4]
	s.f6 = floats[5]
	s.f7 = floats[6]
	s.f8 = floats[7]
	s.arm64_r8 = 0
	runtime_cgocall(syscall15XABI0, unsafe.Pointer(s))
	r := s.a1
	thePool.Put(s)
	return r
}

`)
}

// emitPatternClosures emits per-pattern register* functions.
func emitPatternClosures(buf *bytes.Buffer, cfg fastPathConfig) {
	for _, p := range cfg.Patterns {
		switch {
		case p.NumFloats == 0:
			emitIntOnlyClosures(buf, cfg, p)
		case p.Layout == "trailing" && p.NumFloats == 1:
			emitTrailingFloat1Closures(buf, cfg, p)
		case p.Layout == "trailing" && p.NumFloats > 1:
			emitTrailingFloatNClosures(buf, cfg, p)
		case p.Layout == "interleaved" && p.NumFloats == 1 && p.FloatBits == 32:
			emitInterleavedFloat32x1Closures(buf, cfg, p)
		}
	}
}

// emitIntOnlyClosures emits registerFastFunc: int-only dispatcher.
func emitIntOnlyClosures(buf *bytes.Buffer, _ fastPathConfig, p fastPattern) {
	buf.WriteString(`// registerFastFunc sets fn to a zero-allocation closure that calls cfn
// without using reflect.MakeFunc.
func registerFastFunc(fn reflect.Value, cfn uintptr, numArgs int, hasReturn bool) {
	switch numArgs {
`)
	for n := p.MinInts; n <= p.MaxInts; n++ {
		params := paramList(n)
		args := argList(n)
		callArgs := "cfn"
		if args != "" {
			callArgs += ", " + args
		}
		fmt.Fprintf(buf, "\tcase %d:\n", n)
		fmt.Fprintf(buf, "\t\tif hasReturn {\n")
		fmt.Fprintf(buf, "\t\t\timpl := func(%s) uintptr { return fastCall%d(%s) }\n", params, n, callArgs)
		fmt.Fprintf(buf, "\t\t\tforceFuncPtr(fn, &impl)\n")
		fmt.Fprintf(buf, "\t\t} else {\n")
		fmt.Fprintf(buf, "\t\t\timpl := func(%s) { fastCall%d(%s) }\n", params, n, callArgs)
		fmt.Fprintf(buf, "\t\t\tforceFuncPtr(fn, &impl)\n")
		fmt.Fprintf(buf, "\t\t}\n")
	}
	buf.WriteString("\t}\n}\n\n")
}

// emitTrailingFloat1Closures emits registerFastFuncFloat{32,64}x1.
func emitTrailingFloat1Closures(buf *bytes.Buffer, cfg fastPathConfig, p fastPattern) {
	maxTrailingInts := max(p.MaxInts-1, 0) // leave room for the float
	typeName := "float32"
	bitsFunc := "math.Float32bits"
	suffix := "Float32x1"
	if p.FloatBits == 64 {
		typeName = "float64"
		bitsFunc = "math.Float64bits"
		suffix = "Float64x1"
	}

	fmt.Fprintf(buf, "// registerFastFunc%s handles N int args + 1 trailing %s.\n", suffix, typeName)
	fmt.Fprintf(buf, "func registerFastFunc%s(fn reflect.Value, cfn uintptr, numInts int, hasReturn bool) {\n", suffix)
	buf.WriteString("\tswitch numInts {\n")

	for n := p.MinInts; n <= maxTrailingInts; n++ {
		fmt.Fprintf(buf, "\tcase %d:\n", n)

		intParams := ""
		if n > 0 {
			intParams = argList(n) + " uintptr, "
		}

		var intsInit string
		if n == 0 {
			intsInit = fmt.Sprintf("var ints [%d]uintptr", cfg.MaxIntArgs)
		} else {
			intsInit = fmt.Sprintf("ints := [%d]uintptr{%s}", cfg.MaxIntArgs, argList(n))
		}

		fmt.Fprintf(buf, "\t\tif hasReturn {\n")
		fmt.Fprintf(buf, "\t\t\timpl := func(%sf1 %s) uintptr {\n", intParams, typeName)
		fmt.Fprintf(buf, "\t\t\t\t%s\n", intsInit)
		buf.WriteString("\t\t\t\tvar floats [8]uintptr\n")
		fmt.Fprintf(buf, "\t\t\t\tfloats[0] = uintptr(%s(f1))\n", bitsFunc)
		fmt.Fprintf(buf, "\t\t\t\treturn fastCallIF(cfn, ints, %d, floats, 1)\n", n)
		buf.WriteString(`			}
			forceFuncPtr(fn, &impl)
		} else {
`)

		fmt.Fprintf(buf, "\t\t\timpl := func(%sf1 %s) {\n", intParams, typeName)
		fmt.Fprintf(buf, "\t\t\t\t%s\n", intsInit)
		buf.WriteString("\t\t\t\tvar floats [8]uintptr\n")
		fmt.Fprintf(buf, "\t\t\t\tfloats[0] = uintptr(%s(f1))\n", bitsFunc)
		fmt.Fprintf(buf, "\t\t\t\tfastCallIF(cfn, ints, %d, floats, 1)\n", n)
		buf.WriteString(`			}
			forceFuncPtr(fn, &impl)
		}
`)
	}
	buf.WriteString("\t}\n}\n\n")
}

// emitTrailingFloatNClosures emits registerFastFuncFloat{32,64}xN for N>1 trailing floats.
func emitTrailingFloatNClosures(buf *bytes.Buffer, cfg fastPathConfig, p fastPattern) {
	maxTrailingInts := max(p.MaxInts-p.NumFloats, 0)
	typeName := "float32"
	bitsFunc := "math.Float32bits"
	if p.FloatBits == 64 {
		typeName = "float64"
		bitsFunc = "math.Float64bits"
	}

	funcName := fmt.Sprintf("registerFastFunc%s", p.Name)
	fmt.Fprintf(buf, "// %s handles N int args + %d trailing %s.\n", funcName, p.NumFloats, typeName)
	fmt.Fprintf(buf, "func %s(fn reflect.Value, cfn uintptr, numInts int, hasReturn bool) {\n", funcName)
	buf.WriteString("\tswitch numInts {\n")

	for n := p.MinInts; n <= maxTrailingInts; n++ {
		fmt.Fprintf(buf, "\tcase %d:\n", n)

		intParams := ""
		if n > 0 {
			intParams = argList(n) + " uintptr, "
		}

		var intsInit string
		if n == 0 {
			intsInit = fmt.Sprintf("var ints [%d]uintptr", cfg.MaxIntArgs)
		} else {
			intsInit = fmt.Sprintf("ints := [%d]uintptr{%s}", cfg.MaxIntArgs, argList(n))
		}

		floatParams := floatParamList(p.NumFloats, p.FloatBits)

		fmt.Fprintf(buf, "\t\tif hasReturn {\n")
		fmt.Fprintf(buf, "\t\t\timpl := func(%s%s) uintptr {\n", intParams, floatParams)
		fmt.Fprintf(buf, "\t\t\t\t%s\n", intsInit)
		buf.WriteString("\t\t\t\tvar floats [8]uintptr\n")
		for fi := 0; fi < p.NumFloats; fi++ {
			fmt.Fprintf(buf, "\t\t\t\tfloats[%d] = uintptr(%s(f%d))\n", fi, bitsFunc, fi+1)
		}
		fmt.Fprintf(buf, "\t\t\t\treturn fastCallIF(cfn, ints, %d, floats, %d)\n", n, p.NumFloats)
		buf.WriteString(`			}
			forceFuncPtr(fn, &impl)
		} else {
`)

		fmt.Fprintf(buf, "\t\t\timpl := func(%s%s) {\n", intParams, floatParams)
		fmt.Fprintf(buf, "\t\t\t\t%s\n", intsInit)
		buf.WriteString("\t\t\t\tvar floats [8]uintptr\n")
		for fi := 0; fi < p.NumFloats; fi++ {
			fmt.Fprintf(buf, "\t\t\t\tfloats[%d] = uintptr(%s(f%d))\n", fi, bitsFunc, fi+1)
		}
		fmt.Fprintf(buf, "\t\t\t\tfastCallIF(cfn, ints, %d, floats, %d)\n", n, p.NumFloats)
		buf.WriteString(`			}
			forceFuncPtr(fn, &impl)
		}
`)
	}
	buf.WriteString("\t}\n}\n\n")
}

// emitInterleavedFloat32x1Closures emits registerFastFuncInterleavedFloat32x1.
func emitInterleavedFloat32x1Closures(buf *bytes.Buffer, cfg fastPathConfig, p fastPattern) {
	buf.WriteString(`// registerFastFuncInterleavedFloat32x1 sets fn to a zero-allocation closure
// for functions with totalArgs parameters where exactly one is float32 at
// position floatPos (not the last position — trailing floats are handled by
// registerFastFuncFloat32x1).
func registerFastFuncInterleavedFloat32x1(fn reflect.Value, cfn uintptr, totalArgs, floatPos int, hasReturn bool) {
	switch totalArgs {
`)
	for totalArgs := 2; totalArgs <= p.MaxInts+1; totalArgs++ {
		fmt.Fprintf(buf, "\tcase %d:\n", totalArgs)
		fmt.Fprintf(buf, "\t\tswitch floatPos {\n")

		for floatPos := 0; floatPos <= totalArgs-2; floatPos++ {
			numInts := totalArgs - 1
			fmt.Fprintf(buf, "\t\tcase %d:\n", floatPos)

			fmt.Fprintf(buf, "\t\t\tif hasReturn {\n")
			fmt.Fprintf(buf, "\t\t\t\timpl := func(%s) uintptr {\n", interleavedParams(totalArgs, floatPos))
			fmt.Fprintf(buf, "\t\t\t\t\tints := [%d]uintptr{%s}\n", cfg.MaxIntArgs, interleavedIntArgs(totalArgs))
			buf.WriteString("\t\t\t\t\tvar floats [8]uintptr\n")
			buf.WriteString("\t\t\t\t\tfloats[0] = uintptr(math.Float32bits(f1))\n")
			fmt.Fprintf(buf, "\t\t\t\t\treturn fastCallIF(cfn, ints, %d, floats, 1)\n", numInts)
			buf.WriteString(`				}
				forceFuncPtr(fn, &impl)
			} else {
`)

			fmt.Fprintf(buf, "\t\t\t\timpl := func(%s) {\n", interleavedParams(totalArgs, floatPos))
			fmt.Fprintf(buf, "\t\t\t\t\tints := [%d]uintptr{%s}\n", cfg.MaxIntArgs, interleavedIntArgs(totalArgs))
			buf.WriteString("\t\t\t\t\tvar floats [8]uintptr\n")
			buf.WriteString("\t\t\t\t\tfloats[0] = uintptr(math.Float32bits(f1))\n")
			fmt.Fprintf(buf, "\t\t\t\t\tfastCallIF(cfn, ints, %d, floats, 1)\n", numInts)
			buf.WriteString(`				}
				forceFuncPtr(fn, &impl)
			}
`)
		}

		fmt.Fprintf(buf, "\t\t}\n")
	}
	buf.WriteString("\t}\n}\n\n")
}

func interleavedParams(totalArgs, floatPos int) string {
	var parts []string
	intIdx := 1
	for i := range totalArgs {
		if i == floatPos {
			parts = append(parts, "f1 float32")
		} else {
			parts = append(parts, fmt.Sprintf("a%d uintptr", intIdx))
			intIdx++
		}
	}
	return strings.Join(parts, ", ")
}

func interleavedIntArgs(totalArgs int) string {
	numInts := totalArgs - 1
	parts := make([]string, numInts)
	for i := range numInts {
		parts[i] = fmt.Sprintf("a%d", i+1)
	}
	return strings.Join(parts, ", ")
}

// emitFloatNFallback emits the MakeFunc fallback for unmatched float sigs.
func emitFloatNFallback(buf *bytes.Buffer, cfg fastPathConfig) {
	fmt.Fprintf(buf, `// registerFastFuncFloatN handles functions with interleaved or multiple float args.
// Falls back to reflect.MakeFunc since the combinatorial explosion of
// concrete closures is not worth the code size.
func registerFastFuncFloatN(fn reflect.Value, cfn uintptr, ty reflect.Type, numInts, numFloats int, hasReturn bool) {
	numIn := ty.NumIn()
	v := reflect.MakeFunc(ty, func(args []reflect.Value) []reflect.Value {
		var ints [%d]uintptr
		var floats [8]uintptr
		var ii, fi int
		for i := 0; i < numIn; i++ {
			switch ty.In(i).Kind() {
			case reflect.Float32:
				floats[fi] = uintptr(math.Float32bits(float32(args[i].Float())))
				fi++
			case reflect.Float64:
				floats[fi] = uintptr(math.Float64bits(args[i].Float()))
				fi++
			case reflect.Bool:
				if args[i].Bool() {
					ints[ii] = 1
				}
				ii++
			case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
				ints[ii] = uintptr(args[i].Int())
				ii++
			case reflect.Pointer, reflect.UnsafePointer:
				ints[ii] = args[i].Pointer()
				ii++
			default:
				ints[ii] = uintptr(args[i].Uint())
				ii++
			}
		}
		r := fastCallIF(cfn, ints, numInts, floats, numFloats)
		if !hasReturn {
			return nil
		}
		out := reflect.New(ty.Out(0)).Elem()
		switch ty.Out(0).Kind() {
		case reflect.Uintptr, reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
			out.SetUint(uint64(r))
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
			out.SetInt(int64(r))
		case reflect.Bool:
			out.SetBool(byte(r) != 0)
		case reflect.UnsafePointer:
			out.SetPointer(*(*unsafe.Pointer)(unsafe.Pointer(&r)))
		case reflect.Pointer:
			out = reflect.NewAt(ty.Out(0), unsafe.Pointer(&r)).Elem()
		}
		if len(args) > 0 {
			args[0] = out
			return args[:1]
		}
		return []reflect.Value{out}
	})
	fn.Set(v)
}

`, cfg.MaxIntArgs)
}

// emitTryRegisterFastPath emits the unified routing dispatcher.
func emitTryRegisterFastPath(buf *bytes.Buffer, cfg fastPathConfig) {
	fmt.Fprintf(buf, `// tryRegisterFastPath attempts to install a zero-allocation fast-path closure
// for fn. Returns true if successful, false if the caller should use the slow path.
func tryRegisterFastPath(fn reflect.Value, cfn uintptr, ty reflect.Type) bool {
	numIn := ty.NumIn()
	if !((runtime.GOARCH == "amd64" || runtime.GOARCH == "arm64") && runtime.GOOS != "windows") {
		return false
	}
	if numIn > %d {
		return false
	}

	canFastPath := true
	numFloats := 0
	numInts := 0
	hasStructs := false
	hasSmallStackArg := false
	trailingFloats := true
	seenFloat := false
	floatPos := -1
	intRegCount := numOfIntegerRegisters()

	for i := 0; i < numIn; i++ {
		switch ty.In(i).Kind() {
		case reflect.Uintptr, reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
			reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Bool, reflect.Pointer, reflect.UnsafePointer:
			if seenFloat {
				trailingFloats = false
			}
			if numInts >= intRegCount && ty.In(i).Size() < unsafe.Sizeof(uintptr(0)) {
				hasSmallStackArg = true
			}
			numInts++
		case reflect.Float32, reflect.Float64:
			if !seenFloat {
				floatPos = i
			}
			seenFloat = true
			numFloats++
		case reflect.Struct:
			if isSmallRegStruct(ty.In(i)) {
				if seenFloat {
					trailingFloats = false
				}
				hasStructs = true
				numInts++
			} else {
				canFastPath = false
			}
		default:
			canFastPath = false
		}
	}
	if numFloats > %d {
		canFastPath = false
	}
	if numInts > %d {
		canFastPath = false
	}
	if ty.NumOut() == 1 {
		switch ty.Out(0).Kind() {
		case reflect.Uintptr, reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
			reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Bool, reflect.Pointer, reflect.UnsafePointer:
		default:
			canFastPath = false
		}
	}
	if hasSmallStackArg {
		canFastPath = false
	}
	if !canFastPath {
		return false
	}

	hasReturn := ty.NumOut() > 0
	if hasStructs {
		registerFastFuncWithStructs(fn, cfn, ty, numInts, numFloats, hasReturn)
		return true
	}

`, cfg.MaxIntArgs, cfg.MaxFloatArgs, cfg.MaxIntArgs)

	// Emit pattern matching in config order.
	buf.WriteString("\t// Pattern matching in config order\n")

	for _, p := range cfg.Patterns {
		switch {
		case p.NumFloats == 0:
			// Int-only: numFloats == 0
			buf.WriteString(`	if numFloats == 0 {
		registerFastFunc(fn, cfn, numInts, hasReturn)
		return true
	}

`)

		case p.Layout == "trailing" && p.NumFloats == 1 && p.FloatBits == 32:
			buf.WriteString(`	// Trailing float32x1
	if numFloats == 1 && trailingFloats && ty.In(numInts).Kind() == reflect.Float32 {
		registerFastFuncFloat32x1(fn, cfn, numInts, hasReturn)
		return true
	}

`)

		case p.Layout == "trailing" && p.NumFloats == 1 && p.FloatBits == 64:
			buf.WriteString(`	// Trailing float64x1
	if numFloats == 1 && trailingFloats && ty.In(numInts).Kind() == reflect.Float64 {
		registerFastFuncFloat64x1(fn, cfn, numInts, hasReturn)
		return true
	}

`)

		case p.Layout == "interleaved" && p.NumFloats == 1 && p.FloatBits == 32:
			buf.WriteString(`	// Interleaved float32x1
	if numFloats == 1 && !trailingFloats && ty.In(floatPos).Kind() == reflect.Float32 {
		registerFastFuncInterleavedFloat32x1(fn, cfn, numIn, floatPos, hasReturn)
		return true
	}

`)

		case p.Layout == "trailing" && p.NumFloats > 1:
			fmt.Fprintf(buf, "\t// %s: %d trailing %d-bit floats\n", p.Name, p.NumFloats, p.FloatBits)
			floatKind := "reflect.Float32"
			if p.FloatBits == 64 {
				floatKind = "reflect.Float64"
			}
			fmt.Fprintf(buf, "\tif numFloats == %d && trailingFloats {\n", p.NumFloats)
			// Verify all floats are the right type
			buf.WriteString("\t\tallMatch := true\n")
			fmt.Fprintf(buf, "\t\tfor i := numInts; i < numIn; i++ {\n")
			fmt.Fprintf(buf, "\t\t\tif ty.In(i).Kind() != %s {\n", floatKind)
			buf.WriteString(`				allMatch = false
				break
			}
		}
		if allMatch {
`)
			fmt.Fprintf(buf, "\t\t\tregisterFastFunc%s(fn, cfn, numInts, hasReturn)\n", p.Name)
			buf.WriteString(`			return true
		}
	}

`)
		}
	}

	// Final fallback: MakeFunc for any remaining float sigs
	buf.WriteString(`	// Fallback: MakeFunc for unmatched float patterns
	registerFastFuncFloatN(fn, cfn, ty, numInts, numFloats, hasReturn)
	return true
}

`)
}

// emitForceFuncPtr emits the unsafe func-ptr swap utility.
func emitForceFuncPtr(buf *bytes.Buffer) {
	buf.WriteString(`// forceFuncPtr assigns the function pointer in src to the reflect.Value dst,
// bypassing type checking. This is safe when the source and destination function
// types have identical ABI layouts (same number of pointer-sized args/returns).
func forceFuncPtr(dst reflect.Value, src any) {
	dstPtr := dst.Addr().UnsafePointer() // *func(...)
	srcPtr := (*unsafe.Pointer)(reflect.ValueOf(src).UnsafePointer())
	*(*unsafe.Pointer)(dstPtr) = *srcPtr
}
`)
}
