// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The Ebitengine Authors

//go:build ignore

// genfastfunc generates zero-allocation closures for RegisterFunc's fast path.
// The output file is zz_fast_func.go.
//
// All generated code is driven by a single declarative config (defaultConfig).
// To add a new fast-path pattern, add a fastPattern entry and re-run go generate.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
	"text/template"
)

// fastPathConfig describes every fast-path pattern the generator should emit.
type fastPathConfig struct {
	MaxIntArgs   int           // max integer args (e.g. 15)
	MaxFloatArgs int           // max float register args (e.g. 8)
	Patterns     []fastPattern // patterns to emit, matched in order
}

type fastPattern struct {
	Name      string // "IntOnly", "TrailingFloat32x1", etc.
	MinInts   int    // min integer args (0 = no minimum)
	MaxInts   int    // max integer args (-1 = config.MaxIntArgs)
	NumFloats int    // exact float count (0 = int-only)
	FloatBits int    // 32 or 64 (0 = N/A for int-only)
	Layout    string // "trailing", "interleaved", "any" (empty = N/A for int-only)
}

var defaultConfig = fastPathConfig{
	MaxIntArgs:   15,
	MaxFloatArgs: 8,
	Patterns: []fastPattern{
		{Name: "IntOnly", MaxInts: -1, NumFloats: 0},
		{Name: "TrailingFloat32x1", MaxInts: -1, NumFloats: 1, FloatBits: 32, Layout: "trailing"},
		{Name: "TrailingFloat64x1", MaxInts: -1, NumFloats: 1, FloatBits: 64, Layout: "trailing"},
		{Name: "InterleavedFloat32x1", MinInts: 1, MaxInts: -1, NumFloats: 1, FloatBits: 32, Layout: "interleaved"},
	},
}

func main() {
	cfg := defaultConfig
	resolveConfig(&cfg)

	var buf bytes.Buffer
	execTemplate(&buf, "header", tmplHeader, cfg)
	emitFastCallN(&buf, cfg)
	emitFastCallIF(&buf, cfg)
	emitPatternClosures(&buf, cfg)
	emitFloatNFallback(&buf, cfg)
	emitTryRegisterFastPath(&buf, cfg)
	execTemplate(&buf, "forceFuncPtr", tmplForceFuncPtr, nil)

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("gofmt: %v\n%s", err, buf.String())
	}
	if err := os.WriteFile("zz_fast_func.go", src, 0644); err != nil {
		log.Fatal(err)
	}
}

// resolveConfig expands MaxInts == -1 to cfg.MaxIntArgs.
func resolveConfig(cfg *fastPathConfig) {
	for i := range cfg.Patterns {
		if cfg.Patterns[i].MaxInts == -1 {
			cfg.Patterns[i].MaxInts = cfg.MaxIntArgs
		}
	}
}

var funcs = template.FuncMap{
	"seq":       seq,
	"add":       func(a, b int) int { return a + b },
	"sub":       func(a, b int) int { return a - b },
	"join":      strings.Join,
	"argList":   argList,
	"paramList": paramList,
}

func execTemplate(buf *bytes.Buffer, name, text string, data any) {
	t := template.Must(template.New(name).Funcs(funcs).Parse(text))
	if err := t.Execute(buf, data); err != nil {
		log.Fatalf("template %s: %v", name, err)
	}
}

// seq returns a slice [0, 1, ..., n-1].
func seq(n int) []int {
	s := make([]int, n)
	for i := range s {
		s[i] = i
	}
	return s
}

func argList(n int) string {
	if n == 0 {
		return ""
	}
	parts := make([]string, n)
	for i := range n {
		parts[i] = fmt.Sprintf("a%d", i+1)
	}
	return strings.Join(parts, ", ")
}

func paramList(n int) string {
	if n == 0 {
		return ""
	}
	return argList(n) + " uintptr"
}

func floatParamList(n int, bits int) string {
	ty := "float32"
	if bits == 64 {
		ty = "float64"
	}
	parts := make([]string, n)
	for i := range n {
		parts[i] = fmt.Sprintf("f%d", i+1)
	}
	return strings.Join(parts, ", ") + " " + ty
}

func interleavedParams(totalArgs, floatPos int) string {
	var parts []string
	intIdx := 1
	for i := range totalArgs {
		if i == floatPos {
			parts = append(parts, "f1 float32")
		} else {
			parts = append(parts, fmt.Sprintf("a%d uintptr", intIdx))
			intIdx++
		}
	}
	return strings.Join(parts, ", ")
}

func interleavedIntArgs(totalArgs int) string {
	numInts := totalArgs - 1
	parts := make([]string, numInts)
	for i := range numInts {
		parts[i] = fmt.Sprintf("a%d", i+1)
	}
	return strings.Join(parts, ", ")
}

var tmplHeader = `// Code generated by genfastfunc.go; DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The Ebitengine Authors

//go:build darwin || freebsd || linux || netbsd || windows

package purego

import (
	"math"
	"reflect"
	"runtime"
	"unsafe"
)

`

var tmplForceFuncPtr = `// forceFuncPtr assigns the function pointer in src to the reflect.Value dst,
// bypassing type checking. This is safe when the source and destination function
// types have identical ABI layouts (same number of pointer-sized args/returns).
func forceFuncPtr(dst reflect.Value, src any) {
	dstPtr := dst.Addr().UnsafePointer() // *func(...)
	srcPtr := (*unsafe.Pointer)(reflect.ValueOf(src).UnsafePointer())
	*(*unsafe.Pointer)(dstPtr) = *srcPtr
}
`

// fastCallData holds the computed fields for one fastCallN function.
type fastCallData struct {
	N      int
	Params string // "cfn, a1, a2 uintptr"
	A1to8  string // "a1, a2, 0, 0, 0, 0, 0, 0"
	A9to15 string // pre-formatted assignment lines for a9..a15
}

var tmplFastCallN = `{{range .}}func fastCall{{.N}}({{.Params}} uintptr) uintptr {
	s := thePool.Get().(*syscall15Args)
	s.fn = cfn
	s.a1, s.a2, s.a3, s.a4, s.a5, s.a6, s.a7, s.a8 = {{.A1to8}}
{{.A9to15}}	s.f1, s.f2, s.f3, s.f4, s.f5, s.f6, s.f7, s.f8 = 0, 0, 0, 0, 0, 0, 0, 0
	s.arm64_r8 = 0
	runtime_cgocall(syscall15XABI0, unsafe.Pointer(s))
	r := s.a1
	thePool.Put(s)
	return r
}

{{end}}`

func emitFastCallN(buf *bytes.Buffer, cfg fastPathConfig) {
	var data []fastCallData
	for n := 0; n <= cfg.MaxIntArgs; n++ {
		params := "cfn"
		if n > 0 {
			params += ", " + argList(n)
		}
		data = append(data, fastCallData{
			N:      n,
			Params: params,
			A1to8:  buildA1to8(n),
			A9to15: buildA9to15(n),
		})
	}
	execTemplate(buf, "fastCallN", tmplFastCallN, data)
}

func buildA1to8(n int) string {
	if n == 0 {
		return "0, 0, 0, 0, 0, 0, 0, 0"
	}
	parts := make([]string, 8)
	for i := range 8 {
		if i < n {
			parts[i] = fmt.Sprintf("a%d", i+1)
		} else {
			parts[i] = "0"
		}
	}
	return strings.Join(parts, ", ")
}

func buildA9to15(n int) string {
	fields := []string{"s.a9", "s.a10", "s.a11", "s.a12", "s.a13", "s.a14", "s.a15"}
	if n <= 8 {
		return "\ts.a9, s.a10, s.a11, s.a12, s.a13, s.a14, s.a15 = 0, 0, 0, 0, 0, 0, 0\n"
	}
	overflow := make([]string, n-8)
	for i := 8; i < n; i++ {
		overflow[i-8] = fmt.Sprintf("a%d", i+1)
	}
	s := fmt.Sprintf("\t%s = %s\n", strings.Join(fields[:len(overflow)], ", "), strings.Join(overflow, ", "))
	remaining := fields[len(overflow):]
	if len(remaining) > 0 {
		zeros := make([]string, len(remaining))
		for i := range zeros {
			zeros[i] = "0"
		}
		s += fmt.Sprintf("\t%s = %s\n", strings.Join(remaining, ", "), strings.Join(zeros, ", "))
	}
	return s
}

func emitFastCallIF(buf *bytes.Buffer, cfg fastPathConfig) {
	type ifCaseData struct {
		N        int
		Assign   string // "s.a9, s.a10 = ints[8], ints[9]"
		ZeroRest string // "s.a11, ... = 0, 0, ..."
		HasZeros bool
	}

	type ifData struct {
		MaxIntArgs int
		Cases      []ifCaseData
	}

	var cases []ifCaseData
	for ni := 10; ni <= cfg.MaxIntArgs; ni++ {
		fields := []string{"s.a9", "s.a10", "s.a11", "s.a12", "s.a13", "s.a14", "s.a15"}
		parts := make([]string, ni-8)
		for i := 8; i < ni; i++ {
			parts[i-8] = fmt.Sprintf("ints[%d]", i)
		}
		usedFields := fields[:ni-8]
		remaining := fields[ni-8:]
		c := ifCaseData{
			N:      ni,
			Assign: strings.Join(usedFields, ", ") + " = " + strings.Join(parts, ", "),
		}
		if len(remaining) > 0 {
			zeros := make([]string, len(remaining))
			for i := range zeros {
				zeros[i] = "0"
			}
			c.ZeroRest = strings.Join(remaining, ", ") + " = " + strings.Join(zeros, ", ")
			c.HasZeros = true
		}
		cases = append(cases, c)
	}

	execTemplate(buf, "fastCallIF", tmplFastCallIF, ifData{
		MaxIntArgs: cfg.MaxIntArgs,
		Cases:      cases,
	})
}

var tmplFastCallIF = `// fastCallIF calls cfn with numInts integer args (in a1..a15) and numFloats
// float args (pre-converted to bits in f1..f8). This is the shared backend
// for all fast-path float closures.
func fastCallIF(cfn uintptr, ints [{{.MaxIntArgs}}]uintptr, numInts int, floats [8]uintptr, numFloats int) uintptr {
	s := thePool.Get().(*syscall15Args)
	s.fn = cfn
	// Set integer args. Callers initialize ints via composite literals
	// (e.g. [15]uintptr{a1, a2}), so elements beyond numInts are always zero.
	switch {
	case numInts >= 8:
		s.a1, s.a2, s.a3, s.a4, s.a5, s.a6, s.a7, s.a8 = ints[0], ints[1], ints[2], ints[3], ints[4], ints[5], ints[6], ints[7]
		switch numInts {
		case 8:
			s.a9, s.a10, s.a11, s.a12, s.a13, s.a14, s.a15 = 0, 0, 0, 0, 0, 0, 0
		case 9:
			s.a9 = ints[8]
			s.a10, s.a11, s.a12, s.a13, s.a14, s.a15 = 0, 0, 0, 0, 0, 0
{{- range .Cases}}
		case {{.N}}:
			{{.Assign}}
{{- if .HasZeros}}
			{{.ZeroRest}}
{{- end}}
{{- end}}
		}
	default:
		s.a1 = ints[0]
		s.a2 = ints[1]
		s.a3 = ints[2]
		s.a4 = ints[3]
		s.a5 = ints[4]
		s.a6 = ints[5]
		s.a7 = ints[6]
		s.a8 = 0
		s.a9, s.a10, s.a11, s.a12, s.a13, s.a14, s.a15 = 0, 0, 0, 0, 0, 0, 0
	}
	// Set float args
	s.f1 = floats[0]
	s.f2 = floats[1]
	s.f3 = floats[2]
	s.f4 = floats[3]
	s.f5 = floats[4]
	s.f6 = floats[5]
	s.f7 = floats[6]
	s.f8 = floats[7]
	s.arm64_r8 = 0
	runtime_cgocall(syscall15XABI0, unsafe.Pointer(s))
	r := s.a1
	thePool.Put(s)
	return r
}

`

func emitPatternClosures(buf *bytes.Buffer, cfg fastPathConfig) {
	for _, p := range cfg.Patterns {
		switch {
		case p.NumFloats == 0:
			emitIntOnlyClosures(buf, cfg, p)
		case p.Layout == "trailing" && p.NumFloats == 1:
			emitTrailingFloat1Closures(buf, cfg, p)
		case p.Layout == "trailing" && p.NumFloats > 1:
			emitTrailingFloatNClosures(buf, cfg, p)
		case p.Layout == "interleaved" && p.NumFloats == 1 && p.FloatBits == 32:
			emitInterleavedFloat32x1Closures(buf, cfg, p)
		}
	}
}

type intOnlyCaseData struct {
	N        int
	Params   string // "a1, a2 uintptr"
	CallArgs string // "cfn, a1, a2"
}

var tmplIntOnlyClosures = `// registerFastFunc sets fn to a zero-allocation closure that calls cfn
// without using reflect.MakeFunc.
func registerFastFunc(fn reflect.Value, cfn uintptr, numArgs int, hasReturn bool) {
	switch numArgs {
{{- range .}}
	case {{.N}}:
		if hasReturn {
			impl := func({{.Params}}) uintptr { return fastCall{{.N}}({{.CallArgs}}) }
			forceFuncPtr(fn, &impl)
		} else {
			impl := func({{.Params}}) { fastCall{{.N}}({{.CallArgs}}) }
			forceFuncPtr(fn, &impl)
		}
{{- end}}
	}
}

`

func emitIntOnlyClosures(buf *bytes.Buffer, _ fastPathConfig, p fastPattern) {
	var cases []intOnlyCaseData
	for n := p.MinInts; n <= p.MaxInts; n++ {
		params := paramList(n)
		args := argList(n)
		callArgs := "cfn"
		if args != "" {
			callArgs += ", " + args
		}
		cases = append(cases, intOnlyCaseData{N: n, Params: params, CallArgs: callArgs})
	}
	execTemplate(buf, "intOnlyClosures", tmplIntOnlyClosures, cases)
}

type trailingFloat1CaseData struct {
	N         int
	IntParams string // "a1, a2 uintptr, " (with trailing comma) or ""
	TypeName  string // "float32" or "float64"
	IntsInit  string // "ints := [15]uintptr{a1, a2}"
	BitsFunc  string // "math.Float32bits"
}

type trailingFloat1Data struct {
	Suffix   string
	TypeName string
	Cases    []trailingFloat1CaseData
}

var tmplTrailingFloat1 = `// registerFastFunc{{.Suffix}} handles N int args + 1 trailing {{.TypeName}}.
func registerFastFunc{{.Suffix}}(fn reflect.Value, cfn uintptr, numInts int, hasReturn bool) {
	switch numInts {
{{- range .Cases}}
	case {{.N}}:
		if hasReturn {
			impl := func({{.IntParams}}f1 {{.TypeName}}) uintptr {
				{{.IntsInit}}
				var floats [8]uintptr
				floats[0] = uintptr({{.BitsFunc}}(f1))
				return fastCallIF(cfn, ints, {{.N}}, floats, 1)
			}
			forceFuncPtr(fn, &impl)
		} else {
			impl := func({{.IntParams}}f1 {{.TypeName}}) {
				{{.IntsInit}}
				var floats [8]uintptr
				floats[0] = uintptr({{.BitsFunc}}(f1))
				fastCallIF(cfn, ints, {{.N}}, floats, 1)
			}
			forceFuncPtr(fn, &impl)
		}
{{- end}}
	}
}

`

func emitTrailingFloat1Closures(buf *bytes.Buffer, cfg fastPathConfig, p fastPattern) {
	maxTrailingInts := max(p.MaxInts-1, 0)
	typeName := "float32"
	bitsFunc := "math.Float32bits"
	suffix := "Float32x1"
	if p.FloatBits == 64 {
		typeName = "float64"
		bitsFunc = "math.Float64bits"
		suffix = "Float64x1"
	}

	var cases []trailingFloat1CaseData
	for n := p.MinInts; n <= maxTrailingInts; n++ {
		intParams := ""
		if n > 0 {
			intParams = argList(n) + " uintptr, "
		}
		var intsInit string
		if n == 0 {
			intsInit = fmt.Sprintf("var ints [%d]uintptr", cfg.MaxIntArgs)
		} else {
			intsInit = fmt.Sprintf("ints := [%d]uintptr{%s}", cfg.MaxIntArgs, argList(n))
		}
		cases = append(cases, trailingFloat1CaseData{
			N: n, IntParams: intParams, TypeName: typeName,
			IntsInit: intsInit, BitsFunc: bitsFunc,
		})
	}
	execTemplate(buf, "trailingFloat1_"+suffix, tmplTrailingFloat1, trailingFloat1Data{
		Suffix: suffix, TypeName: typeName, Cases: cases,
	})
}

type trailingFloatNCaseData struct {
	N            int
	IntParams    string // "a1, a2 uintptr, " or ""
	FloatParams  string // "f1, f2 float32"
	IntsInit     string
	FloatAssigns string // "\t\t\t\tfloats[0] = ...\n\t\t\t\tfloats[1] = ..."
	NumFloats    int
}

type trailingFloatNData struct {
	FuncName  string
	NumFloats int
	TypeName  string
	Cases     []trailingFloatNCaseData
}

var tmplTrailingFloatN = `// {{.FuncName}} handles N int args + {{.NumFloats}} trailing {{.TypeName}}.
func {{.FuncName}}(fn reflect.Value, cfn uintptr, numInts int, hasReturn bool) {
	switch numInts {
{{- range .Cases}}
	case {{.N}}:
		if hasReturn {
			impl := func({{.IntParams}}{{.FloatParams}}) uintptr {
				{{.IntsInit}}
				var floats [8]uintptr
{{.FloatAssigns}}				return fastCallIF(cfn, ints, {{.N}}, floats, {{.NumFloats}})
			}
			forceFuncPtr(fn, &impl)
		} else {
			impl := func({{.IntParams}}{{.FloatParams}}) {
				{{.IntsInit}}
				var floats [8]uintptr
{{.FloatAssigns}}				fastCallIF(cfn, ints, {{.N}}, floats, {{.NumFloats}})
			}
			forceFuncPtr(fn, &impl)
		}
{{- end}}
	}
}

`

func emitTrailingFloatNClosures(buf *bytes.Buffer, cfg fastPathConfig, p fastPattern) {
	maxTrailingInts := max(p.MaxInts-p.NumFloats, 0)
	typeName := "float32"
	bitsFunc := "math.Float32bits"
	if p.FloatBits == 64 {
		typeName = "float64"
		bitsFunc = "math.Float64bits"
	}
	funcName := "registerFastFunc" + p.Name

	var cases []trailingFloatNCaseData
	for n := p.MinInts; n <= maxTrailingInts; n++ {
		intParams := ""
		if n > 0 {
			intParams = argList(n) + " uintptr, "
		}
		var intsInit string
		if n == 0 {
			intsInit = fmt.Sprintf("var ints [%d]uintptr", cfg.MaxIntArgs)
		} else {
			intsInit = fmt.Sprintf("ints := [%d]uintptr{%s}", cfg.MaxIntArgs, argList(n))
		}
		var floatAssigns string
		for fi := 0; fi < p.NumFloats; fi++ {
			floatAssigns += fmt.Sprintf("\t\t\t\tfloats[%d] = uintptr(%s(f%d))\n", fi, bitsFunc, fi+1)
		}
		cases = append(cases, trailingFloatNCaseData{
			N: n, IntParams: intParams,
			FloatParams:  floatParamList(p.NumFloats, p.FloatBits),
			IntsInit:     intsInit,
			FloatAssigns: floatAssigns,
			NumFloats:    p.NumFloats,
		})
	}
	execTemplate(buf, "trailingFloatN_"+p.Name, tmplTrailingFloatN, trailingFloatNData{
		FuncName: funcName, NumFloats: p.NumFloats, TypeName: typeName, Cases: cases,
	})
}

type interleavedCaseData struct {
	FloatPos int
	Params   string // "a1 uintptr, f1 float32, a2 uintptr"
	IntsInit string // "ints := [15]uintptr{a1, a2}"
	NumInts  int
}

type interleavedTotalData struct {
	TotalArgs int
	Cases     []interleavedCaseData
}

var tmplInterleavedFloat32x1 = `// registerFastFuncInterleavedFloat32x1 sets fn to a zero-allocation closure
// for functions with totalArgs parameters where exactly one is float32 at
// position floatPos (not the last position — trailing floats are handled by
// registerFastFuncFloat32x1).
func registerFastFuncInterleavedFloat32x1(fn reflect.Value, cfn uintptr, totalArgs, floatPos int, hasReturn bool) {
	switch totalArgs {
{{- range .}}
	case {{.TotalArgs}}:
		switch floatPos {
{{- range .Cases}}
		case {{.FloatPos}}:
			if hasReturn {
				impl := func({{.Params}}) uintptr {
					{{.IntsInit}}
					var floats [8]uintptr
					floats[0] = uintptr(math.Float32bits(f1))
					return fastCallIF(cfn, ints, {{.NumInts}}, floats, 1)
				}
				forceFuncPtr(fn, &impl)
			} else {
				impl := func({{.Params}}) {
					{{.IntsInit}}
					var floats [8]uintptr
					floats[0] = uintptr(math.Float32bits(f1))
					fastCallIF(cfn, ints, {{.NumInts}}, floats, 1)
				}
				forceFuncPtr(fn, &impl)
			}
{{- end}}
		}
{{- end}}
	}
}

`

func emitInterleavedFloat32x1Closures(buf *bytes.Buffer, cfg fastPathConfig, p fastPattern) {
	var groups []interleavedTotalData
	for totalArgs := 2; totalArgs <= p.MaxInts+1; totalArgs++ {
		var cases []interleavedCaseData
		for floatPos := 0; floatPos <= totalArgs-2; floatPos++ {
			numInts := totalArgs - 1
			cases = append(cases, interleavedCaseData{
				FloatPos: floatPos,
				Params:   interleavedParams(totalArgs, floatPos),
				IntsInit: fmt.Sprintf("ints := [%d]uintptr{%s}", cfg.MaxIntArgs, interleavedIntArgs(totalArgs)),
				NumInts:  numInts,
			})
		}
		groups = append(groups, interleavedTotalData{TotalArgs: totalArgs, Cases: cases})
	}
	execTemplate(buf, "interleavedFloat32x1", tmplInterleavedFloat32x1, groups)
}

var tmplFloatNFallback = `// registerFastFuncFloatN handles functions with interleaved or multiple float args.
// Falls back to reflect.MakeFunc since the combinatorial explosion of
// concrete closures is not worth the code size.
func registerFastFuncFloatN(fn reflect.Value, cfn uintptr, ty reflect.Type, numInts, numFloats int, hasReturn bool) {
	numIn := ty.NumIn()
	v := reflect.MakeFunc(ty, func(args []reflect.Value) []reflect.Value {
		var ints [{{.MaxIntArgs}}]uintptr
		var floats [8]uintptr
		var ii, fi int
		for i := 0; i < numIn; i++ {
			switch ty.In(i).Kind() {
			case reflect.Float32:
				floats[fi] = uintptr(math.Float32bits(float32(args[i].Float())))
				fi++
			case reflect.Float64:
				floats[fi] = uintptr(math.Float64bits(args[i].Float()))
				fi++
			case reflect.Bool:
				if args[i].Bool() {
					ints[ii] = 1
				}
				ii++
			case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
				ints[ii] = uintptr(args[i].Int())
				ii++
			case reflect.Pointer, reflect.UnsafePointer:
				ints[ii] = args[i].Pointer()
				ii++
			default:
				ints[ii] = uintptr(args[i].Uint())
				ii++
			}
		}
		r := fastCallIF(cfn, ints, numInts, floats, numFloats)
		if !hasReturn {
			return nil
		}
		out := reflect.New(ty.Out(0)).Elem()
		switch ty.Out(0).Kind() {
		case reflect.Uintptr, reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
			out.SetUint(uint64(r))
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
			out.SetInt(int64(r))
		case reflect.Bool:
			out.SetBool(byte(r) != 0)
		case reflect.UnsafePointer:
			out.SetPointer(*(*unsafe.Pointer)(unsafe.Pointer(&r)))
		case reflect.Pointer:
			out = reflect.NewAt(ty.Out(0), unsafe.Pointer(&r)).Elem()
		}
		if len(args) > 0 {
			args[0] = out
			return args[:1]
		}
		return []reflect.Value{out}
	})
	fn.Set(v)
}

`

func emitFloatNFallback(buf *bytes.Buffer, cfg fastPathConfig) {
	execTemplate(buf, "floatNFallback", tmplFloatNFallback, cfg)
}

func emitTryRegisterFastPath(buf *bytes.Buffer, cfg fastPathConfig) {
	// The dispatcher preamble is mostly static with a few config values.
	execTemplate(buf, "tryRegisterFastPathPreamble", tmplTryRegisterFastPathPreamble, cfg)

	// Emit pattern matching in config order.
	buf.WriteString("\t// Pattern matching in config order\n")
	for _, p := range cfg.Patterns {
		switch {
		case p.NumFloats == 0:
			buf.WriteString(`	if numFloats == 0 {
		registerFastFunc(fn, cfn, numInts, hasReturn)
		return true
	}

`)

		case p.Layout == "trailing" && p.NumFloats == 1 && p.FloatBits == 32:
			buf.WriteString(`	// Trailing float32x1
	if numFloats == 1 && trailingFloats && ty.In(numInts).Kind() == reflect.Float32 {
		registerFastFuncFloat32x1(fn, cfn, numInts, hasReturn)
		return true
	}

`)

		case p.Layout == "trailing" && p.NumFloats == 1 && p.FloatBits == 64:
			buf.WriteString(`	// Trailing float64x1
	if numFloats == 1 && trailingFloats && ty.In(numInts).Kind() == reflect.Float64 {
		registerFastFuncFloat64x1(fn, cfn, numInts, hasReturn)
		return true
	}

`)

		case p.Layout == "interleaved" && p.NumFloats == 1 && p.FloatBits == 32:
			buf.WriteString(`	// Interleaved float32x1
	if numFloats == 1 && !trailingFloats && ty.In(floatPos).Kind() == reflect.Float32 {
		registerFastFuncInterleavedFloat32x1(fn, cfn, numIn, floatPos, hasReturn)
		return true
	}

`)

		case p.Layout == "trailing" && p.NumFloats > 1:
			floatKind := "reflect.Float32"
			if p.FloatBits == 64 {
				floatKind = "reflect.Float64"
			}
			fmt.Fprintf(buf, `	// %s: %d trailing %d-bit floats
	if numFloats == %d && trailingFloats {
		allMatch := true
		for i := numInts; i < numIn; i++ {
			if ty.In(i).Kind() != %s {
				allMatch = false
				break
			}
		}
		if allMatch {
			registerFastFunc%s(fn, cfn, numInts, hasReturn)
			return true
		}
	}

`, p.Name, p.NumFloats, p.FloatBits, p.NumFloats, floatKind, p.Name)
		}
	}

	buf.WriteString(`	// Fallback: MakeFunc for unmatched float patterns
	registerFastFuncFloatN(fn, cfn, ty, numInts, numFloats, hasReturn)
	return true
}

`)
}

var tmplTryRegisterFastPathPreamble = `// tryRegisterFastPath attempts to install a zero-allocation fast-path closure
// for fn. Returns true if successful, false if the caller should use the slow path.
func tryRegisterFastPath(fn reflect.Value, cfn uintptr, ty reflect.Type) bool {
	numIn := ty.NumIn()
	if !((runtime.GOARCH == "amd64" || runtime.GOARCH == "arm64") && runtime.GOOS != "windows") {
		return false
	}
	if numIn > {{.MaxIntArgs}} {
		return false
	}

	canFastPath := true
	var numFloats int
	var numInts int
	var hasStructs bool
	var hasSmallStackArg bool
	trailingFloats := true
	var seenFloat bool
	floatPos := -1
	intRegCount := numOfIntegerRegisters()

	for i := 0; i < numIn; i++ {
		switch ty.In(i).Kind() {
		case reflect.Uintptr, reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
			reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Bool, reflect.Pointer, reflect.UnsafePointer:
			if seenFloat {
				trailingFloats = false
			}
			if numInts >= intRegCount && ty.In(i).Size() < unsafe.Sizeof(uintptr(0)) {
				hasSmallStackArg = true
			}
			numInts++
		case reflect.Float32, reflect.Float64:
			if !seenFloat {
				floatPos = i
			}
			seenFloat = true
			numFloats++
		case reflect.Struct:
			if isSmallRegStruct(ty.In(i)) {
				if seenFloat {
					trailingFloats = false
				}
				hasStructs = true
				numInts++
			} else {
				canFastPath = false
			}
		default:
			canFastPath = false
		}
	}
	if numFloats > {{.MaxFloatArgs}} {
		canFastPath = false
	}
	if numInts > {{.MaxIntArgs}} {
		canFastPath = false
	}
	if ty.NumOut() == 1 {
		switch ty.Out(0).Kind() {
		case reflect.Uintptr, reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
			reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Bool, reflect.Pointer, reflect.UnsafePointer:
		default:
			canFastPath = false
		}
	}
	if hasSmallStackArg {
		canFastPath = false
	}
	if !canFastPath {
		return false
	}

	hasReturn := ty.NumOut() > 0
	if hasStructs {
		registerFastFuncWithStructs(fn, cfn, ty, numInts, numFloats, hasReturn)
		return true
	}

`
