// Code generated by wincallback.go using 'go generate'. DO NOT EDIT.

//go:build linux

// External code calls into callbackasm at an offset corresponding
// to the callback index. Callbackasm is a table of MOVW and B instructions.
// The MOVW instruction loads R8 with the callback index, and the
// B instruction branches to callbackasm1.
// callbackasm1 takes the callback index from R8 and
// indexes into an array that stores information about each callback.
// It then calls the Go implementation for that callback.
#include "textflag.h"

TEXT callbackasm(SB),NOSPLIT|NOFRAME,$0
	MOVW	$0, R8
	B	callbackasm1(SB)
	MOVW	$1, R8
	B	callbackasm1(SB)
	MOVW	$2, R8
	B	callbackasm1(SB)
	MOVW	$3, R8
	B	callbackasm1(SB)
	MOVW	$4, R8
	B	callbackasm1(SB)
	MOVW	$5, R8
	B	callbackasm1(SB)
	MOVW	$6, R8
	B	callbackasm1(SB)
	MOVW	$7, R8
	B	callbackasm1(SB)
	MOVW	$8, R8
	B	callbackasm1(SB)
	MOVW	$9, R8
	B	callbackasm1(SB)
	MOVW	$10, R8
	B	callbackasm1(SB)
	MOVW	$11, R8
	B	callbackasm1(SB)
	MOVW	$12, R8
	B	callbackasm1(SB)
	MOVW	$13, R8
	B	callbackasm1(SB)
	MOVW	$14, R8
	B	callbackasm1(SB)
	MOVW	$15, R8
	B	callbackasm1(SB)
	MOVW	$16, R8
	B	callbackasm1(SB)
	MOVW	$17, R8
	B	callbackasm1(SB)
	MOVW	$18, R8
	B	callbackasm1(SB)
	MOVW	$19, R8
	B	callbackasm1(SB)
	MOVW	$20, R8
	B	callbackasm1(SB)
	MOVW	$21, R8
	B	callbackasm1(SB)
	MOVW	$22, R8
	B	callbackasm1(SB)
	MOVW	$23, R8
	B	callbackasm1(SB)
	MOVW	$24, R8
	B	callbackasm1(SB)
	MOVW	$25, R8
	B	callbackasm1(SB)
	MOVW	$26, R8
	B	callbackasm1(SB)
	MOVW	$27, R8
	B	callbackasm1(SB)
	MOVW	$28, R8
	B	callbackasm1(SB)
	MOVW	$29, R8
	B	callbackasm1(SB)
	MOVW	$30, R8
	B	callbackasm1(SB)
	MOVW	$31, R8
	B	callbackasm1(SB)
	MOVW	$32, R8
	B	callbackasm1(SB)
	MOVW	$33, R8
	B	callbackasm1(SB)
	MOVW	$34, R8
	B	callbackasm1(SB)
	MOVW	$35, R8
	B	callbackasm1(SB)
	MOVW	$36, R8
	B	callbackasm1(SB)
	MOVW	$37, R8
	B	callbackasm1(SB)
	MOVW	$38, R8
	B	callbackasm1(SB)
	MOVW	$39, R8
	B	callbackasm1(SB)
	MOVW	$40, R8
	B	callbackasm1(SB)
	MOVW	$41, R8
	B	callbackasm1(SB)
	MOVW	$42, R8
	B	callbackasm1(SB)
	MOVW	$43, R8
	B	callbackasm1(SB)
	MOVW	$44, R8
	B	callbackasm1(SB)
	MOVW	$45, R8
	B	callbackasm1(SB)
	MOVW	$46, R8
	B	callbackasm1(SB)
	MOVW	$47, R8
	B	callbackasm1(SB)
	MOVW	$48, R8
	B	callbackasm1(SB)
	MOVW	$49, R8
	B	callbackasm1(SB)
	MOVW	$50, R8
	B	callbackasm1(SB)
	MOVW	$51, R8
	B	callbackasm1(SB)
	MOVW	$52, R8
	B	callbackasm1(SB)
	MOVW	$53, R8
	B	callbackasm1(SB)
	MOVW	$54, R8
	B	callbackasm1(SB)
	MOVW	$55, R8
	B	callbackasm1(SB)
	MOVW	$56, R8
	B	callbackasm1(SB)
	MOVW	$57, R8
	B	callbackasm1(SB)
	MOVW	$58, R8
	B	callbackasm1(SB)
	MOVW	$59, R8
	B	callbackasm1(SB)
	MOVW	$60, R8
	B	callbackasm1(SB)
	MOVW	$61, R8
	B	callbackasm1(SB)
	MOVW	$62, R8
	B	callbackasm1(SB)
	MOVW	$63, R8
	B	callbackasm1(SB)
	MOVW	$64, R8
	B	callbackasm1(SB)
	MOVW	$65, R8
	B	callbackasm1(SB)
	MOVW	$66, R8
	B	callbackasm1(SB)
	MOVW	$67, R8
	B	callbackasm1(SB)
	MOVW	$68, R8
	B	callbackasm1(SB)
	MOVW	$69, R8
	B	callbackasm1(SB)
	MOVW	$70, R8
	B	callbackasm1(SB)
	MOVW	$71, R8
	B	callbackasm1(SB)
	MOVW	$72, R8
	B	callbackasm1(SB)
	MOVW	$73, R8
	B	callbackasm1(SB)
	MOVW	$74, R8
	B	callbackasm1(SB)
	MOVW	$75, R8
	B	callbackasm1(SB)
	MOVW	$76, R8
	B	callbackasm1(SB)
	MOVW	$77, R8
	B	callbackasm1(SB)
	MOVW	$78, R8
	B	callbackasm1(SB)
	MOVW	$79, R8
	B	callbackasm1(SB)
	MOVW	$80, R8
	B	callbackasm1(SB)
	MOVW	$81, R8
	B	callbackasm1(SB)
	MOVW	$82, R8
	B	callbackasm1(SB)
	MOVW	$83, R8
	B	callbackasm1(SB)
	MOVW	$84, R8
	B	callbackasm1(SB)
	MOVW	$85, R8
	B	callbackasm1(SB)
	MOVW	$86, R8
	B	callbackasm1(SB)
	MOVW	$87, R8
	B	callbackasm1(SB)
	MOVW	$88, R8
	B	callbackasm1(SB)
	MOVW	$89, R8
	B	callbackasm1(SB)
	MOVW	$90, R8
	B	callbackasm1(SB)
	MOVW	$91, R8
	B	callbackasm1(SB)
	MOVW	$92, R8
	B	callbackasm1(SB)
	MOVW	$93, R8
	B	callbackasm1(SB)
	MOVW	$94, R8
	B	callbackasm1(SB)
	MOVW	$95, R8
	B	callbackasm1(SB)
	MOVW	$96, R8
	B	callbackasm1(SB)
	MOVW	$97, R8
	B	callbackasm1(SB)
	MOVW	$98, R8
	B	callbackasm1(SB)
	MOVW	$99, R8
	B	callbackasm1(SB)
	MOVW	$100, R8
	B	callbackasm1(SB)
	MOVW	$101, R8
	B	callbackasm1(SB)
	MOVW	$102, R8
	B	callbackasm1(SB)
	MOVW	$103, R8
	B	callbackasm1(SB)
	MOVW	$104, R8
	B	callbackasm1(SB)
	MOVW	$105, R8
	B	callbackasm1(SB)
	MOVW	$106, R8
	B	callbackasm1(SB)
	MOVW	$107, R8
	B	callbackasm1(SB)
	MOVW	$108, R8
	B	callbackasm1(SB)
	MOVW	$109, R8
	B	callbackasm1(SB)
	MOVW	$110, R8
	B	callbackasm1(SB)
	MOVW	$111, R8
	B	callbackasm1(SB)
	MOVW	$112, R8
	B	callbackasm1(SB)
	MOVW	$113, R8
	B	callbackasm1(SB)
	MOVW	$114, R8
	B	callbackasm1(SB)
	MOVW	$115, R8
	B	callbackasm1(SB)
	MOVW	$116, R8
	B	callbackasm1(SB)
	MOVW	$117, R8
	B	callbackasm1(SB)
	MOVW	$118, R8
	B	callbackasm1(SB)
	MOVW	$119, R8
	B	callbackasm1(SB)
	MOVW	$120, R8
	B	callbackasm1(SB)
	MOVW	$121, R8
	B	callbackasm1(SB)
	MOVW	$122, R8
	B	callbackasm1(SB)
	MOVW	$123, R8
	B	callbackasm1(SB)
	MOVW	$124, R8
	B	callbackasm1(SB)
	MOVW	$125, R8
	B	callbackasm1(SB)
	MOVW	$126, R8
	B	callbackasm1(SB)
	MOVW	$127, R8
	B	callbackasm1(SB)
	MOVW	$128, R8
	B	callbackasm1(SB)
	MOVW	$129, R8
	B	callbackasm1(SB)
	MOVW	$130, R8
	B	callbackasm1(SB)
	MOVW	$131, R8
	B	callbackasm1(SB)
	MOVW	$132, R8
	B	callbackasm1(SB)
	MOVW	$133, R8
	B	callbackasm1(SB)
	MOVW	$134, R8
	B	callbackasm1(SB)
	MOVW	$135, R8
	B	callbackasm1(SB)
	MOVW	$136, R8
	B	callbackasm1(SB)
	MOVW	$137, R8
	B	callbackasm1(SB)
	MOVW	$138, R8
	B	callbackasm1(SB)
	MOVW	$139, R8
	B	callbackasm1(SB)
	MOVW	$140, R8
	B	callbackasm1(SB)
	MOVW	$141, R8
	B	callbackasm1(SB)
	MOVW	$142, R8
	B	callbackasm1(SB)
	MOVW	$143, R8
	B	callbackasm1(SB)
	MOVW	$144, R8
	B	callbackasm1(SB)
	MOVW	$145, R8
	B	callbackasm1(SB)
	MOVW	$146, R8
	B	callbackasm1(SB)
	MOVW	$147, R8
	B	callbackasm1(SB)
	MOVW	$148, R8
	B	callbackasm1(SB)
	MOVW	$149, R8
	B	callbackasm1(SB)
	MOVW	$150, R8
	B	callbackasm1(SB)
	MOVW	$151, R8
	B	callbackasm1(SB)
	MOVW	$152, R8
	B	callbackasm1(SB)
	MOVW	$153, R8
	B	callbackasm1(SB)
	MOVW	$154, R8
	B	callbackasm1(SB)
	MOVW	$155, R8
	B	callbackasm1(SB)
	MOVW	$156, R8
	B	callbackasm1(SB)
	MOVW	$157, R8
	B	callbackasm1(SB)
	MOVW	$158, R8
	B	callbackasm1(SB)
	MOVW	$159, R8
	B	callbackasm1(SB)
	MOVW	$160, R8
	B	callbackasm1(SB)
	MOVW	$161, R8
	B	callbackasm1(SB)
	MOVW	$162, R8
	B	callbackasm1(SB)
	MOVW	$163, R8
	B	callbackasm1(SB)
	MOVW	$164, R8
	B	callbackasm1(SB)
	MOVW	$165, R8
	B	callbackasm1(SB)
	MOVW	$166, R8
	B	callbackasm1(SB)
	MOVW	$167, R8
	B	callbackasm1(SB)
	MOVW	$168, R8
	B	callbackasm1(SB)
	MOVW	$169, R8
	B	callbackasm1(SB)
	MOVW	$170, R8
	B	callbackasm1(SB)
	MOVW	$171, R8
	B	callbackasm1(SB)
	MOVW	$172, R8
	B	callbackasm1(SB)
	MOVW	$173, R8
	B	callbackasm1(SB)
	MOVW	$174, R8
	B	callbackasm1(SB)
	MOVW	$175, R8
	B	callbackasm1(SB)
	MOVW	$176, R8
	B	callbackasm1(SB)
	MOVW	$177, R8
	B	callbackasm1(SB)
	MOVW	$178, R8
	B	callbackasm1(SB)
	MOVW	$179, R8
	B	callbackasm1(SB)
	MOVW	$180, R8
	B	callbackasm1(SB)
	MOVW	$181, R8
	B	callbackasm1(SB)
	MOVW	$182, R8
	B	callbackasm1(SB)
	MOVW	$183, R8
	B	callbackasm1(SB)
	MOVW	$184, R8
	B	callbackasm1(SB)
	MOVW	$185, R8
	B	callbackasm1(SB)
	MOVW	$186, R8
	B	callbackasm1(SB)
	MOVW	$187, R8
	B	callbackasm1(SB)
	MOVW	$188, R8
	B	callbackasm1(SB)
	MOVW	$189, R8
	B	callbackasm1(SB)
	MOVW	$190, R8
	B	callbackasm1(SB)
	MOVW	$191, R8
	B	callbackasm1(SB)
	MOVW	$192, R8
	B	callbackasm1(SB)
	MOVW	$193, R8
	B	callbackasm1(SB)
	MOVW	$194, R8
	B	callbackasm1(SB)
	MOVW	$195, R8
	B	callbackasm1(SB)
	MOVW	$196, R8
	B	callbackasm1(SB)
	MOVW	$197, R8
	B	callbackasm1(SB)
	MOVW	$198, R8
	B	callbackasm1(SB)
	MOVW	$199, R8
	B	callbackasm1(SB)
	MOVW	$200, R8
	B	callbackasm1(SB)
	MOVW	$201, R8
	B	callbackasm1(SB)
	MOVW	$202, R8
	B	callbackasm1(SB)
	MOVW	$203, R8
	B	callbackasm1(SB)
	MOVW	$204, R8
	B	callbackasm1(SB)
	MOVW	$205, R8
	B	callbackasm1(SB)
	MOVW	$206, R8
	B	callbackasm1(SB)
	MOVW	$207, R8
	B	callbackasm1(SB)
	MOVW	$208, R8
	B	callbackasm1(SB)
	MOVW	$209, R8
	B	callbackasm1(SB)
	MOVW	$210, R8
	B	callbackasm1(SB)
	MOVW	$211, R8
	B	callbackasm1(SB)
	MOVW	$212, R8
	B	callbackasm1(SB)
	MOVW	$213, R8
	B	callbackasm1(SB)
	MOVW	$214, R8
	B	callbackasm1(SB)
	MOVW	$215, R8
	B	callbackasm1(SB)
	MOVW	$216, R8
	B	callbackasm1(SB)
	MOVW	$217, R8
	B	callbackasm1(SB)
	MOVW	$218, R8
	B	callbackasm1(SB)
	MOVW	$219, R8
	B	callbackasm1(SB)
	MOVW	$220, R8
	B	callbackasm1(SB)
	MOVW	$221, R8
	B	callbackasm1(SB)
	MOVW	$222, R8
	B	callbackasm1(SB)
	MOVW	$223, R8
	B	callbackasm1(SB)
	MOVW	$224, R8
	B	callbackasm1(SB)
	MOVW	$225, R8
	B	callbackasm1(SB)
	MOVW	$226, R8
	B	callbackasm1(SB)
	MOVW	$227, R8
	B	callbackasm1(SB)
	MOVW	$228, R8
	B	callbackasm1(SB)
	MOVW	$229, R8
	B	callbackasm1(SB)
	MOVW	$230, R8
	B	callbackasm1(SB)
	MOVW	$231, R8
	B	callbackasm1(SB)
	MOVW	$232, R8
	B	callbackasm1(SB)
	MOVW	$233, R8
	B	callbackasm1(SB)
	MOVW	$234, R8
	B	callbackasm1(SB)
	MOVW	$235, R8
	B	callbackasm1(SB)
	MOVW	$236, R8
	B	callbackasm1(SB)
	MOVW	$237, R8
	B	callbackasm1(SB)
	MOVW	$238, R8
	B	callbackasm1(SB)
	MOVW	$239, R8
	B	callbackasm1(SB)
	MOVW	$240, R8
	B	callbackasm1(SB)
	MOVW	$241, R8
	B	callbackasm1(SB)
	MOVW	$242, R8
	B	callbackasm1(SB)
	MOVW	$243, R8
	B	callbackasm1(SB)
	MOVW	$244, R8
	B	callbackasm1(SB)
	MOVW	$245, R8
	B	callbackasm1(SB)
	MOVW	$246, R8
	B	callbackasm1(SB)
	MOVW	$247, R8
	B	callbackasm1(SB)
	MOVW	$248, R8
	B	callbackasm1(SB)
	MOVW	$249, R8
	B	callbackasm1(SB)
	MOVW	$250, R8
	B	callbackasm1(SB)
	MOVW	$251, R8
	B	callbackasm1(SB)
	MOVW	$252, R8
	B	callbackasm1(SB)
	MOVW	$253, R8
	B	callbackasm1(SB)
	MOVW	$254, R8
	B	callbackasm1(SB)
	MOVW	$255, R8
	B	callbackasm1(SB)
	MOVW	$256, R8
	B	callbackasm1(SB)
	MOVW	$257, R8
	B	callbackasm1(SB)
	MOVW	$258, R8
	B	callbackasm1(SB)
	MOVW	$259, R8
	B	callbackasm1(SB)
	MOVW	$260, R8
	B	callbackasm1(SB)
	MOVW	$261, R8
	B	callbackasm1(SB)
	MOVW	$262, R8
	B	callbackasm1(SB)
	MOVW	$263, R8
	B	callbackasm1(SB)
	MOVW	$264, R8
	B	callbackasm1(SB)
	MOVW	$265, R8
	B	callbackasm1(SB)
	MOVW	$266, R8
	B	callbackasm1(SB)
	MOVW	$267, R8
	B	callbackasm1(SB)
	MOVW	$268, R8
	B	callbackasm1(SB)
	MOVW	$269, R8
	B	callbackasm1(SB)
	MOVW	$270, R8
	B	callbackasm1(SB)
	MOVW	$271, R8
	B	callbackasm1(SB)
	MOVW	$272, R8
	B	callbackasm1(SB)
	MOVW	$273, R8
	B	callbackasm1(SB)
	MOVW	$274, R8
	B	callbackasm1(SB)
	MOVW	$275, R8
	B	callbackasm1(SB)
	MOVW	$276, R8
	B	callbackasm1(SB)
	MOVW	$277, R8
	B	callbackasm1(SB)
	MOVW	$278, R8
	B	callbackasm1(SB)
	MOVW	$279, R8
	B	callbackasm1(SB)
	MOVW	$280, R8
	B	callbackasm1(SB)
	MOVW	$281, R8
	B	callbackasm1(SB)
	MOVW	$282, R8
	B	callbackasm1(SB)
	MOVW	$283, R8
	B	callbackasm1(SB)
	MOVW	$284, R8
	B	callbackasm1(SB)
	MOVW	$285, R8
	B	callbackasm1(SB)
	MOVW	$286, R8
	B	callbackasm1(SB)
	MOVW	$287, R8
	B	callbackasm1(SB)
	MOVW	$288, R8
	B	callbackasm1(SB)
	MOVW	$289, R8
	B	callbackasm1(SB)
	MOVW	$290, R8
	B	callbackasm1(SB)
	MOVW	$291, R8
	B	callbackasm1(SB)
	MOVW	$292, R8
	B	callbackasm1(SB)
	MOVW	$293, R8
	B	callbackasm1(SB)
	MOVW	$294, R8
	B	callbackasm1(SB)
	MOVW	$295, R8
	B	callbackasm1(SB)
	MOVW	$296, R8
	B	callbackasm1(SB)
	MOVW	$297, R8
	B	callbackasm1(SB)
	MOVW	$298, R8
	B	callbackasm1(SB)
	MOVW	$299, R8
	B	callbackasm1(SB)
	MOVW	$300, R8
	B	callbackasm1(SB)
	MOVW	$301, R8
	B	callbackasm1(SB)
	MOVW	$302, R8
	B	callbackasm1(SB)
	MOVW	$303, R8
	B	callbackasm1(SB)
	MOVW	$304, R8
	B	callbackasm1(SB)
	MOVW	$305, R8
	B	callbackasm1(SB)
	MOVW	$306, R8
	B	callbackasm1(SB)
	MOVW	$307, R8
	B	callbackasm1(SB)
	MOVW	$308, R8
	B	callbackasm1(SB)
	MOVW	$309, R8
	B	callbackasm1(SB)
	MOVW	$310, R8
	B	callbackasm1(SB)
	MOVW	$311, R8
	B	callbackasm1(SB)
	MOVW	$312, R8
	B	callbackasm1(SB)
	MOVW	$313, R8
	B	callbackasm1(SB)
	MOVW	$314, R8
	B	callbackasm1(SB)
	MOVW	$315, R8
	B	callbackasm1(SB)
	MOVW	$316, R8
	B	callbackasm1(SB)
	MOVW	$317, R8
	B	callbackasm1(SB)
	MOVW	$318, R8
	B	callbackasm1(SB)
	MOVW	$319, R8
	B	callbackasm1(SB)
	MOVW	$320, R8
	B	callbackasm1(SB)
	MOVW	$321, R8
	B	callbackasm1(SB)
	MOVW	$322, R8
	B	callbackasm1(SB)
	MOVW	$323, R8
	B	callbackasm1(SB)
	MOVW	$324, R8
	B	callbackasm1(SB)
	MOVW	$325, R8
	B	callbackasm1(SB)
	MOVW	$326, R8
	B	callbackasm1(SB)
	MOVW	$327, R8
	B	callbackasm1(SB)
	MOVW	$328, R8
	B	callbackasm1(SB)
	MOVW	$329, R8
	B	callbackasm1(SB)
	MOVW	$330, R8
	B	callbackasm1(SB)
	MOVW	$331, R8
	B	callbackasm1(SB)
	MOVW	$332, R8
	B	callbackasm1(SB)
	MOVW	$333, R8
	B	callbackasm1(SB)
	MOVW	$334, R8
	B	callbackasm1(SB)
	MOVW	$335, R8
	B	callbackasm1(SB)
	MOVW	$336, R8
	B	callbackasm1(SB)
	MOVW	$337, R8
	B	callbackasm1(SB)
	MOVW	$338, R8
	B	callbackasm1(SB)
	MOVW	$339, R8
	B	callbackasm1(SB)
	MOVW	$340, R8
	B	callbackasm1(SB)
	MOVW	$341, R8
	B	callbackasm1(SB)
	MOVW	$342, R8
	B	callbackasm1(SB)
	MOVW	$343, R8
	B	callbackasm1(SB)
	MOVW	$344, R8
	B	callbackasm1(SB)
	MOVW	$345, R8
	B	callbackasm1(SB)
	MOVW	$346, R8
	B	callbackasm1(SB)
	MOVW	$347, R8
	B	callbackasm1(SB)
	MOVW	$348, R8
	B	callbackasm1(SB)
	MOVW	$349, R8
	B	callbackasm1(SB)
	MOVW	$350, R8
	B	callbackasm1(SB)
	MOVW	$351, R8
	B	callbackasm1(SB)
	MOVW	$352, R8
	B	callbackasm1(SB)
	MOVW	$353, R8
	B	callbackasm1(SB)
	MOVW	$354, R8
	B	callbackasm1(SB)
	MOVW	$355, R8
	B	callbackasm1(SB)
	MOVW	$356, R8
	B	callbackasm1(SB)
	MOVW	$357, R8
	B	callbackasm1(SB)
	MOVW	$358, R8
	B	callbackasm1(SB)
	MOVW	$359, R8
	B	callbackasm1(SB)
	MOVW	$360, R8
	B	callbackasm1(SB)
	MOVW	$361, R8
	B	callbackasm1(SB)
	MOVW	$362, R8
	B	callbackasm1(SB)
	MOVW	$363, R8
	B	callbackasm1(SB)
	MOVW	$364, R8
	B	callbackasm1(SB)
	MOVW	$365, R8
	B	callbackasm1(SB)
	MOVW	$366, R8
	B	callbackasm1(SB)
	MOVW	$367, R8
	B	callbackasm1(SB)
	MOVW	$368, R8
	B	callbackasm1(SB)
	MOVW	$369, R8
	B	callbackasm1(SB)
	MOVW	$370, R8
	B	callbackasm1(SB)
	MOVW	$371, R8
	B	callbackasm1(SB)
	MOVW	$372, R8
	B	callbackasm1(SB)
	MOVW	$373, R8
	B	callbackasm1(SB)
	MOVW	$374, R8
	B	callbackasm1(SB)
	MOVW	$375, R8
	B	callbackasm1(SB)
	MOVW	$376, R8
	B	callbackasm1(SB)
	MOVW	$377, R8
	B	callbackasm1(SB)
	MOVW	$378, R8
	B	callbackasm1(SB)
	MOVW	$379, R8
	B	callbackasm1(SB)
	MOVW	$380, R8
	B	callbackasm1(SB)
	MOVW	$381, R8
	B	callbackasm1(SB)
	MOVW	$382, R8
	B	callbackasm1(SB)
	MOVW	$383, R8
	B	callbackasm1(SB)
	MOVW	$384, R8
	B	callbackasm1(SB)
	MOVW	$385, R8
	B	callbackasm1(SB)
	MOVW	$386, R8
	B	callbackasm1(SB)
	MOVW	$387, R8
	B	callbackasm1(SB)
	MOVW	$388, R8
	B	callbackasm1(SB)
	MOVW	$389, R8
	B	callbackasm1(SB)
	MOVW	$390, R8
	B	callbackasm1(SB)
	MOVW	$391, R8
	B	callbackasm1(SB)
	MOVW	$392, R8
	B	callbackasm1(SB)
	MOVW	$393, R8
	B	callbackasm1(SB)
	MOVW	$394, R8
	B	callbackasm1(SB)
	MOVW	$395, R8
	B	callbackasm1(SB)
	MOVW	$396, R8
	B	callbackasm1(SB)
	MOVW	$397, R8
	B	callbackasm1(SB)
	MOVW	$398, R8
	B	callbackasm1(SB)
	MOVW	$399, R8
	B	callbackasm1(SB)
	MOVW	$400, R8
	B	callbackasm1(SB)
	MOVW	$401, R8
	B	callbackasm1(SB)
	MOVW	$402, R8
	B	callbackasm1(SB)
	MOVW	$403, R8
	B	callbackasm1(SB)
	MOVW	$404, R8
	B	callbackasm1(SB)
	MOVW	$405, R8
	B	callbackasm1(SB)
	MOVW	$406, R8
	B	callbackasm1(SB)
	MOVW	$407, R8
	B	callbackasm1(SB)
	MOVW	$408, R8
	B	callbackasm1(SB)
	MOVW	$409, R8
	B	callbackasm1(SB)
	MOVW	$410, R8
	B	callbackasm1(SB)
	MOVW	$411, R8
	B	callbackasm1(SB)
	MOVW	$412, R8
	B	callbackasm1(SB)
	MOVW	$413, R8
	B	callbackasm1(SB)
	MOVW	$414, R8
	B	callbackasm1(SB)
	MOVW	$415, R8
	B	callbackasm1(SB)
	MOVW	$416, R8
	B	callbackasm1(SB)
	MOVW	$417, R8
	B	callbackasm1(SB)
	MOVW	$418, R8
	B	callbackasm1(SB)
	MOVW	$419, R8
	B	callbackasm1(SB)
	MOVW	$420, R8
	B	callbackasm1(SB)
	MOVW	$421, R8
	B	callbackasm1(SB)
	MOVW	$422, R8
	B	callbackasm1(SB)
	MOVW	$423, R8
	B	callbackasm1(SB)
	MOVW	$424, R8
	B	callbackasm1(SB)
	MOVW	$425, R8
	B	callbackasm1(SB)
	MOVW	$426, R8
	B	callbackasm1(SB)
	MOVW	$427, R8
	B	callbackasm1(SB)
	MOVW	$428, R8
	B	callbackasm1(SB)
	MOVW	$429, R8
	B	callbackasm1(SB)
	MOVW	$430, R8
	B	callbackasm1(SB)
	MOVW	$431, R8
	B	callbackasm1(SB)
	MOVW	$432, R8
	B	callbackasm1(SB)
	MOVW	$433, R8
	B	callbackasm1(SB)
	MOVW	$434, R8
	B	callbackasm1(SB)
	MOVW	$435, R8
	B	callbackasm1(SB)
	MOVW	$436, R8
	B	callbackasm1(SB)
	MOVW	$437, R8
	B	callbackasm1(SB)
	MOVW	$438, R8
	B	callbackasm1(SB)
	MOVW	$439, R8
	B	callbackasm1(SB)
	MOVW	$440, R8
	B	callbackasm1(SB)
	MOVW	$441, R8
	B	callbackasm1(SB)
	MOVW	$442, R8
	B	callbackasm1(SB)
	MOVW	$443, R8
	B	callbackasm1(SB)
	MOVW	$444, R8
	B	callbackasm1(SB)
	MOVW	$445, R8
	B	callbackasm1(SB)
	MOVW	$446, R8
	B	callbackasm1(SB)
	MOVW	$447, R8
	B	callbackasm1(SB)
	MOVW	$448, R8
	B	callbackasm1(SB)
	MOVW	$449, R8
	B	callbackasm1(SB)
	MOVW	$450, R8
	B	callbackasm1(SB)
	MOVW	$451, R8
	B	callbackasm1(SB)
	MOVW	$452, R8
	B	callbackasm1(SB)
	MOVW	$453, R8
	B	callbackasm1(SB)
	MOVW	$454, R8
	B	callbackasm1(SB)
	MOVW	$455, R8
	B	callbackasm1(SB)
	MOVW	$456, R8
	B	callbackasm1(SB)
	MOVW	$457, R8
	B	callbackasm1(SB)
	MOVW	$458, R8
	B	callbackasm1(SB)
	MOVW	$459, R8
	B	callbackasm1(SB)
	MOVW	$460, R8
	B	callbackasm1(SB)
	MOVW	$461, R8
	B	callbackasm1(SB)
	MOVW	$462, R8
	B	callbackasm1(SB)
	MOVW	$463, R8
	B	callbackasm1(SB)
	MOVW	$464, R8
	B	callbackasm1(SB)
	MOVW	$465, R8
	B	callbackasm1(SB)
	MOVW	$466, R8
	B	callbackasm1(SB)
	MOVW	$467, R8
	B	callbackasm1(SB)
	MOVW	$468, R8
	B	callbackasm1(SB)
	MOVW	$469, R8
	B	callbackasm1(SB)
	MOVW	$470, R8
	B	callbackasm1(SB)
	MOVW	$471, R8
	B	callbackasm1(SB)
	MOVW	$472, R8
	B	callbackasm1(SB)
	MOVW	$473, R8
	B	callbackasm1(SB)
	MOVW	$474, R8
	B	callbackasm1(SB)
	MOVW	$475, R8
	B	callbackasm1(SB)
	MOVW	$476, R8
	B	callbackasm1(SB)
	MOVW	$477, R8
	B	callbackasm1(SB)
	MOVW	$478, R8
	B	callbackasm1(SB)
	MOVW	$479, R8
	B	callbackasm1(SB)
	MOVW	$480, R8
	B	callbackasm1(SB)
	MOVW	$481, R8
	B	callbackasm1(SB)
	MOVW	$482, R8
	B	callbackasm1(SB)
	MOVW	$483, R8
	B	callbackasm1(SB)
	MOVW	$484, R8
	B	callbackasm1(SB)
	MOVW	$485, R8
	B	callbackasm1(SB)
	MOVW	$486, R8
	B	callbackasm1(SB)
	MOVW	$487, R8
	B	callbackasm1(SB)
	MOVW	$488, R8
	B	callbackasm1(SB)
	MOVW	$489, R8
	B	callbackasm1(SB)
	MOVW	$490, R8
	B	callbackasm1(SB)
	MOVW	$491, R8
	B	callbackasm1(SB)
	MOVW	$492, R8
	B	callbackasm1(SB)
	MOVW	$493, R8
	B	callbackasm1(SB)
	MOVW	$494, R8
	B	callbackasm1(SB)
	MOVW	$495, R8
	B	callbackasm1(SB)
	MOVW	$496, R8
	B	callbackasm1(SB)
	MOVW	$497, R8
	B	callbackasm1(SB)
	MOVW	$498, R8
	B	callbackasm1(SB)
	MOVW	$499, R8
	B	callbackasm1(SB)
	MOVW	$500, R8
	B	callbackasm1(SB)
	MOVW	$501, R8
	B	callbackasm1(SB)
	MOVW	$502, R8
	B	callbackasm1(SB)
	MOVW	$503, R8
	B	callbackasm1(SB)
	MOVW	$504, R8
	B	callbackasm1(SB)
	MOVW	$505, R8
	B	callbackasm1(SB)
	MOVW	$506, R8
	B	callbackasm1(SB)
	MOVW	$507, R8
	B	callbackasm1(SB)
	MOVW	$508, R8
	B	callbackasm1(SB)
	MOVW	$509, R8
	B	callbackasm1(SB)
	MOVW	$510, R8
	B	callbackasm1(SB)
	MOVW	$511, R8
	B	callbackasm1(SB)
	MOVW	$512, R8
	B	callbackasm1(SB)
	MOVW	$513, R8
	B	callbackasm1(SB)
	MOVW	$514, R8
	B	callbackasm1(SB)
	MOVW	$515, R8
	B	callbackasm1(SB)
	MOVW	$516, R8
	B	callbackasm1(SB)
	MOVW	$517, R8
	B	callbackasm1(SB)
	MOVW	$518, R8
	B	callbackasm1(SB)
	MOVW	$519, R8
	B	callbackasm1(SB)
	MOVW	$520, R8
	B	callbackasm1(SB)
	MOVW	$521, R8
	B	callbackasm1(SB)
	MOVW	$522, R8
	B	callbackasm1(SB)
	MOVW	$523, R8
	B	callbackasm1(SB)
	MOVW	$524, R8
	B	callbackasm1(SB)
	MOVW	$525, R8
	B	callbackasm1(SB)
	MOVW	$526, R8
	B	callbackasm1(SB)
	MOVW	$527, R8
	B	callbackasm1(SB)
	MOVW	$528, R8
	B	callbackasm1(SB)
	MOVW	$529, R8
	B	callbackasm1(SB)
	MOVW	$530, R8
	B	callbackasm1(SB)
	MOVW	$531, R8
	B	callbackasm1(SB)
	MOVW	$532, R8
	B	callbackasm1(SB)
	MOVW	$533, R8
	B	callbackasm1(SB)
	MOVW	$534, R8
	B	callbackasm1(SB)
	MOVW	$535, R8
	B	callbackasm1(SB)
	MOVW	$536, R8
	B	callbackasm1(SB)
	MOVW	$537, R8
	B	callbackasm1(SB)
	MOVW	$538, R8
	B	callbackasm1(SB)
	MOVW	$539, R8
	B	callbackasm1(SB)
	MOVW	$540, R8
	B	callbackasm1(SB)
	MOVW	$541, R8
	B	callbackasm1(SB)
	MOVW	$542, R8
	B	callbackasm1(SB)
	MOVW	$543, R8
	B	callbackasm1(SB)
	MOVW	$544, R8
	B	callbackasm1(SB)
	MOVW	$545, R8
	B	callbackasm1(SB)
	MOVW	$546, R8
	B	callbackasm1(SB)
	MOVW	$547, R8
	B	callbackasm1(SB)
	MOVW	$548, R8
	B	callbackasm1(SB)
	MOVW	$549, R8
	B	callbackasm1(SB)
	MOVW	$550, R8
	B	callbackasm1(SB)
	MOVW	$551, R8
	B	callbackasm1(SB)
	MOVW	$552, R8
	B	callbackasm1(SB)
	MOVW	$553, R8
	B	callbackasm1(SB)
	MOVW	$554, R8
	B	callbackasm1(SB)
	MOVW	$555, R8
	B	callbackasm1(SB)
	MOVW	$556, R8
	B	callbackasm1(SB)
	MOVW	$557, R8
	B	callbackasm1(SB)
	MOVW	$558, R8
	B	callbackasm1(SB)
	MOVW	$559, R8
	B	callbackasm1(SB)
	MOVW	$560, R8
	B	callbackasm1(SB)
	MOVW	$561, R8
	B	callbackasm1(SB)
	MOVW	$562, R8
	B	callbackasm1(SB)
	MOVW	$563, R8
	B	callbackasm1(SB)
	MOVW	$564, R8
	B	callbackasm1(SB)
	MOVW	$565, R8
	B	callbackasm1(SB)
	MOVW	$566, R8
	B	callbackasm1(SB)
	MOVW	$567, R8
	B	callbackasm1(SB)
	MOVW	$568, R8
	B	callbackasm1(SB)
	MOVW	$569, R8
	B	callbackasm1(SB)
	MOVW	$570, R8
	B	callbackasm1(SB)
	MOVW	$571, R8
	B	callbackasm1(SB)
	MOVW	$572, R8
	B	callbackasm1(SB)
	MOVW	$573, R8
	B	callbackasm1(SB)
	MOVW	$574, R8
	B	callbackasm1(SB)
	MOVW	$575, R8
	B	callbackasm1(SB)
	MOVW	$576, R8
	B	callbackasm1(SB)
	MOVW	$577, R8
	B	callbackasm1(SB)
	MOVW	$578, R8
	B	callbackasm1(SB)
	MOVW	$579, R8
	B	callbackasm1(SB)
	MOVW	$580, R8
	B	callbackasm1(SB)
	MOVW	$581, R8
	B	callbackasm1(SB)
	MOVW	$582, R8
	B	callbackasm1(SB)
	MOVW	$583, R8
	B	callbackasm1(SB)
	MOVW	$584, R8
	B	callbackasm1(SB)
	MOVW	$585, R8
	B	callbackasm1(SB)
	MOVW	$586, R8
	B	callbackasm1(SB)
	MOVW	$587, R8
	B	callbackasm1(SB)
	MOVW	$588, R8
	B	callbackasm1(SB)
	MOVW	$589, R8
	B	callbackasm1(SB)
	MOVW	$590, R8
	B	callbackasm1(SB)
	MOVW	$591, R8
	B	callbackasm1(SB)
	MOVW	$592, R8
	B	callbackasm1(SB)
	MOVW	$593, R8
	B	callbackasm1(SB)
	MOVW	$594, R8
	B	callbackasm1(SB)
	MOVW	$595, R8
	B	callbackasm1(SB)
	MOVW	$596, R8
	B	callbackasm1(SB)
	MOVW	$597, R8
	B	callbackasm1(SB)
	MOVW	$598, R8
	B	callbackasm1(SB)
	MOVW	$599, R8
	B	callbackasm1(SB)
	MOVW	$600, R8
	B	callbackasm1(SB)
	MOVW	$601, R8
	B	callbackasm1(SB)
	MOVW	$602, R8
	B	callbackasm1(SB)
	MOVW	$603, R8
	B	callbackasm1(SB)
	MOVW	$604, R8
	B	callbackasm1(SB)
	MOVW	$605, R8
	B	callbackasm1(SB)
	MOVW	$606, R8
	B	callbackasm1(SB)
	MOVW	$607, R8
	B	callbackasm1(SB)
	MOVW	$608, R8
	B	callbackasm1(SB)
	MOVW	$609, R8
	B	callbackasm1(SB)
	MOVW	$610, R8
	B	callbackasm1(SB)
	MOVW	$611, R8
	B	callbackasm1(SB)
	MOVW	$612, R8
	B	callbackasm1(SB)
	MOVW	$613, R8
	B	callbackasm1(SB)
	MOVW	$614, R8
	B	callbackasm1(SB)
	MOVW	$615, R8
	B	callbackasm1(SB)
	MOVW	$616, R8
	B	callbackasm1(SB)
	MOVW	$617, R8
	B	callbackasm1(SB)
	MOVW	$618, R8
	B	callbackasm1(SB)
	MOVW	$619, R8
	B	callbackasm1(SB)
	MOVW	$620, R8
	B	callbackasm1(SB)
	MOVW	$621, R8
	B	callbackasm1(SB)
	MOVW	$622, R8
	B	callbackasm1(SB)
	MOVW	$623, R8
	B	callbackasm1(SB)
	MOVW	$624, R8
	B	callbackasm1(SB)
	MOVW	$625, R8
	B	callbackasm1(SB)
	MOVW	$626, R8
	B	callbackasm1(SB)
	MOVW	$627, R8
	B	callbackasm1(SB)
	MOVW	$628, R8
	B	callbackasm1(SB)
	MOVW	$629, R8
	B	callbackasm1(SB)
	MOVW	$630, R8
	B	callbackasm1(SB)
	MOVW	$631, R8
	B	callbackasm1(SB)
	MOVW	$632, R8
	B	callbackasm1(SB)
	MOVW	$633, R8
	B	callbackasm1(SB)
	MOVW	$634, R8
	B	callbackasm1(SB)
	MOVW	$635, R8
	B	callbackasm1(SB)
	MOVW	$636, R8
	B	callbackasm1(SB)
	MOVW	$637, R8
	B	callbackasm1(SB)
	MOVW	$638, R8
	B	callbackasm1(SB)
	MOVW	$639, R8
	B	callbackasm1(SB)
	MOVW	$640, R8
	B	callbackasm1(SB)
	MOVW	$641, R8
	B	callbackasm1(SB)
	MOVW	$642, R8
	B	callbackasm1(SB)
	MOVW	$643, R8
	B	callbackasm1(SB)
	MOVW	$644, R8
	B	callbackasm1(SB)
	MOVW	$645, R8
	B	callbackasm1(SB)
	MOVW	$646, R8
	B	callbackasm1(SB)
	MOVW	$647, R8
	B	callbackasm1(SB)
	MOVW	$648, R8
	B	callbackasm1(SB)
	MOVW	$649, R8
	B	callbackasm1(SB)
	MOVW	$650, R8
	B	callbackasm1(SB)
	MOVW	$651, R8
	B	callbackasm1(SB)
	MOVW	$652, R8
	B	callbackasm1(SB)
	MOVW	$653, R8
	B	callbackasm1(SB)
	MOVW	$654, R8
	B	callbackasm1(SB)
	MOVW	$655, R8
	B	callbackasm1(SB)
	MOVW	$656, R8
	B	callbackasm1(SB)
	MOVW	$657, R8
	B	callbackasm1(SB)
	MOVW	$658, R8
	B	callbackasm1(SB)
	MOVW	$659, R8
	B	callbackasm1(SB)
	MOVW	$660, R8
	B	callbackasm1(SB)
	MOVW	$661, R8
	B	callbackasm1(SB)
	MOVW	$662, R8
	B	callbackasm1(SB)
	MOVW	$663, R8
	B	callbackasm1(SB)
	MOVW	$664, R8
	B	callbackasm1(SB)
	MOVW	$665, R8
	B	callbackasm1(SB)
	MOVW	$666, R8
	B	callbackasm1(SB)
	MOVW	$667, R8
	B	callbackasm1(SB)
	MOVW	$668, R8
	B	callbackasm1(SB)
	MOVW	$669, R8
	B	callbackasm1(SB)
	MOVW	$670, R8
	B	callbackasm1(SB)
	MOVW	$671, R8
	B	callbackasm1(SB)
	MOVW	$672, R8
	B	callbackasm1(SB)
	MOVW	$673, R8
	B	callbackasm1(SB)
	MOVW	$674, R8
	B	callbackasm1(SB)
	MOVW	$675, R8
	B	callbackasm1(SB)
	MOVW	$676, R8
	B	callbackasm1(SB)
	MOVW	$677, R8
	B	callbackasm1(SB)
	MOVW	$678, R8
	B	callbackasm1(SB)
	MOVW	$679, R8
	B	callbackasm1(SB)
	MOVW	$680, R8
	B	callbackasm1(SB)
	MOVW	$681, R8
	B	callbackasm1(SB)
	MOVW	$682, R8
	B	callbackasm1(SB)
	MOVW	$683, R8
	B	callbackasm1(SB)
	MOVW	$684, R8
	B	callbackasm1(SB)
	MOVW	$685, R8
	B	callbackasm1(SB)
	MOVW	$686, R8
	B	callbackasm1(SB)
	MOVW	$687, R8
	B	callbackasm1(SB)
	MOVW	$688, R8
	B	callbackasm1(SB)
	MOVW	$689, R8
	B	callbackasm1(SB)
	MOVW	$690, R8
	B	callbackasm1(SB)
	MOVW	$691, R8
	B	callbackasm1(SB)
	MOVW	$692, R8
	B	callbackasm1(SB)
	MOVW	$693, R8
	B	callbackasm1(SB)
	MOVW	$694, R8
	B	callbackasm1(SB)
	MOVW	$695, R8
	B	callbackasm1(SB)
	MOVW	$696, R8
	B	callbackasm1(SB)
	MOVW	$697, R8
	B	callbackasm1(SB)
	MOVW	$698, R8
	B	callbackasm1(SB)
	MOVW	$699, R8
	B	callbackasm1(SB)
	MOVW	$700, R8
	B	callbackasm1(SB)
	MOVW	$701, R8
	B	callbackasm1(SB)
	MOVW	$702, R8
	B	callbackasm1(SB)
	MOVW	$703, R8
	B	callbackasm1(SB)
	MOVW	$704, R8
	B	callbackasm1(SB)
	MOVW	$705, R8
	B	callbackasm1(SB)
	MOVW	$706, R8
	B	callbackasm1(SB)
	MOVW	$707, R8
	B	callbackasm1(SB)
	MOVW	$708, R8
	B	callbackasm1(SB)
	MOVW	$709, R8
	B	callbackasm1(SB)
	MOVW	$710, R8
	B	callbackasm1(SB)
	MOVW	$711, R8
	B	callbackasm1(SB)
	MOVW	$712, R8
	B	callbackasm1(SB)
	MOVW	$713, R8
	B	callbackasm1(SB)
	MOVW	$714, R8
	B	callbackasm1(SB)
	MOVW	$715, R8
	B	callbackasm1(SB)
	MOVW	$716, R8
	B	callbackasm1(SB)
	MOVW	$717, R8
	B	callbackasm1(SB)
	MOVW	$718, R8
	B	callbackasm1(SB)
	MOVW	$719, R8
	B	callbackasm1(SB)
	MOVW	$720, R8
	B	callbackasm1(SB)
	MOVW	$721, R8
	B	callbackasm1(SB)
	MOVW	$722, R8
	B	callbackasm1(SB)
	MOVW	$723, R8
	B	callbackasm1(SB)
	MOVW	$724, R8
	B	callbackasm1(SB)
	MOVW	$725, R8
	B	callbackasm1(SB)
	MOVW	$726, R8
	B	callbackasm1(SB)
	MOVW	$727, R8
	B	callbackasm1(SB)
	MOVW	$728, R8
	B	callbackasm1(SB)
	MOVW	$729, R8
	B	callbackasm1(SB)
	MOVW	$730, R8
	B	callbackasm1(SB)
	MOVW	$731, R8
	B	callbackasm1(SB)
	MOVW	$732, R8
	B	callbackasm1(SB)
	MOVW	$733, R8
	B	callbackasm1(SB)
	MOVW	$734, R8
	B	callbackasm1(SB)
	MOVW	$735, R8
	B	callbackasm1(SB)
	MOVW	$736, R8
	B	callbackasm1(SB)
	MOVW	$737, R8
	B	callbackasm1(SB)
	MOVW	$738, R8
	B	callbackasm1(SB)
	MOVW	$739, R8
	B	callbackasm1(SB)
	MOVW	$740, R8
	B	callbackasm1(SB)
	MOVW	$741, R8
	B	callbackasm1(SB)
	MOVW	$742, R8
	B	callbackasm1(SB)
	MOVW	$743, R8
	B	callbackasm1(SB)
	MOVW	$744, R8
	B	callbackasm1(SB)
	MOVW	$745, R8
	B	callbackasm1(SB)
	MOVW	$746, R8
	B	callbackasm1(SB)
	MOVW	$747, R8
	B	callbackasm1(SB)
	MOVW	$748, R8
	B	callbackasm1(SB)
	MOVW	$749, R8
	B	callbackasm1(SB)
	MOVW	$750, R8
	B	callbackasm1(SB)
	MOVW	$751, R8
	B	callbackasm1(SB)
	MOVW	$752, R8
	B	callbackasm1(SB)
	MOVW	$753, R8
	B	callbackasm1(SB)
	MOVW	$754, R8
	B	callbackasm1(SB)
	MOVW	$755, R8
	B	callbackasm1(SB)
	MOVW	$756, R8
	B	callbackasm1(SB)
	MOVW	$757, R8
	B	callbackasm1(SB)
	MOVW	$758, R8
	B	callbackasm1(SB)
	MOVW	$759, R8
	B	callbackasm1(SB)
	MOVW	$760, R8
	B	callbackasm1(SB)
	MOVW	$761, R8
	B	callbackasm1(SB)
	MOVW	$762, R8
	B	callbackasm1(SB)
	MOVW	$763, R8
	B	callbackasm1(SB)
	MOVW	$764, R8
	B	callbackasm1(SB)
	MOVW	$765, R8
	B	callbackasm1(SB)
	MOVW	$766, R8
	B	callbackasm1(SB)
	MOVW	$767, R8
	B	callbackasm1(SB)
	MOVW	$768, R8
	B	callbackasm1(SB)
	MOVW	$769, R8
	B	callbackasm1(SB)
	MOVW	$770, R8
	B	callbackasm1(SB)
	MOVW	$771, R8
	B	callbackasm1(SB)
	MOVW	$772, R8
	B	callbackasm1(SB)
	MOVW	$773, R8
	B	callbackasm1(SB)
	MOVW	$774, R8
	B	callbackasm1(SB)
	MOVW	$775, R8
	B	callbackasm1(SB)
	MOVW	$776, R8
	B	callbackasm1(SB)
	MOVW	$777, R8
	B	callbackasm1(SB)
	MOVW	$778, R8
	B	callbackasm1(SB)
	MOVW	$779, R8
	B	callbackasm1(SB)
	MOVW	$780, R8
	B	callbackasm1(SB)
	MOVW	$781, R8
	B	callbackasm1(SB)
	MOVW	$782, R8
	B	callbackasm1(SB)
	MOVW	$783, R8
	B	callbackasm1(SB)
	MOVW	$784, R8
	B	callbackasm1(SB)
	MOVW	$785, R8
	B	callbackasm1(SB)
	MOVW	$786, R8
	B	callbackasm1(SB)
	MOVW	$787, R8
	B	callbackasm1(SB)
	MOVW	$788, R8
	B	callbackasm1(SB)
	MOVW	$789, R8
	B	callbackasm1(SB)
	MOVW	$790, R8
	B	callbackasm1(SB)
	MOVW	$791, R8
	B	callbackasm1(SB)
	MOVW	$792, R8
	B	callbackasm1(SB)
	MOVW	$793, R8
	B	callbackasm1(SB)
	MOVW	$794, R8
	B	callbackasm1(SB)
	MOVW	$795, R8
	B	callbackasm1(SB)
	MOVW	$796, R8
	B	callbackasm1(SB)
	MOVW	$797, R8
	B	callbackasm1(SB)
	MOVW	$798, R8
	B	callbackasm1(SB)
	MOVW	$799, R8
	B	callbackasm1(SB)
	MOVW	$800, R8
	B	callbackasm1(SB)
	MOVW	$801, R8
	B	callbackasm1(SB)
	MOVW	$802, R8
	B	callbackasm1(SB)
	MOVW	$803, R8
	B	callbackasm1(SB)
	MOVW	$804, R8
	B	callbackasm1(SB)
	MOVW	$805, R8
	B	callbackasm1(SB)
	MOVW	$806, R8
	B	callbackasm1(SB)
	MOVW	$807, R8
	B	callbackasm1(SB)
	MOVW	$808, R8
	B	callbackasm1(SB)
	MOVW	$809, R8
	B	callbackasm1(SB)
	MOVW	$810, R8
	B	callbackasm1(SB)
	MOVW	$811, R8
	B	callbackasm1(SB)
	MOVW	$812, R8
	B	callbackasm1(SB)
	MOVW	$813, R8
	B	callbackasm1(SB)
	MOVW	$814, R8
	B	callbackasm1(SB)
	MOVW	$815, R8
	B	callbackasm1(SB)
	MOVW	$816, R8
	B	callbackasm1(SB)
	MOVW	$817, R8
	B	callbackasm1(SB)
	MOVW	$818, R8
	B	callbackasm1(SB)
	MOVW	$819, R8
	B	callbackasm1(SB)
	MOVW	$820, R8
	B	callbackasm1(SB)
	MOVW	$821, R8
	B	callbackasm1(SB)
	MOVW	$822, R8
	B	callbackasm1(SB)
	MOVW	$823, R8
	B	callbackasm1(SB)
	MOVW	$824, R8
	B	callbackasm1(SB)
	MOVW	$825, R8
	B	callbackasm1(SB)
	MOVW	$826, R8
	B	callbackasm1(SB)
	MOVW	$827, R8
	B	callbackasm1(SB)
	MOVW	$828, R8
	B	callbackasm1(SB)
	MOVW	$829, R8
	B	callbackasm1(SB)
	MOVW	$830, R8
	B	callbackasm1(SB)
	MOVW	$831, R8
	B	callbackasm1(SB)
	MOVW	$832, R8
	B	callbackasm1(SB)
	MOVW	$833, R8
	B	callbackasm1(SB)
	MOVW	$834, R8
	B	callbackasm1(SB)
	MOVW	$835, R8
	B	callbackasm1(SB)
	MOVW	$836, R8
	B	callbackasm1(SB)
	MOVW	$837, R8
	B	callbackasm1(SB)
	MOVW	$838, R8
	B	callbackasm1(SB)
	MOVW	$839, R8
	B	callbackasm1(SB)
	MOVW	$840, R8
	B	callbackasm1(SB)
	MOVW	$841, R8
	B	callbackasm1(SB)
	MOVW	$842, R8
	B	callbackasm1(SB)
	MOVW	$843, R8
	B	callbackasm1(SB)
	MOVW	$844, R8
	B	callbackasm1(SB)
	MOVW	$845, R8
	B	callbackasm1(SB)
	MOVW	$846, R8
	B	callbackasm1(SB)
	MOVW	$847, R8
	B	callbackasm1(SB)
	MOVW	$848, R8
	B	callbackasm1(SB)
	MOVW	$849, R8
	B	callbackasm1(SB)
	MOVW	$850, R8
	B	callbackasm1(SB)
	MOVW	$851, R8
	B	callbackasm1(SB)
	MOVW	$852, R8
	B	callbackasm1(SB)
	MOVW	$853, R8
	B	callbackasm1(SB)
	MOVW	$854, R8
	B	callbackasm1(SB)
	MOVW	$855, R8
	B	callbackasm1(SB)
	MOVW	$856, R8
	B	callbackasm1(SB)
	MOVW	$857, R8
	B	callbackasm1(SB)
	MOVW	$858, R8
	B	callbackasm1(SB)
	MOVW	$859, R8
	B	callbackasm1(SB)
	MOVW	$860, R8
	B	callbackasm1(SB)
	MOVW	$861, R8
	B	callbackasm1(SB)
	MOVW	$862, R8
	B	callbackasm1(SB)
	MOVW	$863, R8
	B	callbackasm1(SB)
	MOVW	$864, R8
	B	callbackasm1(SB)
	MOVW	$865, R8
	B	callbackasm1(SB)
	MOVW	$866, R8
	B	callbackasm1(SB)
	MOVW	$867, R8
	B	callbackasm1(SB)
	MOVW	$868, R8
	B	callbackasm1(SB)
	MOVW	$869, R8
	B	callbackasm1(SB)
	MOVW	$870, R8
	B	callbackasm1(SB)
	MOVW	$871, R8
	B	callbackasm1(SB)
	MOVW	$872, R8
	B	callbackasm1(SB)
	MOVW	$873, R8
	B	callbackasm1(SB)
	MOVW	$874, R8
	B	callbackasm1(SB)
	MOVW	$875, R8
	B	callbackasm1(SB)
	MOVW	$876, R8
	B	callbackasm1(SB)
	MOVW	$877, R8
	B	callbackasm1(SB)
	MOVW	$878, R8
	B	callbackasm1(SB)
	MOVW	$879, R8
	B	callbackasm1(SB)
	MOVW	$880, R8
	B	callbackasm1(SB)
	MOVW	$881, R8
	B	callbackasm1(SB)
	MOVW	$882, R8
	B	callbackasm1(SB)
	MOVW	$883, R8
	B	callbackasm1(SB)
	MOVW	$884, R8
	B	callbackasm1(SB)
	MOVW	$885, R8
	B	callbackasm1(SB)
	MOVW	$886, R8
	B	callbackasm1(SB)
	MOVW	$887, R8
	B	callbackasm1(SB)
	MOVW	$888, R8
	B	callbackasm1(SB)
	MOVW	$889, R8
	B	callbackasm1(SB)
	MOVW	$890, R8
	B	callbackasm1(SB)
	MOVW	$891, R8
	B	callbackasm1(SB)
	MOVW	$892, R8
	B	callbackasm1(SB)
	MOVW	$893, R8
	B	callbackasm1(SB)
	MOVW	$894, R8
	B	callbackasm1(SB)
	MOVW	$895, R8
	B	callbackasm1(SB)
	MOVW	$896, R8
	B	callbackasm1(SB)
	MOVW	$897, R8
	B	callbackasm1(SB)
	MOVW	$898, R8
	B	callbackasm1(SB)
	MOVW	$899, R8
	B	callbackasm1(SB)
	MOVW	$900, R8
	B	callbackasm1(SB)
	MOVW	$901, R8
	B	callbackasm1(SB)
	MOVW	$902, R8
	B	callbackasm1(SB)
	MOVW	$903, R8
	B	callbackasm1(SB)
	MOVW	$904, R8
	B	callbackasm1(SB)
	MOVW	$905, R8
	B	callbackasm1(SB)
	MOVW	$906, R8
	B	callbackasm1(SB)
	MOVW	$907, R8
	B	callbackasm1(SB)
	MOVW	$908, R8
	B	callbackasm1(SB)
	MOVW	$909, R8
	B	callbackasm1(SB)
	MOVW	$910, R8
	B	callbackasm1(SB)
	MOVW	$911, R8
	B	callbackasm1(SB)
	MOVW	$912, R8
	B	callbackasm1(SB)
	MOVW	$913, R8
	B	callbackasm1(SB)
	MOVW	$914, R8
	B	callbackasm1(SB)
	MOVW	$915, R8
	B	callbackasm1(SB)
	MOVW	$916, R8
	B	callbackasm1(SB)
	MOVW	$917, R8
	B	callbackasm1(SB)
	MOVW	$918, R8
	B	callbackasm1(SB)
	MOVW	$919, R8
	B	callbackasm1(SB)
	MOVW	$920, R8
	B	callbackasm1(SB)
	MOVW	$921, R8
	B	callbackasm1(SB)
	MOVW	$922, R8
	B	callbackasm1(SB)
	MOVW	$923, R8
	B	callbackasm1(SB)
	MOVW	$924, R8
	B	callbackasm1(SB)
	MOVW	$925, R8
	B	callbackasm1(SB)
	MOVW	$926, R8
	B	callbackasm1(SB)
	MOVW	$927, R8
	B	callbackasm1(SB)
	MOVW	$928, R8
	B	callbackasm1(SB)
	MOVW	$929, R8
	B	callbackasm1(SB)
	MOVW	$930, R8
	B	callbackasm1(SB)
	MOVW	$931, R8
	B	callbackasm1(SB)
	MOVW	$932, R8
	B	callbackasm1(SB)
	MOVW	$933, R8
	B	callbackasm1(SB)
	MOVW	$934, R8
	B	callbackasm1(SB)
	MOVW	$935, R8
	B	callbackasm1(SB)
	MOVW	$936, R8
	B	callbackasm1(SB)
	MOVW	$937, R8
	B	callbackasm1(SB)
	MOVW	$938, R8
	B	callbackasm1(SB)
	MOVW	$939, R8
	B	callbackasm1(SB)
	MOVW	$940, R8
	B	callbackasm1(SB)
	MOVW	$941, R8
	B	callbackasm1(SB)
	MOVW	$942, R8
	B	callbackasm1(SB)
	MOVW	$943, R8
	B	callbackasm1(SB)
	MOVW	$944, R8
	B	callbackasm1(SB)
	MOVW	$945, R8
	B	callbackasm1(SB)
	MOVW	$946, R8
	B	callbackasm1(SB)
	MOVW	$947, R8
	B	callbackasm1(SB)
	MOVW	$948, R8
	B	callbackasm1(SB)
	MOVW	$949, R8
	B	callbackasm1(SB)
	MOVW	$950, R8
	B	callbackasm1(SB)
	MOVW	$951, R8
	B	callbackasm1(SB)
	MOVW	$952, R8
	B	callbackasm1(SB)
	MOVW	$953, R8
	B	callbackasm1(SB)
	MOVW	$954, R8
	B	callbackasm1(SB)
	MOVW	$955, R8
	B	callbackasm1(SB)
	MOVW	$956, R8
	B	callbackasm1(SB)
	MOVW	$957, R8
	B	callbackasm1(SB)
	MOVW	$958, R8
	B	callbackasm1(SB)
	MOVW	$959, R8
	B	callbackasm1(SB)
	MOVW	$960, R8
	B	callbackasm1(SB)
	MOVW	$961, R8
	B	callbackasm1(SB)
	MOVW	$962, R8
	B	callbackasm1(SB)
	MOVW	$963, R8
	B	callbackasm1(SB)
	MOVW	$964, R8
	B	callbackasm1(SB)
	MOVW	$965, R8
	B	callbackasm1(SB)
	MOVW	$966, R8
	B	callbackasm1(SB)
	MOVW	$967, R8
	B	callbackasm1(SB)
	MOVW	$968, R8
	B	callbackasm1(SB)
	MOVW	$969, R8
	B	callbackasm1(SB)
	MOVW	$970, R8
	B	callbackasm1(SB)
	MOVW	$971, R8
	B	callbackasm1(SB)
	MOVW	$972, R8
	B	callbackasm1(SB)
	MOVW	$973, R8
	B	callbackasm1(SB)
	MOVW	$974, R8
	B	callbackasm1(SB)
	MOVW	$975, R8
	B	callbackasm1(SB)
	MOVW	$976, R8
	B	callbackasm1(SB)
	MOVW	$977, R8
	B	callbackasm1(SB)
	MOVW	$978, R8
	B	callbackasm1(SB)
	MOVW	$979, R8
	B	callbackasm1(SB)
	MOVW	$980, R8
	B	callbackasm1(SB)
	MOVW	$981, R8
	B	callbackasm1(SB)
	MOVW	$982, R8
	B	callbackasm1(SB)
	MOVW	$983, R8
	B	callbackasm1(SB)
	MOVW	$984, R8
	B	callbackasm1(SB)
	MOVW	$985, R8
	B	callbackasm1(SB)
	MOVW	$986, R8
	B	callbackasm1(SB)
	MOVW	$987, R8
	B	callbackasm1(SB)
	MOVW	$988, R8
	B	callbackasm1(SB)
	MOVW	$989, R8
	B	callbackasm1(SB)
	MOVW	$990, R8
	B	callbackasm1(SB)
	MOVW	$991, R8
	B	callbackasm1(SB)
	MOVW	$992, R8
	B	callbackasm1(SB)
	MOVW	$993, R8
	B	callbackasm1(SB)
	MOVW	$994, R8
	B	callbackasm1(SB)
	MOVW	$995, R8
	B	callbackasm1(SB)
	MOVW	$996, R8
	B	callbackasm1(SB)
	MOVW	$997, R8
	B	callbackasm1(SB)
	MOVW	$998, R8
	B	callbackasm1(SB)
	MOVW	$999, R8
	B	callbackasm1(SB)
	MOVW	$1000, R8
	B	callbackasm1(SB)
	MOVW	$1001, R8
	B	callbackasm1(SB)
	MOVW	$1002, R8
	B	callbackasm1(SB)
	MOVW	$1003, R8
	B	callbackasm1(SB)
	MOVW	$1004, R8
	B	callbackasm1(SB)
	MOVW	$1005, R8
	B	callbackasm1(SB)
	MOVW	$1006, R8
	B	callbackasm1(SB)
	MOVW	$1007, R8
	B	callbackasm1(SB)
	MOVW	$1008, R8
	B	callbackasm1(SB)
	MOVW	$1009, R8
	B	callbackasm1(SB)
	MOVW	$1010, R8
	B	callbackasm1(SB)
	MOVW	$1011, R8
	B	callbackasm1(SB)
	MOVW	$1012, R8
	B	callbackasm1(SB)
	MOVW	$1013, R8
	B	callbackasm1(SB)
	MOVW	$1014, R8
	B	callbackasm1(SB)
	MOVW	$1015, R8
	B	callbackasm1(SB)
	MOVW	$1016, R8
	B	callbackasm1(SB)
	MOVW	$1017, R8
	B	callbackasm1(SB)
	MOVW	$1018, R8
	B	callbackasm1(SB)
	MOVW	$1019, R8
	B	callbackasm1(SB)
	MOVW	$1020, R8
	B	callbackasm1(SB)
	MOVW	$1021, R8
	B	callbackasm1(SB)
	MOVW	$1022, R8
	B	callbackasm1(SB)
	MOVW	$1023, R8
	B	callbackasm1(SB)
	MOVW	$1024, R8
	B	callbackasm1(SB)
	MOVW	$1025, R8
	B	callbackasm1(SB)
	MOVW	$1026, R8
	B	callbackasm1(SB)
	MOVW	$1027, R8
	B	callbackasm1(SB)
	MOVW	$1028, R8
	B	callbackasm1(SB)
	MOVW	$1029, R8
	B	callbackasm1(SB)
	MOVW	$1030, R8
	B	callbackasm1(SB)
	MOVW	$1031, R8
	B	callbackasm1(SB)
	MOVW	$1032, R8
	B	callbackasm1(SB)
	MOVW	$1033, R8
	B	callbackasm1(SB)
	MOVW	$1034, R8
	B	callbackasm1(SB)
	MOVW	$1035, R8
	B	callbackasm1(SB)
	MOVW	$1036, R8
	B	callbackasm1(SB)
	MOVW	$1037, R8
	B	callbackasm1(SB)
	MOVW	$1038, R8
	B	callbackasm1(SB)
	MOVW	$1039, R8
	B	callbackasm1(SB)
	MOVW	$1040, R8
	B	callbackasm1(SB)
	MOVW	$1041, R8
	B	callbackasm1(SB)
	MOVW	$1042, R8
	B	callbackasm1(SB)
	MOVW	$1043, R8
	B	callbackasm1(SB)
	MOVW	$1044, R8
	B	callbackasm1(SB)
	MOVW	$1045, R8
	B	callbackasm1(SB)
	MOVW	$1046, R8
	B	callbackasm1(SB)
	MOVW	$1047, R8
	B	callbackasm1(SB)
	MOVW	$1048, R8
	B	callbackasm1(SB)
	MOVW	$1049, R8
	B	callbackasm1(SB)
	MOVW	$1050, R8
	B	callbackasm1(SB)
	MOVW	$1051, R8
	B	callbackasm1(SB)
	MOVW	$1052, R8
	B	callbackasm1(SB)
	MOVW	$1053, R8
	B	callbackasm1(SB)
	MOVW	$1054, R8
	B	callbackasm1(SB)
	MOVW	$1055, R8
	B	callbackasm1(SB)
	MOVW	$1056, R8
	B	callbackasm1(SB)
	MOVW	$1057, R8
	B	callbackasm1(SB)
	MOVW	$1058, R8
	B	callbackasm1(SB)
	MOVW	$1059, R8
	B	callbackasm1(SB)
	MOVW	$1060, R8
	B	callbackasm1(SB)
	MOVW	$1061, R8
	B	callbackasm1(SB)
	MOVW	$1062, R8
	B	callbackasm1(SB)
	MOVW	$1063, R8
	B	callbackasm1(SB)
	MOVW	$1064, R8
	B	callbackasm1(SB)
	MOVW	$1065, R8
	B	callbackasm1(SB)
	MOVW	$1066, R8
	B	callbackasm1(SB)
	MOVW	$1067, R8
	B	callbackasm1(SB)
	MOVW	$1068, R8
	B	callbackasm1(SB)
	MOVW	$1069, R8
	B	callbackasm1(SB)
	MOVW	$1070, R8
	B	callbackasm1(SB)
	MOVW	$1071, R8
	B	callbackasm1(SB)
	MOVW	$1072, R8
	B	callbackasm1(SB)
	MOVW	$1073, R8
	B	callbackasm1(SB)
	MOVW	$1074, R8
	B	callbackasm1(SB)
	MOVW	$1075, R8
	B	callbackasm1(SB)
	MOVW	$1076, R8
	B	callbackasm1(SB)
	MOVW	$1077, R8
	B	callbackasm1(SB)
	MOVW	$1078, R8
	B	callbackasm1(SB)
	MOVW	$1079, R8
	B	callbackasm1(SB)
	MOVW	$1080, R8
	B	callbackasm1(SB)
	MOVW	$1081, R8
	B	callbackasm1(SB)
	MOVW	$1082, R8
	B	callbackasm1(SB)
	MOVW	$1083, R8
	B	callbackasm1(SB)
	MOVW	$1084, R8
	B	callbackasm1(SB)
	MOVW	$1085, R8
	B	callbackasm1(SB)
	MOVW	$1086, R8
	B	callbackasm1(SB)
	MOVW	$1087, R8
	B	callbackasm1(SB)
	MOVW	$1088, R8
	B	callbackasm1(SB)
	MOVW	$1089, R8
	B	callbackasm1(SB)
	MOVW	$1090, R8
	B	callbackasm1(SB)
	MOVW	$1091, R8
	B	callbackasm1(SB)
	MOVW	$1092, R8
	B	callbackasm1(SB)
	MOVW	$1093, R8
	B	callbackasm1(SB)
	MOVW	$1094, R8
	B	callbackasm1(SB)
	MOVW	$1095, R8
	B	callbackasm1(SB)
	MOVW	$1096, R8
	B	callbackasm1(SB)
	MOVW	$1097, R8
	B	callbackasm1(SB)
	MOVW	$1098, R8
	B	callbackasm1(SB)
	MOVW	$1099, R8
	B	callbackasm1(SB)
	MOVW	$1100, R8
	B	callbackasm1(SB)
	MOVW	$1101, R8
	B	callbackasm1(SB)
	MOVW	$1102, R8
	B	callbackasm1(SB)
	MOVW	$1103, R8
	B	callbackasm1(SB)
	MOVW	$1104, R8
	B	callbackasm1(SB)
	MOVW	$1105, R8
	B	callbackasm1(SB)
	MOVW	$1106, R8
	B	callbackasm1(SB)
	MOVW	$1107, R8
	B	callbackasm1(SB)
	MOVW	$1108, R8
	B	callbackasm1(SB)
	MOVW	$1109, R8
	B	callbackasm1(SB)
	MOVW	$1110, R8
	B	callbackasm1(SB)
	MOVW	$1111, R8
	B	callbackasm1(SB)
	MOVW	$1112, R8
	B	callbackasm1(SB)
	MOVW	$1113, R8
	B	callbackasm1(SB)
	MOVW	$1114, R8
	B	callbackasm1(SB)
	MOVW	$1115, R8
	B	callbackasm1(SB)
	MOVW	$1116, R8
	B	callbackasm1(SB)
	MOVW	$1117, R8
	B	callbackasm1(SB)
	MOVW	$1118, R8
	B	callbackasm1(SB)
	MOVW	$1119, R8
	B	callbackasm1(SB)
	MOVW	$1120, R8
	B	callbackasm1(SB)
	MOVW	$1121, R8
	B	callbackasm1(SB)
	MOVW	$1122, R8
	B	callbackasm1(SB)
	MOVW	$1123, R8
	B	callbackasm1(SB)
	MOVW	$1124, R8
	B	callbackasm1(SB)
	MOVW	$1125, R8
	B	callbackasm1(SB)
	MOVW	$1126, R8
	B	callbackasm1(SB)
	MOVW	$1127, R8
	B	callbackasm1(SB)
	MOVW	$1128, R8
	B	callbackasm1(SB)
	MOVW	$1129, R8
	B	callbackasm1(SB)
	MOVW	$1130, R8
	B	callbackasm1(SB)
	MOVW	$1131, R8
	B	callbackasm1(SB)
	MOVW	$1132, R8
	B	callbackasm1(SB)
	MOVW	$1133, R8
	B	callbackasm1(SB)
	MOVW	$1134, R8
	B	callbackasm1(SB)
	MOVW	$1135, R8
	B	callbackasm1(SB)
	MOVW	$1136, R8
	B	callbackasm1(SB)
	MOVW	$1137, R8
	B	callbackasm1(SB)
	MOVW	$1138, R8
	B	callbackasm1(SB)
	MOVW	$1139, R8
	B	callbackasm1(SB)
	MOVW	$1140, R8
	B	callbackasm1(SB)
	MOVW	$1141, R8
	B	callbackasm1(SB)
	MOVW	$1142, R8
	B	callbackasm1(SB)
	MOVW	$1143, R8
	B	callbackasm1(SB)
	MOVW	$1144, R8
	B	callbackasm1(SB)
	MOVW	$1145, R8
	B	callbackasm1(SB)
	MOVW	$1146, R8
	B	callbackasm1(SB)
	MOVW	$1147, R8
	B	callbackasm1(SB)
	MOVW	$1148, R8
	B	callbackasm1(SB)
	MOVW	$1149, R8
	B	callbackasm1(SB)
	MOVW	$1150, R8
	B	callbackasm1(SB)
	MOVW	$1151, R8
	B	callbackasm1(SB)
	MOVW	$1152, R8
	B	callbackasm1(SB)
	MOVW	$1153, R8
	B	callbackasm1(SB)
	MOVW	$1154, R8
	B	callbackasm1(SB)
	MOVW	$1155, R8
	B	callbackasm1(SB)
	MOVW	$1156, R8
	B	callbackasm1(SB)
	MOVW	$1157, R8
	B	callbackasm1(SB)
	MOVW	$1158, R8
	B	callbackasm1(SB)
	MOVW	$1159, R8
	B	callbackasm1(SB)
	MOVW	$1160, R8
	B	callbackasm1(SB)
	MOVW	$1161, R8
	B	callbackasm1(SB)
	MOVW	$1162, R8
	B	callbackasm1(SB)
	MOVW	$1163, R8
	B	callbackasm1(SB)
	MOVW	$1164, R8
	B	callbackasm1(SB)
	MOVW	$1165, R8
	B	callbackasm1(SB)
	MOVW	$1166, R8
	B	callbackasm1(SB)
	MOVW	$1167, R8
	B	callbackasm1(SB)
	MOVW	$1168, R8
	B	callbackasm1(SB)
	MOVW	$1169, R8
	B	callbackasm1(SB)
	MOVW	$1170, R8
	B	callbackasm1(SB)
	MOVW	$1171, R8
	B	callbackasm1(SB)
	MOVW	$1172, R8
	B	callbackasm1(SB)
	MOVW	$1173, R8
	B	callbackasm1(SB)
	MOVW	$1174, R8
	B	callbackasm1(SB)
	MOVW	$1175, R8
	B	callbackasm1(SB)
	MOVW	$1176, R8
	B	callbackasm1(SB)
	MOVW	$1177, R8
	B	callbackasm1(SB)
	MOVW	$1178, R8
	B	callbackasm1(SB)
	MOVW	$1179, R8
	B	callbackasm1(SB)
	MOVW	$1180, R8
	B	callbackasm1(SB)
	MOVW	$1181, R8
	B	callbackasm1(SB)
	MOVW	$1182, R8
	B	callbackasm1(SB)
	MOVW	$1183, R8
	B	callbackasm1(SB)
	MOVW	$1184, R8
	B	callbackasm1(SB)
	MOVW	$1185, R8
	B	callbackasm1(SB)
	MOVW	$1186, R8
	B	callbackasm1(SB)
	MOVW	$1187, R8
	B	callbackasm1(SB)
	MOVW	$1188, R8
	B	callbackasm1(SB)
	MOVW	$1189, R8
	B	callbackasm1(SB)
	MOVW	$1190, R8
	B	callbackasm1(SB)
	MOVW	$1191, R8
	B	callbackasm1(SB)
	MOVW	$1192, R8
	B	callbackasm1(SB)
	MOVW	$1193, R8
	B	callbackasm1(SB)
	MOVW	$1194, R8
	B	callbackasm1(SB)
	MOVW	$1195, R8
	B	callbackasm1(SB)
	MOVW	$1196, R8
	B	callbackasm1(SB)
	MOVW	$1197, R8
	B	callbackasm1(SB)
	MOVW	$1198, R8
	B	callbackasm1(SB)
	MOVW	$1199, R8
	B	callbackasm1(SB)
	MOVW	$1200, R8
	B	callbackasm1(SB)
	MOVW	$1201, R8
	B	callbackasm1(SB)
	MOVW	$1202, R8
	B	callbackasm1(SB)
	MOVW	$1203, R8
	B	callbackasm1(SB)
	MOVW	$1204, R8
	B	callbackasm1(SB)
	MOVW	$1205, R8
	B	callbackasm1(SB)
	MOVW	$1206, R8
	B	callbackasm1(SB)
	MOVW	$1207, R8
	B	callbackasm1(SB)
	MOVW	$1208, R8
	B	callbackasm1(SB)
	MOVW	$1209, R8
	B	callbackasm1(SB)
	MOVW	$1210, R8
	B	callbackasm1(SB)
	MOVW	$1211, R8
	B	callbackasm1(SB)
	MOVW	$1212, R8
	B	callbackasm1(SB)
	MOVW	$1213, R8
	B	callbackasm1(SB)
	MOVW	$1214, R8
	B	callbackasm1(SB)
	MOVW	$1215, R8
	B	callbackasm1(SB)
	MOVW	$1216, R8
	B	callbackasm1(SB)
	MOVW	$1217, R8
	B	callbackasm1(SB)
	MOVW	$1218, R8
	B	callbackasm1(SB)
	MOVW	$1219, R8
	B	callbackasm1(SB)
	MOVW	$1220, R8
	B	callbackasm1(SB)
	MOVW	$1221, R8
	B	callbackasm1(SB)
	MOVW	$1222, R8
	B	callbackasm1(SB)
	MOVW	$1223, R8
	B	callbackasm1(SB)
	MOVW	$1224, R8
	B	callbackasm1(SB)
	MOVW	$1225, R8
	B	callbackasm1(SB)
	MOVW	$1226, R8
	B	callbackasm1(SB)
	MOVW	$1227, R8
	B	callbackasm1(SB)
	MOVW	$1228, R8
	B	callbackasm1(SB)
	MOVW	$1229, R8
	B	callbackasm1(SB)
	MOVW	$1230, R8
	B	callbackasm1(SB)
	MOVW	$1231, R8
	B	callbackasm1(SB)
	MOVW	$1232, R8
	B	callbackasm1(SB)
	MOVW	$1233, R8
	B	callbackasm1(SB)
	MOVW	$1234, R8
	B	callbackasm1(SB)
	MOVW	$1235, R8
	B	callbackasm1(SB)
	MOVW	$1236, R8
	B	callbackasm1(SB)
	MOVW	$1237, R8
	B	callbackasm1(SB)
	MOVW	$1238, R8
	B	callbackasm1(SB)
	MOVW	$1239, R8
	B	callbackasm1(SB)
	MOVW	$1240, R8
	B	callbackasm1(SB)
	MOVW	$1241, R8
	B	callbackasm1(SB)
	MOVW	$1242, R8
	B	callbackasm1(SB)
	MOVW	$1243, R8
	B	callbackasm1(SB)
	MOVW	$1244, R8
	B	callbackasm1(SB)
	MOVW	$1245, R8
	B	callbackasm1(SB)
	MOVW	$1246, R8
	B	callbackasm1(SB)
	MOVW	$1247, R8
	B	callbackasm1(SB)
	MOVW	$1248, R8
	B	callbackasm1(SB)
	MOVW	$1249, R8
	B	callbackasm1(SB)
	MOVW	$1250, R8
	B	callbackasm1(SB)
	MOVW	$1251, R8
	B	callbackasm1(SB)
	MOVW	$1252, R8
	B	callbackasm1(SB)
	MOVW	$1253, R8
	B	callbackasm1(SB)
	MOVW	$1254, R8
	B	callbackasm1(SB)
	MOVW	$1255, R8
	B	callbackasm1(SB)
	MOVW	$1256, R8
	B	callbackasm1(SB)
	MOVW	$1257, R8
	B	callbackasm1(SB)
	MOVW	$1258, R8
	B	callbackasm1(SB)
	MOVW	$1259, R8
	B	callbackasm1(SB)
	MOVW	$1260, R8
	B	callbackasm1(SB)
	MOVW	$1261, R8
	B	callbackasm1(SB)
	MOVW	$1262, R8
	B	callbackasm1(SB)
	MOVW	$1263, R8
	B	callbackasm1(SB)
	MOVW	$1264, R8
	B	callbackasm1(SB)
	MOVW	$1265, R8
	B	callbackasm1(SB)
	MOVW	$1266, R8
	B	callbackasm1(SB)
	MOVW	$1267, R8
	B	callbackasm1(SB)
	MOVW	$1268, R8
	B	callbackasm1(SB)
	MOVW	$1269, R8
	B	callbackasm1(SB)
	MOVW	$1270, R8
	B	callbackasm1(SB)
	MOVW	$1271, R8
	B	callbackasm1(SB)
	MOVW	$1272, R8
	B	callbackasm1(SB)
	MOVW	$1273, R8
	B	callbackasm1(SB)
	MOVW	$1274, R8
	B	callbackasm1(SB)
	MOVW	$1275, R8
	B	callbackasm1(SB)
	MOVW	$1276, R8
	B	callbackasm1(SB)
	MOVW	$1277, R8
	B	callbackasm1(SB)
	MOVW	$1278, R8
	B	callbackasm1(SB)
	MOVW	$1279, R8
	B	callbackasm1(SB)
	MOVW	$1280, R8
	B	callbackasm1(SB)
	MOVW	$1281, R8
	B	callbackasm1(SB)
	MOVW	$1282, R8
	B	callbackasm1(SB)
	MOVW	$1283, R8
	B	callbackasm1(SB)
	MOVW	$1284, R8
	B	callbackasm1(SB)
	MOVW	$1285, R8
	B	callbackasm1(SB)
	MOVW	$1286, R8
	B	callbackasm1(SB)
	MOVW	$1287, R8
	B	callbackasm1(SB)
	MOVW	$1288, R8
	B	callbackasm1(SB)
	MOVW	$1289, R8
	B	callbackasm1(SB)
	MOVW	$1290, R8
	B	callbackasm1(SB)
	MOVW	$1291, R8
	B	callbackasm1(SB)
	MOVW	$1292, R8
	B	callbackasm1(SB)
	MOVW	$1293, R8
	B	callbackasm1(SB)
	MOVW	$1294, R8
	B	callbackasm1(SB)
	MOVW	$1295, R8
	B	callbackasm1(SB)
	MOVW	$1296, R8
	B	callbackasm1(SB)
	MOVW	$1297, R8
	B	callbackasm1(SB)
	MOVW	$1298, R8
	B	callbackasm1(SB)
	MOVW	$1299, R8
	B	callbackasm1(SB)
	MOVW	$1300, R8
	B	callbackasm1(SB)
	MOVW	$1301, R8
	B	callbackasm1(SB)
	MOVW	$1302, R8
	B	callbackasm1(SB)
	MOVW	$1303, R8
	B	callbackasm1(SB)
	MOVW	$1304, R8
	B	callbackasm1(SB)
	MOVW	$1305, R8
	B	callbackasm1(SB)
	MOVW	$1306, R8
	B	callbackasm1(SB)
	MOVW	$1307, R8
	B	callbackasm1(SB)
	MOVW	$1308, R8
	B	callbackasm1(SB)
	MOVW	$1309, R8
	B	callbackasm1(SB)
	MOVW	$1310, R8
	B	callbackasm1(SB)
	MOVW	$1311, R8
	B	callbackasm1(SB)
	MOVW	$1312, R8
	B	callbackasm1(SB)
	MOVW	$1313, R8
	B	callbackasm1(SB)
	MOVW	$1314, R8
	B	callbackasm1(SB)
	MOVW	$1315, R8
	B	callbackasm1(SB)
	MOVW	$1316, R8
	B	callbackasm1(SB)
	MOVW	$1317, R8
	B	callbackasm1(SB)
	MOVW	$1318, R8
	B	callbackasm1(SB)
	MOVW	$1319, R8
	B	callbackasm1(SB)
	MOVW	$1320, R8
	B	callbackasm1(SB)
	MOVW	$1321, R8
	B	callbackasm1(SB)
	MOVW	$1322, R8
	B	callbackasm1(SB)
	MOVW	$1323, R8
	B	callbackasm1(SB)
	MOVW	$1324, R8
	B	callbackasm1(SB)
	MOVW	$1325, R8
	B	callbackasm1(SB)
	MOVW	$1326, R8
	B	callbackasm1(SB)
	MOVW	$1327, R8
	B	callbackasm1(SB)
	MOVW	$1328, R8
	B	callbackasm1(SB)
	MOVW	$1329, R8
	B	callbackasm1(SB)
	MOVW	$1330, R8
	B	callbackasm1(SB)
	MOVW	$1331, R8
	B	callbackasm1(SB)
	MOVW	$1332, R8
	B	callbackasm1(SB)
	MOVW	$1333, R8
	B	callbackasm1(SB)
	MOVW	$1334, R8
	B	callbackasm1(SB)
	MOVW	$1335, R8
	B	callbackasm1(SB)
	MOVW	$1336, R8
	B	callbackasm1(SB)
	MOVW	$1337, R8
	B	callbackasm1(SB)
	MOVW	$1338, R8
	B	callbackasm1(SB)
	MOVW	$1339, R8
	B	callbackasm1(SB)
	MOVW	$1340, R8
	B	callbackasm1(SB)
	MOVW	$1341, R8
	B	callbackasm1(SB)
	MOVW	$1342, R8
	B	callbackasm1(SB)
	MOVW	$1343, R8
	B	callbackasm1(SB)
	MOVW	$1344, R8
	B	callbackasm1(SB)
	MOVW	$1345, R8
	B	callbackasm1(SB)
	MOVW	$1346, R8
	B	callbackasm1(SB)
	MOVW	$1347, R8
	B	callbackasm1(SB)
	MOVW	$1348, R8
	B	callbackasm1(SB)
	MOVW	$1349, R8
	B	callbackasm1(SB)
	MOVW	$1350, R8
	B	callbackasm1(SB)
	MOVW	$1351, R8
	B	callbackasm1(SB)
	MOVW	$1352, R8
	B	callbackasm1(SB)
	MOVW	$1353, R8
	B	callbackasm1(SB)
	MOVW	$1354, R8
	B	callbackasm1(SB)
	MOVW	$1355, R8
	B	callbackasm1(SB)
	MOVW	$1356, R8
	B	callbackasm1(SB)
	MOVW	$1357, R8
	B	callbackasm1(SB)
	MOVW	$1358, R8
	B	callbackasm1(SB)
	MOVW	$1359, R8
	B	callbackasm1(SB)
	MOVW	$1360, R8
	B	callbackasm1(SB)
	MOVW	$1361, R8
	B	callbackasm1(SB)
	MOVW	$1362, R8
	B	callbackasm1(SB)
	MOVW	$1363, R8
	B	callbackasm1(SB)
	MOVW	$1364, R8
	B	callbackasm1(SB)
	MOVW	$1365, R8
	B	callbackasm1(SB)
	MOVW	$1366, R8
	B	callbackasm1(SB)
	MOVW	$1367, R8
	B	callbackasm1(SB)
	MOVW	$1368, R8
	B	callbackasm1(SB)
	MOVW	$1369, R8
	B	callbackasm1(SB)
	MOVW	$1370, R8
	B	callbackasm1(SB)
	MOVW	$1371, R8
	B	callbackasm1(SB)
	MOVW	$1372, R8
	B	callbackasm1(SB)
	MOVW	$1373, R8
	B	callbackasm1(SB)
	MOVW	$1374, R8
	B	callbackasm1(SB)
	MOVW	$1375, R8
	B	callbackasm1(SB)
	MOVW	$1376, R8
	B	callbackasm1(SB)
	MOVW	$1377, R8
	B	callbackasm1(SB)
	MOVW	$1378, R8
	B	callbackasm1(SB)
	MOVW	$1379, R8
	B	callbackasm1(SB)
	MOVW	$1380, R8
	B	callbackasm1(SB)
	MOVW	$1381, R8
	B	callbackasm1(SB)
	MOVW	$1382, R8
	B	callbackasm1(SB)
	MOVW	$1383, R8
	B	callbackasm1(SB)
	MOVW	$1384, R8
	B	callbackasm1(SB)
	MOVW	$1385, R8
	B	callbackasm1(SB)
	MOVW	$1386, R8
	B	callbackasm1(SB)
	MOVW	$1387, R8
	B	callbackasm1(SB)
	MOVW	$1388, R8
	B	callbackasm1(SB)
	MOVW	$1389, R8
	B	callbackasm1(SB)
	MOVW	$1390, R8
	B	callbackasm1(SB)
	MOVW	$1391, R8
	B	callbackasm1(SB)
	MOVW	$1392, R8
	B	callbackasm1(SB)
	MOVW	$1393, R8
	B	callbackasm1(SB)
	MOVW	$1394, R8
	B	callbackasm1(SB)
	MOVW	$1395, R8
	B	callbackasm1(SB)
	MOVW	$1396, R8
	B	callbackasm1(SB)
	MOVW	$1397, R8
	B	callbackasm1(SB)
	MOVW	$1398, R8
	B	callbackasm1(SB)
	MOVW	$1399, R8
	B	callbackasm1(SB)
	MOVW	$1400, R8
	B	callbackasm1(SB)
	MOVW	$1401, R8
	B	callbackasm1(SB)
	MOVW	$1402, R8
	B	callbackasm1(SB)
	MOVW	$1403, R8
	B	callbackasm1(SB)
	MOVW	$1404, R8
	B	callbackasm1(SB)
	MOVW	$1405, R8
	B	callbackasm1(SB)
	MOVW	$1406, R8
	B	callbackasm1(SB)
	MOVW	$1407, R8
	B	callbackasm1(SB)
	MOVW	$1408, R8
	B	callbackasm1(SB)
	MOVW	$1409, R8
	B	callbackasm1(SB)
	MOVW	$1410, R8
	B	callbackasm1(SB)
	MOVW	$1411, R8
	B	callbackasm1(SB)
	MOVW	$1412, R8
	B	callbackasm1(SB)
	MOVW	$1413, R8
	B	callbackasm1(SB)
	MOVW	$1414, R8
	B	callbackasm1(SB)
	MOVW	$1415, R8
	B	callbackasm1(SB)
	MOVW	$1416, R8
	B	callbackasm1(SB)
	MOVW	$1417, R8
	B	callbackasm1(SB)
	MOVW	$1418, R8
	B	callbackasm1(SB)
	MOVW	$1419, R8
	B	callbackasm1(SB)
	MOVW	$1420, R8
	B	callbackasm1(SB)
	MOVW	$1421, R8
	B	callbackasm1(SB)
	MOVW	$1422, R8
	B	callbackasm1(SB)
	MOVW	$1423, R8
	B	callbackasm1(SB)
	MOVW	$1424, R8
	B	callbackasm1(SB)
	MOVW	$1425, R8
	B	callbackasm1(SB)
	MOVW	$1426, R8
	B	callbackasm1(SB)
	MOVW	$1427, R8
	B	callbackasm1(SB)
	MOVW	$1428, R8
	B	callbackasm1(SB)
	MOVW	$1429, R8
	B	callbackasm1(SB)
	MOVW	$1430, R8
	B	callbackasm1(SB)
	MOVW	$1431, R8
	B	callbackasm1(SB)
	MOVW	$1432, R8
	B	callbackasm1(SB)
	MOVW	$1433, R8
	B	callbackasm1(SB)
	MOVW	$1434, R8
	B	callbackasm1(SB)
	MOVW	$1435, R8
	B	callbackasm1(SB)
	MOVW	$1436, R8
	B	callbackasm1(SB)
	MOVW	$1437, R8
	B	callbackasm1(SB)
	MOVW	$1438, R8
	B	callbackasm1(SB)
	MOVW	$1439, R8
	B	callbackasm1(SB)
	MOVW	$1440, R8
	B	callbackasm1(SB)
	MOVW	$1441, R8
	B	callbackasm1(SB)
	MOVW	$1442, R8
	B	callbackasm1(SB)
	MOVW	$1443, R8
	B	callbackasm1(SB)
	MOVW	$1444, R8
	B	callbackasm1(SB)
	MOVW	$1445, R8
	B	callbackasm1(SB)
	MOVW	$1446, R8
	B	callbackasm1(SB)
	MOVW	$1447, R8
	B	callbackasm1(SB)
	MOVW	$1448, R8
	B	callbackasm1(SB)
	MOVW	$1449, R8
	B	callbackasm1(SB)
	MOVW	$1450, R8
	B	callbackasm1(SB)
	MOVW	$1451, R8
	B	callbackasm1(SB)
	MOVW	$1452, R8
	B	callbackasm1(SB)
	MOVW	$1453, R8
	B	callbackasm1(SB)
	MOVW	$1454, R8
	B	callbackasm1(SB)
	MOVW	$1455, R8
	B	callbackasm1(SB)
	MOVW	$1456, R8
	B	callbackasm1(SB)
	MOVW	$1457, R8
	B	callbackasm1(SB)
	MOVW	$1458, R8
	B	callbackasm1(SB)
	MOVW	$1459, R8
	B	callbackasm1(SB)
	MOVW	$1460, R8
	B	callbackasm1(SB)
	MOVW	$1461, R8
	B	callbackasm1(SB)
	MOVW	$1462, R8
	B	callbackasm1(SB)
	MOVW	$1463, R8
	B	callbackasm1(SB)
	MOVW	$1464, R8
	B	callbackasm1(SB)
	MOVW	$1465, R8
	B	callbackasm1(SB)
	MOVW	$1466, R8
	B	callbackasm1(SB)
	MOVW	$1467, R8
	B	callbackasm1(SB)
	MOVW	$1468, R8
	B	callbackasm1(SB)
	MOVW	$1469, R8
	B	callbackasm1(SB)
	MOVW	$1470, R8
	B	callbackasm1(SB)
	MOVW	$1471, R8
	B	callbackasm1(SB)
	MOVW	$1472, R8
	B	callbackasm1(SB)
	MOVW	$1473, R8
	B	callbackasm1(SB)
	MOVW	$1474, R8
	B	callbackasm1(SB)
	MOVW	$1475, R8
	B	callbackasm1(SB)
	MOVW	$1476, R8
	B	callbackasm1(SB)
	MOVW	$1477, R8
	B	callbackasm1(SB)
	MOVW	$1478, R8
	B	callbackasm1(SB)
	MOVW	$1479, R8
	B	callbackasm1(SB)
	MOVW	$1480, R8
	B	callbackasm1(SB)
	MOVW	$1481, R8
	B	callbackasm1(SB)
	MOVW	$1482, R8
	B	callbackasm1(SB)
	MOVW	$1483, R8
	B	callbackasm1(SB)
	MOVW	$1484, R8
	B	callbackasm1(SB)
	MOVW	$1485, R8
	B	callbackasm1(SB)
	MOVW	$1486, R8
	B	callbackasm1(SB)
	MOVW	$1487, R8
	B	callbackasm1(SB)
	MOVW	$1488, R8
	B	callbackasm1(SB)
	MOVW	$1489, R8
	B	callbackasm1(SB)
	MOVW	$1490, R8
	B	callbackasm1(SB)
	MOVW	$1491, R8
	B	callbackasm1(SB)
	MOVW	$1492, R8
	B	callbackasm1(SB)
	MOVW	$1493, R8
	B	callbackasm1(SB)
	MOVW	$1494, R8
	B	callbackasm1(SB)
	MOVW	$1495, R8
	B	callbackasm1(SB)
	MOVW	$1496, R8
	B	callbackasm1(SB)
	MOVW	$1497, R8
	B	callbackasm1(SB)
	MOVW	$1498, R8
	B	callbackasm1(SB)
	MOVW	$1499, R8
	B	callbackasm1(SB)
	MOVW	$1500, R8
	B	callbackasm1(SB)
	MOVW	$1501, R8
	B	callbackasm1(SB)
	MOVW	$1502, R8
	B	callbackasm1(SB)
	MOVW	$1503, R8
	B	callbackasm1(SB)
	MOVW	$1504, R8
	B	callbackasm1(SB)
	MOVW	$1505, R8
	B	callbackasm1(SB)
	MOVW	$1506, R8
	B	callbackasm1(SB)
	MOVW	$1507, R8
	B	callbackasm1(SB)
	MOVW	$1508, R8
	B	callbackasm1(SB)
	MOVW	$1509, R8
	B	callbackasm1(SB)
	MOVW	$1510, R8
	B	callbackasm1(SB)
	MOVW	$1511, R8
	B	callbackasm1(SB)
	MOVW	$1512, R8
	B	callbackasm1(SB)
	MOVW	$1513, R8
	B	callbackasm1(SB)
	MOVW	$1514, R8
	B	callbackasm1(SB)
	MOVW	$1515, R8
	B	callbackasm1(SB)
	MOVW	$1516, R8
	B	callbackasm1(SB)
	MOVW	$1517, R8
	B	callbackasm1(SB)
	MOVW	$1518, R8
	B	callbackasm1(SB)
	MOVW	$1519, R8
	B	callbackasm1(SB)
	MOVW	$1520, R8
	B	callbackasm1(SB)
	MOVW	$1521, R8
	B	callbackasm1(SB)
	MOVW	$1522, R8
	B	callbackasm1(SB)
	MOVW	$1523, R8
	B	callbackasm1(SB)
	MOVW	$1524, R8
	B	callbackasm1(SB)
	MOVW	$1525, R8
	B	callbackasm1(SB)
	MOVW	$1526, R8
	B	callbackasm1(SB)
	MOVW	$1527, R8
	B	callbackasm1(SB)
	MOVW	$1528, R8
	B	callbackasm1(SB)
	MOVW	$1529, R8
	B	callbackasm1(SB)
	MOVW	$1530, R8
	B	callbackasm1(SB)
	MOVW	$1531, R8
	B	callbackasm1(SB)
	MOVW	$1532, R8
	B	callbackasm1(SB)
	MOVW	$1533, R8
	B	callbackasm1(SB)
	MOVW	$1534, R8
	B	callbackasm1(SB)
	MOVW	$1535, R8
	B	callbackasm1(SB)
	MOVW	$1536, R8
	B	callbackasm1(SB)
	MOVW	$1537, R8
	B	callbackasm1(SB)
	MOVW	$1538, R8
	B	callbackasm1(SB)
	MOVW	$1539, R8
	B	callbackasm1(SB)
	MOVW	$1540, R8
	B	callbackasm1(SB)
	MOVW	$1541, R8
	B	callbackasm1(SB)
	MOVW	$1542, R8
	B	callbackasm1(SB)
	MOVW	$1543, R8
	B	callbackasm1(SB)
	MOVW	$1544, R8
	B	callbackasm1(SB)
	MOVW	$1545, R8
	B	callbackasm1(SB)
	MOVW	$1546, R8
	B	callbackasm1(SB)
	MOVW	$1547, R8
	B	callbackasm1(SB)
	MOVW	$1548, R8
	B	callbackasm1(SB)
	MOVW	$1549, R8
	B	callbackasm1(SB)
	MOVW	$1550, R8
	B	callbackasm1(SB)
	MOVW	$1551, R8
	B	callbackasm1(SB)
	MOVW	$1552, R8
	B	callbackasm1(SB)
	MOVW	$1553, R8
	B	callbackasm1(SB)
	MOVW	$1554, R8
	B	callbackasm1(SB)
	MOVW	$1555, R8
	B	callbackasm1(SB)
	MOVW	$1556, R8
	B	callbackasm1(SB)
	MOVW	$1557, R8
	B	callbackasm1(SB)
	MOVW	$1558, R8
	B	callbackasm1(SB)
	MOVW	$1559, R8
	B	callbackasm1(SB)
	MOVW	$1560, R8
	B	callbackasm1(SB)
	MOVW	$1561, R8
	B	callbackasm1(SB)
	MOVW	$1562, R8
	B	callbackasm1(SB)
	MOVW	$1563, R8
	B	callbackasm1(SB)
	MOVW	$1564, R8
	B	callbackasm1(SB)
	MOVW	$1565, R8
	B	callbackasm1(SB)
	MOVW	$1566, R8
	B	callbackasm1(SB)
	MOVW	$1567, R8
	B	callbackasm1(SB)
	MOVW	$1568, R8
	B	callbackasm1(SB)
	MOVW	$1569, R8
	B	callbackasm1(SB)
	MOVW	$1570, R8
	B	callbackasm1(SB)
	MOVW	$1571, R8
	B	callbackasm1(SB)
	MOVW	$1572, R8
	B	callbackasm1(SB)
	MOVW	$1573, R8
	B	callbackasm1(SB)
	MOVW	$1574, R8
	B	callbackasm1(SB)
	MOVW	$1575, R8
	B	callbackasm1(SB)
	MOVW	$1576, R8
	B	callbackasm1(SB)
	MOVW	$1577, R8
	B	callbackasm1(SB)
	MOVW	$1578, R8
	B	callbackasm1(SB)
	MOVW	$1579, R8
	B	callbackasm1(SB)
	MOVW	$1580, R8
	B	callbackasm1(SB)
	MOVW	$1581, R8
	B	callbackasm1(SB)
	MOVW	$1582, R8
	B	callbackasm1(SB)
	MOVW	$1583, R8
	B	callbackasm1(SB)
	MOVW	$1584, R8
	B	callbackasm1(SB)
	MOVW	$1585, R8
	B	callbackasm1(SB)
	MOVW	$1586, R8
	B	callbackasm1(SB)
	MOVW	$1587, R8
	B	callbackasm1(SB)
	MOVW	$1588, R8
	B	callbackasm1(SB)
	MOVW	$1589, R8
	B	callbackasm1(SB)
	MOVW	$1590, R8
	B	callbackasm1(SB)
	MOVW	$1591, R8
	B	callbackasm1(SB)
	MOVW	$1592, R8
	B	callbackasm1(SB)
	MOVW	$1593, R8
	B	callbackasm1(SB)
	MOVW	$1594, R8
	B	callbackasm1(SB)
	MOVW	$1595, R8
	B	callbackasm1(SB)
	MOVW	$1596, R8
	B	callbackasm1(SB)
	MOVW	$1597, R8
	B	callbackasm1(SB)
	MOVW	$1598, R8
	B	callbackasm1(SB)
	MOVW	$1599, R8
	B	callbackasm1(SB)
	MOVW	$1600, R8
	B	callbackasm1(SB)
	MOVW	$1601, R8
	B	callbackasm1(SB)
	MOVW	$1602, R8
	B	callbackasm1(SB)
	MOVW	$1603, R8
	B	callbackasm1(SB)
	MOVW	$1604, R8
	B	callbackasm1(SB)
	MOVW	$1605, R8
	B	callbackasm1(SB)
	MOVW	$1606, R8
	B	callbackasm1(SB)
	MOVW	$1607, R8
	B	callbackasm1(SB)
	MOVW	$1608, R8
	B	callbackasm1(SB)
	MOVW	$1609, R8
	B	callbackasm1(SB)
	MOVW	$1610, R8
	B	callbackasm1(SB)
	MOVW	$1611, R8
	B	callbackasm1(SB)
	MOVW	$1612, R8
	B	callbackasm1(SB)
	MOVW	$1613, R8
	B	callbackasm1(SB)
	MOVW	$1614, R8
	B	callbackasm1(SB)
	MOVW	$1615, R8
	B	callbackasm1(SB)
	MOVW	$1616, R8
	B	callbackasm1(SB)
	MOVW	$1617, R8
	B	callbackasm1(SB)
	MOVW	$1618, R8
	B	callbackasm1(SB)
	MOVW	$1619, R8
	B	callbackasm1(SB)
	MOVW	$1620, R8
	B	callbackasm1(SB)
	MOVW	$1621, R8
	B	callbackasm1(SB)
	MOVW	$1622, R8
	B	callbackasm1(SB)
	MOVW	$1623, R8
	B	callbackasm1(SB)
	MOVW	$1624, R8
	B	callbackasm1(SB)
	MOVW	$1625, R8
	B	callbackasm1(SB)
	MOVW	$1626, R8
	B	callbackasm1(SB)
	MOVW	$1627, R8
	B	callbackasm1(SB)
	MOVW	$1628, R8
	B	callbackasm1(SB)
	MOVW	$1629, R8
	B	callbackasm1(SB)
	MOVW	$1630, R8
	B	callbackasm1(SB)
	MOVW	$1631, R8
	B	callbackasm1(SB)
	MOVW	$1632, R8
	B	callbackasm1(SB)
	MOVW	$1633, R8
	B	callbackasm1(SB)
	MOVW	$1634, R8
	B	callbackasm1(SB)
	MOVW	$1635, R8
	B	callbackasm1(SB)
	MOVW	$1636, R8
	B	callbackasm1(SB)
	MOVW	$1637, R8
	B	callbackasm1(SB)
	MOVW	$1638, R8
	B	callbackasm1(SB)
	MOVW	$1639, R8
	B	callbackasm1(SB)
	MOVW	$1640, R8
	B	callbackasm1(SB)
	MOVW	$1641, R8
	B	callbackasm1(SB)
	MOVW	$1642, R8
	B	callbackasm1(SB)
	MOVW	$1643, R8
	B	callbackasm1(SB)
	MOVW	$1644, R8
	B	callbackasm1(SB)
	MOVW	$1645, R8
	B	callbackasm1(SB)
	MOVW	$1646, R8
	B	callbackasm1(SB)
	MOVW	$1647, R8
	B	callbackasm1(SB)
	MOVW	$1648, R8
	B	callbackasm1(SB)
	MOVW	$1649, R8
	B	callbackasm1(SB)
	MOVW	$1650, R8
	B	callbackasm1(SB)
	MOVW	$1651, R8
	B	callbackasm1(SB)
	MOVW	$1652, R8
	B	callbackasm1(SB)
	MOVW	$1653, R8
	B	callbackasm1(SB)
	MOVW	$1654, R8
	B	callbackasm1(SB)
	MOVW	$1655, R8
	B	callbackasm1(SB)
	MOVW	$1656, R8
	B	callbackasm1(SB)
	MOVW	$1657, R8
	B	callbackasm1(SB)
	MOVW	$1658, R8
	B	callbackasm1(SB)
	MOVW	$1659, R8
	B	callbackasm1(SB)
	MOVW	$1660, R8
	B	callbackasm1(SB)
	MOVW	$1661, R8
	B	callbackasm1(SB)
	MOVW	$1662, R8
	B	callbackasm1(SB)
	MOVW	$1663, R8
	B	callbackasm1(SB)
	MOVW	$1664, R8
	B	callbackasm1(SB)
	MOVW	$1665, R8
	B	callbackasm1(SB)
	MOVW	$1666, R8
	B	callbackasm1(SB)
	MOVW	$1667, R8
	B	callbackasm1(SB)
	MOVW	$1668, R8
	B	callbackasm1(SB)
	MOVW	$1669, R8
	B	callbackasm1(SB)
	MOVW	$1670, R8
	B	callbackasm1(SB)
	MOVW	$1671, R8
	B	callbackasm1(SB)
	MOVW	$1672, R8
	B	callbackasm1(SB)
	MOVW	$1673, R8
	B	callbackasm1(SB)
	MOVW	$1674, R8
	B	callbackasm1(SB)
	MOVW	$1675, R8
	B	callbackasm1(SB)
	MOVW	$1676, R8
	B	callbackasm1(SB)
	MOVW	$1677, R8
	B	callbackasm1(SB)
	MOVW	$1678, R8
	B	callbackasm1(SB)
	MOVW	$1679, R8
	B	callbackasm1(SB)
	MOVW	$1680, R8
	B	callbackasm1(SB)
	MOVW	$1681, R8
	B	callbackasm1(SB)
	MOVW	$1682, R8
	B	callbackasm1(SB)
	MOVW	$1683, R8
	B	callbackasm1(SB)
	MOVW	$1684, R8
	B	callbackasm1(SB)
	MOVW	$1685, R8
	B	callbackasm1(SB)
	MOVW	$1686, R8
	B	callbackasm1(SB)
	MOVW	$1687, R8
	B	callbackasm1(SB)
	MOVW	$1688, R8
	B	callbackasm1(SB)
	MOVW	$1689, R8
	B	callbackasm1(SB)
	MOVW	$1690, R8
	B	callbackasm1(SB)
	MOVW	$1691, R8
	B	callbackasm1(SB)
	MOVW	$1692, R8
	B	callbackasm1(SB)
	MOVW	$1693, R8
	B	callbackasm1(SB)
	MOVW	$1694, R8
	B	callbackasm1(SB)
	MOVW	$1695, R8
	B	callbackasm1(SB)
	MOVW	$1696, R8
	B	callbackasm1(SB)
	MOVW	$1697, R8
	B	callbackasm1(SB)
	MOVW	$1698, R8
	B	callbackasm1(SB)
	MOVW	$1699, R8
	B	callbackasm1(SB)
	MOVW	$1700, R8
	B	callbackasm1(SB)
	MOVW	$1701, R8
	B	callbackasm1(SB)
	MOVW	$1702, R8
	B	callbackasm1(SB)
	MOVW	$1703, R8
	B	callbackasm1(SB)
	MOVW	$1704, R8
	B	callbackasm1(SB)
	MOVW	$1705, R8
	B	callbackasm1(SB)
	MOVW	$1706, R8
	B	callbackasm1(SB)
	MOVW	$1707, R8
	B	callbackasm1(SB)
	MOVW	$1708, R8
	B	callbackasm1(SB)
	MOVW	$1709, R8
	B	callbackasm1(SB)
	MOVW	$1710, R8
	B	callbackasm1(SB)
	MOVW	$1711, R8
	B	callbackasm1(SB)
	MOVW	$1712, R8
	B	callbackasm1(SB)
	MOVW	$1713, R8
	B	callbackasm1(SB)
	MOVW	$1714, R8
	B	callbackasm1(SB)
	MOVW	$1715, R8
	B	callbackasm1(SB)
	MOVW	$1716, R8
	B	callbackasm1(SB)
	MOVW	$1717, R8
	B	callbackasm1(SB)
	MOVW	$1718, R8
	B	callbackasm1(SB)
	MOVW	$1719, R8
	B	callbackasm1(SB)
	MOVW	$1720, R8
	B	callbackasm1(SB)
	MOVW	$1721, R8
	B	callbackasm1(SB)
	MOVW	$1722, R8
	B	callbackasm1(SB)
	MOVW	$1723, R8
	B	callbackasm1(SB)
	MOVW	$1724, R8
	B	callbackasm1(SB)
	MOVW	$1725, R8
	B	callbackasm1(SB)
	MOVW	$1726, R8
	B	callbackasm1(SB)
	MOVW	$1727, R8
	B	callbackasm1(SB)
	MOVW	$1728, R8
	B	callbackasm1(SB)
	MOVW	$1729, R8
	B	callbackasm1(SB)
	MOVW	$1730, R8
	B	callbackasm1(SB)
	MOVW	$1731, R8
	B	callbackasm1(SB)
	MOVW	$1732, R8
	B	callbackasm1(SB)
	MOVW	$1733, R8
	B	callbackasm1(SB)
	MOVW	$1734, R8
	B	callbackasm1(SB)
	MOVW	$1735, R8
	B	callbackasm1(SB)
	MOVW	$1736, R8
	B	callbackasm1(SB)
	MOVW	$1737, R8
	B	callbackasm1(SB)
	MOVW	$1738, R8
	B	callbackasm1(SB)
	MOVW	$1739, R8
	B	callbackasm1(SB)
	MOVW	$1740, R8
	B	callbackasm1(SB)
	MOVW	$1741, R8
	B	callbackasm1(SB)
	MOVW	$1742, R8
	B	callbackasm1(SB)
	MOVW	$1743, R8
	B	callbackasm1(SB)
	MOVW	$1744, R8
	B	callbackasm1(SB)
	MOVW	$1745, R8
	B	callbackasm1(SB)
	MOVW	$1746, R8
	B	callbackasm1(SB)
	MOVW	$1747, R8
	B	callbackasm1(SB)
	MOVW	$1748, R8
	B	callbackasm1(SB)
	MOVW	$1749, R8
	B	callbackasm1(SB)
	MOVW	$1750, R8
	B	callbackasm1(SB)
	MOVW	$1751, R8
	B	callbackasm1(SB)
	MOVW	$1752, R8
	B	callbackasm1(SB)
	MOVW	$1753, R8
	B	callbackasm1(SB)
	MOVW	$1754, R8
	B	callbackasm1(SB)
	MOVW	$1755, R8
	B	callbackasm1(SB)
	MOVW	$1756, R8
	B	callbackasm1(SB)
	MOVW	$1757, R8
	B	callbackasm1(SB)
	MOVW	$1758, R8
	B	callbackasm1(SB)
	MOVW	$1759, R8
	B	callbackasm1(SB)
	MOVW	$1760, R8
	B	callbackasm1(SB)
	MOVW	$1761, R8
	B	callbackasm1(SB)
	MOVW	$1762, R8
	B	callbackasm1(SB)
	MOVW	$1763, R8
	B	callbackasm1(SB)
	MOVW	$1764, R8
	B	callbackasm1(SB)
	MOVW	$1765, R8
	B	callbackasm1(SB)
	MOVW	$1766, R8
	B	callbackasm1(SB)
	MOVW	$1767, R8
	B	callbackasm1(SB)
	MOVW	$1768, R8
	B	callbackasm1(SB)
	MOVW	$1769, R8
	B	callbackasm1(SB)
	MOVW	$1770, R8
	B	callbackasm1(SB)
	MOVW	$1771, R8
	B	callbackasm1(SB)
	MOVW	$1772, R8
	B	callbackasm1(SB)
	MOVW	$1773, R8
	B	callbackasm1(SB)
	MOVW	$1774, R8
	B	callbackasm1(SB)
	MOVW	$1775, R8
	B	callbackasm1(SB)
	MOVW	$1776, R8
	B	callbackasm1(SB)
	MOVW	$1777, R8
	B	callbackasm1(SB)
	MOVW	$1778, R8
	B	callbackasm1(SB)
	MOVW	$1779, R8
	B	callbackasm1(SB)
	MOVW	$1780, R8
	B	callbackasm1(SB)
	MOVW	$1781, R8
	B	callbackasm1(SB)
	MOVW	$1782, R8
	B	callbackasm1(SB)
	MOVW	$1783, R8
	B	callbackasm1(SB)
	MOVW	$1784, R8
	B	callbackasm1(SB)
	MOVW	$1785, R8
	B	callbackasm1(SB)
	MOVW	$1786, R8
	B	callbackasm1(SB)
	MOVW	$1787, R8
	B	callbackasm1(SB)
	MOVW	$1788, R8
	B	callbackasm1(SB)
	MOVW	$1789, R8
	B	callbackasm1(SB)
	MOVW	$1790, R8
	B	callbackasm1(SB)
	MOVW	$1791, R8
	B	callbackasm1(SB)
	MOVW	$1792, R8
	B	callbackasm1(SB)
	MOVW	$1793, R8
	B	callbackasm1(SB)
	MOVW	$1794, R8
	B	callbackasm1(SB)
	MOVW	$1795, R8
	B	callbackasm1(SB)
	MOVW	$1796, R8
	B	callbackasm1(SB)
	MOVW	$1797, R8
	B	callbackasm1(SB)
	MOVW	$1798, R8
	B	callbackasm1(SB)
	MOVW	$1799, R8
	B	callbackasm1(SB)
	MOVW	$1800, R8
	B	callbackasm1(SB)
	MOVW	$1801, R8
	B	callbackasm1(SB)
	MOVW	$1802, R8
	B	callbackasm1(SB)
	MOVW	$1803, R8
	B	callbackasm1(SB)
	MOVW	$1804, R8
	B	callbackasm1(SB)
	MOVW	$1805, R8
	B	callbackasm1(SB)
	MOVW	$1806, R8
	B	callbackasm1(SB)
	MOVW	$1807, R8
	B	callbackasm1(SB)
	MOVW	$1808, R8
	B	callbackasm1(SB)
	MOVW	$1809, R8
	B	callbackasm1(SB)
	MOVW	$1810, R8
	B	callbackasm1(SB)
	MOVW	$1811, R8
	B	callbackasm1(SB)
	MOVW	$1812, R8
	B	callbackasm1(SB)
	MOVW	$1813, R8
	B	callbackasm1(SB)
	MOVW	$1814, R8
	B	callbackasm1(SB)
	MOVW	$1815, R8
	B	callbackasm1(SB)
	MOVW	$1816, R8
	B	callbackasm1(SB)
	MOVW	$1817, R8
	B	callbackasm1(SB)
	MOVW	$1818, R8
	B	callbackasm1(SB)
	MOVW	$1819, R8
	B	callbackasm1(SB)
	MOVW	$1820, R8
	B	callbackasm1(SB)
	MOVW	$1821, R8
	B	callbackasm1(SB)
	MOVW	$1822, R8
	B	callbackasm1(SB)
	MOVW	$1823, R8
	B	callbackasm1(SB)
	MOVW	$1824, R8
	B	callbackasm1(SB)
	MOVW	$1825, R8
	B	callbackasm1(SB)
	MOVW	$1826, R8
	B	callbackasm1(SB)
	MOVW	$1827, R8
	B	callbackasm1(SB)
	MOVW	$1828, R8
	B	callbackasm1(SB)
	MOVW	$1829, R8
	B	callbackasm1(SB)
	MOVW	$1830, R8
	B	callbackasm1(SB)
	MOVW	$1831, R8
	B	callbackasm1(SB)
	MOVW	$1832, R8
	B	callbackasm1(SB)
	MOVW	$1833, R8
	B	callbackasm1(SB)
	MOVW	$1834, R8
	B	callbackasm1(SB)
	MOVW	$1835, R8
	B	callbackasm1(SB)
	MOVW	$1836, R8
	B	callbackasm1(SB)
	MOVW	$1837, R8
	B	callbackasm1(SB)
	MOVW	$1838, R8
	B	callbackasm1(SB)
	MOVW	$1839, R8
	B	callbackasm1(SB)
	MOVW	$1840, R8
	B	callbackasm1(SB)
	MOVW	$1841, R8
	B	callbackasm1(SB)
	MOVW	$1842, R8
	B	callbackasm1(SB)
	MOVW	$1843, R8
	B	callbackasm1(SB)
	MOVW	$1844, R8
	B	callbackasm1(SB)
	MOVW	$1845, R8
	B	callbackasm1(SB)
	MOVW	$1846, R8
	B	callbackasm1(SB)
	MOVW	$1847, R8
	B	callbackasm1(SB)
	MOVW	$1848, R8
	B	callbackasm1(SB)
	MOVW	$1849, R8
	B	callbackasm1(SB)
	MOVW	$1850, R8
	B	callbackasm1(SB)
	MOVW	$1851, R8
	B	callbackasm1(SB)
	MOVW	$1852, R8
	B	callbackasm1(SB)
	MOVW	$1853, R8
	B	callbackasm1(SB)
	MOVW	$1854, R8
	B	callbackasm1(SB)
	MOVW	$1855, R8
	B	callbackasm1(SB)
	MOVW	$1856, R8
	B	callbackasm1(SB)
	MOVW	$1857, R8
	B	callbackasm1(SB)
	MOVW	$1858, R8
	B	callbackasm1(SB)
	MOVW	$1859, R8
	B	callbackasm1(SB)
	MOVW	$1860, R8
	B	callbackasm1(SB)
	MOVW	$1861, R8
	B	callbackasm1(SB)
	MOVW	$1862, R8
	B	callbackasm1(SB)
	MOVW	$1863, R8
	B	callbackasm1(SB)
	MOVW	$1864, R8
	B	callbackasm1(SB)
	MOVW	$1865, R8
	B	callbackasm1(SB)
	MOVW	$1866, R8
	B	callbackasm1(SB)
	MOVW	$1867, R8
	B	callbackasm1(SB)
	MOVW	$1868, R8
	B	callbackasm1(SB)
	MOVW	$1869, R8
	B	callbackasm1(SB)
	MOVW	$1870, R8
	B	callbackasm1(SB)
	MOVW	$1871, R8
	B	callbackasm1(SB)
	MOVW	$1872, R8
	B	callbackasm1(SB)
	MOVW	$1873, R8
	B	callbackasm1(SB)
	MOVW	$1874, R8
	B	callbackasm1(SB)
	MOVW	$1875, R8
	B	callbackasm1(SB)
	MOVW	$1876, R8
	B	callbackasm1(SB)
	MOVW	$1877, R8
	B	callbackasm1(SB)
	MOVW	$1878, R8
	B	callbackasm1(SB)
	MOVW	$1879, R8
	B	callbackasm1(SB)
	MOVW	$1880, R8
	B	callbackasm1(SB)
	MOVW	$1881, R8
	B	callbackasm1(SB)
	MOVW	$1882, R8
	B	callbackasm1(SB)
	MOVW	$1883, R8
	B	callbackasm1(SB)
	MOVW	$1884, R8
	B	callbackasm1(SB)
	MOVW	$1885, R8
	B	callbackasm1(SB)
	MOVW	$1886, R8
	B	callbackasm1(SB)
	MOVW	$1887, R8
	B	callbackasm1(SB)
	MOVW	$1888, R8
	B	callbackasm1(SB)
	MOVW	$1889, R8
	B	callbackasm1(SB)
	MOVW	$1890, R8
	B	callbackasm1(SB)
	MOVW	$1891, R8
	B	callbackasm1(SB)
	MOVW	$1892, R8
	B	callbackasm1(SB)
	MOVW	$1893, R8
	B	callbackasm1(SB)
	MOVW	$1894, R8
	B	callbackasm1(SB)
	MOVW	$1895, R8
	B	callbackasm1(SB)
	MOVW	$1896, R8
	B	callbackasm1(SB)
	MOVW	$1897, R8
	B	callbackasm1(SB)
	MOVW	$1898, R8
	B	callbackasm1(SB)
	MOVW	$1899, R8
	B	callbackasm1(SB)
	MOVW	$1900, R8
	B	callbackasm1(SB)
	MOVW	$1901, R8
	B	callbackasm1(SB)
	MOVW	$1902, R8
	B	callbackasm1(SB)
	MOVW	$1903, R8
	B	callbackasm1(SB)
	MOVW	$1904, R8
	B	callbackasm1(SB)
	MOVW	$1905, R8
	B	callbackasm1(SB)
	MOVW	$1906, R8
	B	callbackasm1(SB)
	MOVW	$1907, R8
	B	callbackasm1(SB)
	MOVW	$1908, R8
	B	callbackasm1(SB)
	MOVW	$1909, R8
	B	callbackasm1(SB)
	MOVW	$1910, R8
	B	callbackasm1(SB)
	MOVW	$1911, R8
	B	callbackasm1(SB)
	MOVW	$1912, R8
	B	callbackasm1(SB)
	MOVW	$1913, R8
	B	callbackasm1(SB)
	MOVW	$1914, R8
	B	callbackasm1(SB)
	MOVW	$1915, R8
	B	callbackasm1(SB)
	MOVW	$1916, R8
	B	callbackasm1(SB)
	MOVW	$1917, R8
	B	callbackasm1(SB)
	MOVW	$1918, R8
	B	callbackasm1(SB)
	MOVW	$1919, R8
	B	callbackasm1(SB)
	MOVW	$1920, R8
	B	callbackasm1(SB)
	MOVW	$1921, R8
	B	callbackasm1(SB)
	MOVW	$1922, R8
	B	callbackasm1(SB)
	MOVW	$1923, R8
	B	callbackasm1(SB)
	MOVW	$1924, R8
	B	callbackasm1(SB)
	MOVW	$1925, R8
	B	callbackasm1(SB)
	MOVW	$1926, R8
	B	callbackasm1(SB)
	MOVW	$1927, R8
	B	callbackasm1(SB)
	MOVW	$1928, R8
	B	callbackasm1(SB)
	MOVW	$1929, R8
	B	callbackasm1(SB)
	MOVW	$1930, R8
	B	callbackasm1(SB)
	MOVW	$1931, R8
	B	callbackasm1(SB)
	MOVW	$1932, R8
	B	callbackasm1(SB)
	MOVW	$1933, R8
	B	callbackasm1(SB)
	MOVW	$1934, R8
	B	callbackasm1(SB)
	MOVW	$1935, R8
	B	callbackasm1(SB)
	MOVW	$1936, R8
	B	callbackasm1(SB)
	MOVW	$1937, R8
	B	callbackasm1(SB)
	MOVW	$1938, R8
	B	callbackasm1(SB)
	MOVW	$1939, R8
	B	callbackasm1(SB)
	MOVW	$1940, R8
	B	callbackasm1(SB)
	MOVW	$1941, R8
	B	callbackasm1(SB)
	MOVW	$1942, R8
	B	callbackasm1(SB)
	MOVW	$1943, R8
	B	callbackasm1(SB)
	MOVW	$1944, R8
	B	callbackasm1(SB)
	MOVW	$1945, R8
	B	callbackasm1(SB)
	MOVW	$1946, R8
	B	callbackasm1(SB)
	MOVW	$1947, R8
	B	callbackasm1(SB)
	MOVW	$1948, R8
	B	callbackasm1(SB)
	MOVW	$1949, R8
	B	callbackasm1(SB)
	MOVW	$1950, R8
	B	callbackasm1(SB)
	MOVW	$1951, R8
	B	callbackasm1(SB)
	MOVW	$1952, R8
	B	callbackasm1(SB)
	MOVW	$1953, R8
	B	callbackasm1(SB)
	MOVW	$1954, R8
	B	callbackasm1(SB)
	MOVW	$1955, R8
	B	callbackasm1(SB)
	MOVW	$1956, R8
	B	callbackasm1(SB)
	MOVW	$1957, R8
	B	callbackasm1(SB)
	MOVW	$1958, R8
	B	callbackasm1(SB)
	MOVW	$1959, R8
	B	callbackasm1(SB)
	MOVW	$1960, R8
	B	callbackasm1(SB)
	MOVW	$1961, R8
	B	callbackasm1(SB)
	MOVW	$1962, R8
	B	callbackasm1(SB)
	MOVW	$1963, R8
	B	callbackasm1(SB)
	MOVW	$1964, R8
	B	callbackasm1(SB)
	MOVW	$1965, R8
	B	callbackasm1(SB)
	MOVW	$1966, R8
	B	callbackasm1(SB)
	MOVW	$1967, R8
	B	callbackasm1(SB)
	MOVW	$1968, R8
	B	callbackasm1(SB)
	MOVW	$1969, R8
	B	callbackasm1(SB)
	MOVW	$1970, R8
	B	callbackasm1(SB)
	MOVW	$1971, R8
	B	callbackasm1(SB)
	MOVW	$1972, R8
	B	callbackasm1(SB)
	MOVW	$1973, R8
	B	callbackasm1(SB)
	MOVW	$1974, R8
	B	callbackasm1(SB)
	MOVW	$1975, R8
	B	callbackasm1(SB)
	MOVW	$1976, R8
	B	callbackasm1(SB)
	MOVW	$1977, R8
	B	callbackasm1(SB)
	MOVW	$1978, R8
	B	callbackasm1(SB)
	MOVW	$1979, R8
	B	callbackasm1(SB)
	MOVW	$1980, R8
	B	callbackasm1(SB)
	MOVW	$1981, R8
	B	callbackasm1(SB)
	MOVW	$1982, R8
	B	callbackasm1(SB)
	MOVW	$1983, R8
	B	callbackasm1(SB)
	MOVW	$1984, R8
	B	callbackasm1(SB)
	MOVW	$1985, R8
	B	callbackasm1(SB)
	MOVW	$1986, R8
	B	callbackasm1(SB)
	MOVW	$1987, R8
	B	callbackasm1(SB)
	MOVW	$1988, R8
	B	callbackasm1(SB)
	MOVW	$1989, R8
	B	callbackasm1(SB)
	MOVW	$1990, R8
	B	callbackasm1(SB)
	MOVW	$1991, R8
	B	callbackasm1(SB)
	MOVW	$1992, R8
	B	callbackasm1(SB)
	MOVW	$1993, R8
	B	callbackasm1(SB)
	MOVW	$1994, R8
	B	callbackasm1(SB)
	MOVW	$1995, R8
	B	callbackasm1(SB)
	MOVW	$1996, R8
	B	callbackasm1(SB)
	MOVW	$1997, R8
	B	callbackasm1(SB)
	MOVW	$1998, R8
	B	callbackasm1(SB)
	MOVW	$1999, R8
	B	callbackasm1(SB)
