package main

import (
	"log"

	"github.com/ebitengine/purego/objc"
)

func init() {
	var p *objc.Protocol

	p = objc.AllocateProtocol("NSAccessibility")
	if p != nil {
		p.AddMethodDescription(objc.RegisterName("accessibilityCellForColumn:row:"), "@32@0:8q16q24", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityNumberOfCharacters"), "q16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("isAccessibilityProtectedContent"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityMinimizeButton:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityTitleUIElement:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilitySelectedTextRanges"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("isAccessibilitySelectorAllowed:"), "B24@0:8:16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityDisclosedByRow:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityOverflowButton:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityVisibleColumns:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityActivationPoint"), "{CGPoint=dd}16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityAllowedValues"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityApplicationFocusedUIElement"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityAttributedStringForRange:"), "@32@0:8{_NSRange=QQ}16", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityAttributedUserInputLabels"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityCancelButton"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityChildren"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityChildrenInNavigationOrder"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityClearButton"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityCloseButton"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityColumnCount"), "q16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityColumnHeaderUIElements"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityColumnIndexRange"), "{_NSRange=QQ}16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityColumnTitles"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityColumns"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityContents"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityCriticalValue"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityCustomActions"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityCustomRotors"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityDecrementButton"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityDefaultButton"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityDisclosedByRow"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityDisclosedRows"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityDisclosureLevel"), "q16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityDocument"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityExtrasMenuBar"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityFilename"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityFocusedWindow"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityFrame"), "{CGRect={CGPoint=dd}{CGSize=dd}}16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityFrameForRange:"), "{CGRect={CGPoint=dd}{CGSize=dd}}32@0:8{_NSRange=QQ}16", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityFullScreenButton"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityGrowArea"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityHandles"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityHeader"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityHelp"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityHorizontalScrollBar"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityHorizontalUnitDescription"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityHorizontalUnits"), "q16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityIdentifier"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityIncrementButton"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityIndex"), "q16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityInsertionPointLineNumber"), "q16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityLabel"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityLabelUIElements"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityLabelValue"), "f16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityLayoutPointForScreenPoint:"), "{CGPoint=dd}32@0:8{CGPoint=dd}16", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityLayoutSizeForScreenSize:"), "{CGSize=dd}32@0:8{CGSize=dd}16", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityLineForIndex:"), "q24@0:8q16", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityLinkedUIElements"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityMainWindow"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityMarkerGroupUIElement"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityMarkerTypeDescription"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityMarkerUIElements"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityMarkerValues"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityMaxValue"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityMenuBar"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityMinValue"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityMinimizeButton"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityNextContents"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityOrientation"), "q16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityOverflowButton"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityParent"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityPerformCancel"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityPerformConfirm"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityPerformDecrement"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityPerformDelete"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityPerformIncrement"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityPerformPick"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityPerformPress"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityPerformRaise"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityPerformShowAlternateUI"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityPerformShowDefaultUI"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityPerformShowMenu"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityPlaceholderValue"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityPreviousContents"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityProxy"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityRTFForRange:"), "@32@0:8{_NSRange=QQ}16", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityRangeForIndex:"), "{_NSRange=QQ}24@0:8q16", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityRangeForLine:"), "{_NSRange=QQ}24@0:8q16", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityRangeForPosition:"), "{_NSRange=QQ}32@0:8{CGPoint=dd}16", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityRole"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityRoleDescription"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityRowCount"), "q16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityRowHeaderUIElements"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityRowIndexRange"), "{_NSRange=QQ}16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityRows"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityRulerMarkerType"), "q16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityScreenPointForLayoutPoint:"), "{CGPoint=dd}32@0:8{CGPoint=dd}16", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityScreenSizeForLayoutSize:"), "{CGSize=dd}32@0:8{CGSize=dd}16", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilitySearchButton"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilitySearchMenu"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilitySelectedCells"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilitySelectedChildren"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilitySelectedColumns"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilitySelectedRows"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilitySelectedText"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilitySelectedTextRange"), "{_NSRange=QQ}16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityServesAsTitleForUIElements"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilitySharedCharacterRange"), "{_NSRange=QQ}16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilitySharedFocusElements"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilitySharedTextUIElements"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityShownMenu"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilitySortDirection"), "q16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilitySplitters"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityStringForRange:"), "@32@0:8{_NSRange=QQ}16", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityStyleRangeForIndex:"), "{_NSRange=QQ}24@0:8q16", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilitySubrole"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityTabs"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityTitle"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityTitleUIElement"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityToolbarButton"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityTopLevelUIElement"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityURL"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityUnitDescription"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityUnits"), "q16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityUserInputLabels"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityValue"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityValueDescription"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityVerticalScrollBar"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityVerticalUnitDescription"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityVerticalUnits"), "q16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityVisibleCells"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityVisibleCharacterRange"), "{_NSRange=QQ}16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityVisibleChildren"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityVisibleColumns"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityVisibleRows"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityWarningValue"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityWindow"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityWindows"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("accessibilityZoomButton"), "@16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("isAccessibilityAlternateUIVisible"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("isAccessibilityDisclosed"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("isAccessibilityEdited"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("isAccessibilityElement"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("isAccessibilityEnabled"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("isAccessibilityExpanded"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("isAccessibilityFocused"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("isAccessibilityFrontmost"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("isAccessibilityHidden"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("isAccessibilityMain"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("isAccessibilityMinimized"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("isAccessibilityModal"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("isAccessibilityOrderedByRow"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("isAccessibilityRequired"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("isAccessibilitySelected"), "B16@0:8", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityActivationPoint:"), "v32@0:8{CGPoint=dd}16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityAllowedValues:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityAlternateUIVisible:"), "v20@0:8B16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityApplicationFocusedUIElement:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityAttributedUserInputLabels:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityCancelButton:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityChildren:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityChildrenInNavigationOrder:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityClearButton:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityCloseButton:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityColumnCount:"), "v24@0:8q16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityColumnHeaderUIElements:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityColumnIndexRange:"), "v32@0:8{_NSRange=QQ}16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityColumnTitles:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityColumns:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityContents:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityCriticalValue:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityCustomActions:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityCustomRotors:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityDecrementButton:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityDefaultButton:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityDisclosed:"), "v20@0:8B16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityDisclosedRows:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityDisclosureLevel:"), "v24@0:8q16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityDocument:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityEdited:"), "v20@0:8B16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityElement:"), "v20@0:8B16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityEnabled:"), "v20@0:8B16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityExpanded:"), "v20@0:8B16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityExtrasMenuBar:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityFilename:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityFocused:"), "v20@0:8B16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityFocusedWindow:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityFrame:"), "v48@0:8{CGRect={CGPoint=dd}{CGSize=dd}}16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityFrontmost:"), "v20@0:8B16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityFullScreenButton:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityGrowArea:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityHandles:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityHeader:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityHelp:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityHidden:"), "v20@0:8B16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityHorizontalScrollBar:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityHorizontalUnitDescription:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityHorizontalUnits:"), "v24@0:8q16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityIdentifier:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityIncrementButton:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityIndex:"), "v24@0:8q16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityInsertionPointLineNumber:"), "v24@0:8q16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityLabel:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityLabelUIElements:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityLabelValue:"), "v20@0:8f16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityLinkedUIElements:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityMain:"), "v20@0:8B16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityMainWindow:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityMarkerGroupUIElement:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityMarkerTypeDescription:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityMarkerUIElements:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityMarkerValues:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityMaxValue:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityMenuBar:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityMinValue:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityMinimized:"), "v20@0:8B16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityModal:"), "v20@0:8B16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityNextContents:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityNumberOfCharacters:"), "v24@0:8q16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityOrderedByRow:"), "v20@0:8B16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityOrientation:"), "v24@0:8q16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityParent:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityPlaceholderValue:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityPreviousContents:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityProtectedContent:"), "v20@0:8B16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityProxy:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityRequired:"), "v20@0:8B16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityRole:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityRoleDescription:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityRowCount:"), "v24@0:8q16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityRowHeaderUIElements:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityRowIndexRange:"), "v32@0:8{_NSRange=QQ}16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityRows:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityRulerMarkerType:"), "v24@0:8q16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilitySearchButton:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilitySearchMenu:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilitySelected:"), "v20@0:8B16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilitySelectedCells:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilitySelectedChildren:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilitySelectedColumns:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilitySelectedRows:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilitySelectedText:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilitySelectedTextRange:"), "v32@0:8{_NSRange=QQ}16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilitySelectedTextRanges:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityServesAsTitleForUIElements:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilitySharedCharacterRange:"), "v32@0:8{_NSRange=QQ}16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilitySharedFocusElements:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilitySharedTextUIElements:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityShownMenu:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilitySortDirection:"), "v24@0:8q16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilitySplitters:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilitySubrole:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityTabs:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityTitle:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityToolbarButton:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityTopLevelUIElement:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityURL:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityUnitDescription:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityUnits:"), "v24@0:8q16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityUserInputLabels:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityValue:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityValueDescription:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityVerticalScrollBar:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityVerticalUnitDescription:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityVerticalUnits:"), "v24@0:8q16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityVisibleCells:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityVisibleCharacterRange:"), "v32@0:8{_NSRange=QQ}16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityVisibleChildren:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityVisibleRows:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityWarningValue:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityWindow:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityWindows:"), "v24@0:8@16", true, true)
		p.AddMethodDescription(objc.RegisterName("setAccessibilityZoomButton:"), "v24@0:8@16", true, true)
		var adoptedProtocol *objc.Protocol
		adoptedProtocol = objc.GetProtocol("NSObject")
		if adoptedProtocol == nil {
			log.Fatalln("protocol 'NSObject' does not exist")
		}
		p.AddProtocol(adoptedProtocol)
		p.AddProperty("accessibilityElement", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("B\x00")[0]}, {Name: &[]byte("G\x00")[0], Value: &[]byte("isAccessibilityElement\x00")[0]}}, true, true)
		p.AddProperty("accessibilityFrame", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("{CGRect={CGPoint=dd}{CGSize=dd}}\x00")[0]}}, true, true)
		p.AddProperty("accessibilityFocused", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("B\x00")[0]}, {Name: &[]byte("G\x00")[0], Value: &[]byte("isAccessibilityFocused\x00")[0]}}, true, true)
		p.AddProperty("accessibilityActivationPoint", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("{CGPoint=dd}\x00")[0]}}, true, true)
		p.AddProperty("accessibilityTopLevelUIElement", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("W\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityURL", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSURL\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityValue", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityValueDescription", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSString\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityVisibleChildren", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilitySubrole", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSString\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityTitle", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSString\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityTitleUIElement", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("W\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityNextContents", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityOrientation", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("q\x00")[0]}}, true, true)
		p.AddProperty("accessibilityOverflowButton", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityParent", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("W\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityPlaceholderValue", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSString\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityPreviousContents", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityRole", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSString\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityRoleDescription", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSString\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilitySearchButton", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilitySearchMenu", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilitySelected", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("B\x00")[0]}, {Name: &[]byte("G\x00")[0], Value: &[]byte("isAccessibilitySelected\x00")[0]}}, true, true)
		p.AddProperty("accessibilitySelectedChildren", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityServesAsTitleForUIElements", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityShownMenu", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityMinValue", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityMaxValue", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityLinkedUIElements", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityWindow", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("W\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityIdentifier", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSString\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityHelp", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSString\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityFilename", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSString\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityExpanded", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("B\x00")[0]}, {Name: &[]byte("G\x00")[0], Value: &[]byte("isAccessibilityExpanded\x00")[0]}}, true, true)
		p.AddProperty("accessibilityEdited", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("B\x00")[0]}, {Name: &[]byte("G\x00")[0], Value: &[]byte("isAccessibilityEdited\x00")[0]}}, true, true)
		p.AddProperty("accessibilityEnabled", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("B\x00")[0]}, {Name: &[]byte("G\x00")[0], Value: &[]byte("isAccessibilityEnabled\x00")[0]}}, true, true)
		p.AddProperty("accessibilityChildren", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityChildrenInNavigationOrder", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityClearButton", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityCancelButton", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityProtectedContent", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("B\x00")[0]}, {Name: &[]byte("G\x00")[0], Value: &[]byte("isAccessibilityProtectedContent\x00")[0]}}, true, true)
		p.AddProperty("accessibilityContents", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityLabel", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSString\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityAlternateUIVisible", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("B\x00")[0]}, {Name: &[]byte("G\x00")[0], Value: &[]byte("isAccessibilityAlternateUIVisible\x00")[0]}}, true, true)
		p.AddProperty("accessibilitySharedFocusElements", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityRequired", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("B\x00")[0]}, {Name: &[]byte("G\x00")[0], Value: &[]byte("isAccessibilityRequired\x00")[0]}}, true, true)
		p.AddProperty("accessibilityCustomRotors", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityUserInputLabels", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityAttributedUserInputLabels", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityApplicationFocusedUIElement", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityMainWindow", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityHidden", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("B\x00")[0]}, {Name: &[]byte("G\x00")[0], Value: &[]byte("isAccessibilityHidden\x00")[0]}}, true, true)
		p.AddProperty("accessibilityFrontmost", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("B\x00")[0]}, {Name: &[]byte("G\x00")[0], Value: &[]byte("isAccessibilityFrontmost\x00")[0]}}, true, true)
		p.AddProperty("accessibilityFocusedWindow", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityWindows", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityExtrasMenuBar", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("W\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityMenuBar", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("W\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityColumnTitles", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityOrderedByRow", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("B\x00")[0]}, {Name: &[]byte("G\x00")[0], Value: &[]byte("isAccessibilityOrderedByRow\x00")[0]}}, true, true)
		p.AddProperty("accessibilityHorizontalUnits", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("q\x00")[0]}}, true, true)
		p.AddProperty("accessibilityVerticalUnits", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("q\x00")[0]}}, true, true)
		p.AddProperty("accessibilityHorizontalUnitDescription", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSString\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityVerticalUnitDescription", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSString\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityHandles", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityWarningValue", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityCriticalValue", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityDisclosed", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("B\x00")[0]}, {Name: &[]byte("G\x00")[0], Value: &[]byte("isAccessibilityDisclosed\x00")[0]}}, true, true)
		p.AddProperty("accessibilityDisclosedByRow", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("W\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityDisclosedRows", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityDisclosureLevel", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("q\x00")[0]}}, true, true)
		p.AddProperty("accessibilityMarkerUIElements", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityMarkerValues", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityMarkerGroupUIElement", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityUnits", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("q\x00")[0]}}, true, true)
		p.AddProperty("accessibilityUnitDescription", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSString\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityRulerMarkerType", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("q\x00")[0]}}, true, true)
		p.AddProperty("accessibilityMarkerTypeDescription", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSString\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityHorizontalScrollBar", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityVerticalScrollBar", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityAllowedValues", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityLabelUIElements", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityLabelValue", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("f\x00")[0]}}, true, true)
		p.AddProperty("accessibilitySplitters", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityDecrementButton", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityIncrementButton", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityTabs", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityHeader", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityColumnCount", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("q\x00")[0]}}, true, true)
		p.AddProperty("accessibilityRowCount", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("q\x00")[0]}}, true, true)
		p.AddProperty("accessibilityIndex", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("q\x00")[0]}}, true, true)
		p.AddProperty("accessibilityColumns", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityRows", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityVisibleRows", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilitySelectedRows", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityVisibleColumns", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilitySelectedColumns", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilitySortDirection", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("q\x00")[0]}}, true, true)
		p.AddProperty("accessibilityRowHeaderUIElements", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilitySelectedCells", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityVisibleCells", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityColumnHeaderUIElements", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityRowIndexRange", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("{_NSRange=QQ}\x00")[0]}}, true, true)
		p.AddProperty("accessibilityColumnIndexRange", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("{_NSRange=QQ}\x00")[0]}}, true, true)
		p.AddProperty("accessibilityInsertionPointLineNumber", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("q\x00")[0]}}, true, true)
		p.AddProperty("accessibilitySharedCharacterRange", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("{_NSRange=QQ}\x00")[0]}}, true, true)
		p.AddProperty("accessibilitySharedTextUIElements", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityVisibleCharacterRange", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("{_NSRange=QQ}\x00")[0]}}, true, true)
		p.AddProperty("accessibilityNumberOfCharacters", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("q\x00")[0]}}, true, true)
		p.AddProperty("accessibilitySelectedText", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSString\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilitySelectedTextRange", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("{_NSRange=QQ}\x00")[0]}}, true, true)
		p.AddProperty("accessibilitySelectedTextRanges", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityToolbarButton", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityModal", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("B\x00")[0]}, {Name: &[]byte("G\x00")[0], Value: &[]byte("isAccessibilityModal\x00")[0]}}, true, true)
		p.AddProperty("accessibilityProxy", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityMain", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("B\x00")[0]}, {Name: &[]byte("G\x00")[0], Value: &[]byte("isAccessibilityMain\x00")[0]}}, true, true)
		p.AddProperty("accessibilityFullScreenButton", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityGrowArea", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityDocument", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSString\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityDefaultButton", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityCloseButton", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityZoomButton", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityMinimizeButton", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\x00")[0]}, {Name: &[]byte("&\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.AddProperty("accessibilityMinimized", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("B\x00")[0]}, {Name: &[]byte("G\x00")[0], Value: &[]byte("isAccessibilityMinimized\x00")[0]}}, true, true)
		p.AddProperty("accessibilityCustomActions", []objc.PropertyAttribute{{Name: &[]byte("T\x00")[0], Value: &[]byte("@\"NSArray\"\x00")[0]}, {Name: &[]byte("C\x00")[0], Value: &[]byte("\x00")[0]}}, true, true)
		p.Register()
	} // Finished protocol: NSAccessibility

	p = objc.AllocateProtocol("NSApplicationDelegate")
	if p != nil {
		p.AddMethodDescription(objc.RegisterName("application:delegateHandlesKey:"), "B32@0:8@16@24", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationWillFinishLaunching:"), "v24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("application:continueUserActivity:restorationHandler:"), "B40@0:8@16@24@?32", false, true)
		p.AddMethodDescription(objc.RegisterName("application:didDecodeRestorableState:"), "v32@0:8@16@24", false, true)
		p.AddMethodDescription(objc.RegisterName("application:didFailToContinueUserActivityWithType:error:"), "v40@0:8@16@24@32", false, true)
		p.AddMethodDescription(objc.RegisterName("application:didFailToRegisterForRemoteNotificationsWithError:"), "v32@0:8@16@24", false, true)
		p.AddMethodDescription(objc.RegisterName("application:didReceiveRemoteNotification:"), "v32@0:8@16@24", false, true)
		p.AddMethodDescription(objc.RegisterName("application:didRegisterForRemoteNotificationsWithDeviceToken:"), "v32@0:8@16@24", false, true)
		p.AddMethodDescription(objc.RegisterName("application:didUpdateUserActivity:"), "v32@0:8@16@24", false, true)
		p.AddMethodDescription(objc.RegisterName("application:handlerForIntent:"), "@32@0:8@16@24", false, true)
		p.AddMethodDescription(objc.RegisterName("application:openFile:"), "B32@0:8@16@24", false, true)
		p.AddMethodDescription(objc.RegisterName("application:openFileWithoutUI:"), "B32@0:8@16@24", false, true)
		p.AddMethodDescription(objc.RegisterName("application:openFiles:"), "v32@0:8@16@24", false, true)
		p.AddMethodDescription(objc.RegisterName("application:openTempFile:"), "B32@0:8@16@24", false, true)
		p.AddMethodDescription(objc.RegisterName("application:openURLs:"), "v32@0:8@16@24", false, true)
		p.AddMethodDescription(objc.RegisterName("application:printFile:"), "B32@0:8@16@24", false, true)
		p.AddMethodDescription(objc.RegisterName("application:printFiles:withSettings:showPrintPanels:"), "Q44@0:8@16@24@32B40", false, true)
		p.AddMethodDescription(objc.RegisterName("application:userDidAcceptCloudKitShareWithMetadata:"), "v32@0:8@16@24", false, true)
		p.AddMethodDescription(objc.RegisterName("application:willContinueUserActivityWithType:"), "B32@0:8@16@24", false, true)
		p.AddMethodDescription(objc.RegisterName("application:willEncodeRestorableState:"), "v32@0:8@16@24", false, true)
		p.AddMethodDescription(objc.RegisterName("application:willPresentError:"), "@32@0:8@16@24", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationDidBecomeActive:"), "v24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationDidChangeOcclusionState:"), "v24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationDidChangeScreenParameters:"), "v24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationDidFinishLaunching:"), "v24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationDidHide:"), "v24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationDidResignActive:"), "v24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationDidUnhide:"), "v24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationDidUpdate:"), "v24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationDockMenu:"), "@24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationOpenUntitledFile:"), "B24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationProtectedDataDidBecomeAvailable:"), "v24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationProtectedDataWillBecomeUnavailable:"), "v24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationShouldAutomaticallyLocalizeKeyEquivalents:"), "B24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationShouldHandleReopen:hasVisibleWindows:"), "B28@0:8@16B24", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationShouldOpenUntitledFile:"), "B24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationShouldTerminate:"), "Q24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationShouldTerminateAfterLastWindowClosed:"), "B24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationSupportsSecureRestorableState:"), "B24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationWillBecomeActive:"), "v24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationWillHide:"), "v24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationWillResignActive:"), "v24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationWillTerminate:"), "v24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationWillUnhide:"), "v24@0:8@16", false, true)
		p.AddMethodDescription(objc.RegisterName("applicationWillUpdate:"), "v24@0:8@16", false, true)
		var adoptedProtocol *objc.Protocol
		adoptedProtocol = objc.GetProtocol("NSObject")
		if adoptedProtocol == nil {
			log.Fatalln("protocol 'NSObject' does not exist")
		}
		p.AddProtocol(adoptedProtocol)
		p.Register()
	} // Finished protocol: NSApplicationDelegate
}
