// Copyright 2014 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

#include "textflag.h"
#include "abi_ppc64x.h"

#define FIXED_FRAME 32

// Called by C code generated by cmd/cgo.
// func crosscall2(fn, a unsafe.Pointer, n int32, ctxt uintptr)
// Saves C callee-saved registers and calls cgocallback with three arguments.
// fn is the PC of a func(a unsafe.Pointer) function.
TEXT crosscall2(SB), NOSPLIT|NOFRAME, $0
	STACK_AND_SAVE_HOST_TO_GO_ABI(FIXED_FRAME)
	MOVD R2, 24(R1)

	MOVD R3, FIXED_FRAME+0(R1) // fn unsafe.Pointer
	MOVD R4, FIXED_FRAME+8(R1) // a unsafe.Pointer

	// Skip R5 = n uint32
	MOVD R6, FIXED_FRAME+16(R1)  // ctxt uintptr
	BL   runtime·cgocallback(SB)

	MOVD 24(R1), R2
	UNSTACK_AND_RESTORE_GO_TO_HOST_ABI(FIXED_FRAME)
	RET
