// Code generated by 'go generate' with gen.go. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2022 The Ebitengine Authors

//go:build !cgo && (darwin || freebsd || linux || netbsd)

package fakecgo

import (
	_ "unsafe"
)

//go:linkname _x_cgo_init_trampoline _x_cgo_init_trampoline
//go:linkname _cgo_init _cgo_init
var _x_cgo_init_trampoline byte
var _cgo_init = &_x_cgo_init_trampoline

//go:linkname _x_cgo_thread_start_trampoline _x_cgo_thread_start_trampoline
//go:linkname _cgo_thread_start _cgo_thread_start
var _x_cgo_thread_start_trampoline byte
var _cgo_thread_start = &_x_cgo_thread_start_trampoline

//go:linkname _x_cgo_setenv_trampoline _x_cgo_setenv_trampoline
//go:linkname _cgo_setenv runtime._cgo_setenv
var _x_cgo_setenv_trampoline byte
var _cgo_setenv = &_x_cgo_setenv_trampoline

//go:linkname _x_cgo_unsetenv_trampoline _x_cgo_unsetenv_trampoline
//go:linkname _cgo_unsetenv runtime._cgo_unsetenv
var _x_cgo_unsetenv_trampoline byte
var _cgo_unsetenv = &_x_cgo_unsetenv_trampoline

//go:linkname _x_cgo_notify_runtime_init_done_trampoline _x_cgo_notify_runtime_init_done_trampoline
//go:linkname _cgo_notify_runtime_init_done _cgo_notify_runtime_init_done
var _x_cgo_notify_runtime_init_done_trampoline byte
var _cgo_notify_runtime_init_done = &_x_cgo_notify_runtime_init_done_trampoline

//go:linkname _x_cgo_bindm_trampoline _x_cgo_bindm_trampoline
//go:linkname _cgo_bindm _cgo_bindm
var _x_cgo_bindm_trampoline byte
var _cgo_bindm = &_x_cgo_bindm_trampoline

var (
	threadentry_call                   = threadentry
	_cgo_init_call                     = x_cgo_init
	_cgo_thread_start_call             = x_cgo_thread_start
	_cgo_setenv_call                   = x_cgo_setenv
	_cgo_unsetenv_call                 = x_cgo_unsetenv
	_cgo_notify_runtime_init_done_call = x_cgo_notify_runtime_init_done
	_cgo_bindm_call                    = x_cgo_bindm
)
