// Code generated by 'go generate' with gen.go. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2022 The Ebitengine Authors

//go:build !cgo && (darwin || freebsd || linux || netbsd)

#include "textflag.h"
#include "go_asm.h"

// these trampolines map the gcc ABI to Go ABI and then calls into the Go equivalent functions.

TEXT _x_cgo_init_trampoline(SB), NOSPLIT, $8-0
	MOVW R0, 4(R13)
	MOVW R1, 8(R13)
	MOVW ·_cgo_init_call(SB), R12
	MOVW (R12), R12
	CALL (R12)
	RET

TEXT _x_cgo_thread_start_trampoline(SB), NOSPLIT, $4-0
	MOVW R0, 4(R13)
	MOVW ·_cgo_thread_start_call(SB), R12
	MOVW (R12), R12
	CALL (R12)
	RET

TEXT _x_cgo_setenv_trampoline(SB), NOSPLIT, $4-0
	MOVW R0, 4(R13)
	MOVW ·_cgo_setenv_call(SB), R12
	MOVW (R12), R12
	CALL (R12)
	RET

TEXT _x_cgo_unsetenv_trampoline(SB), NOSPLIT, $4-0
	MOVW R0, 4(R13)
	MOVW ·_cgo_unsetenv_call(SB), R12
	MOVW (R12), R12
	CALL (R12)
	RET

TEXT _x_cgo_notify_runtime_init_done_trampoline(SB), NOSPLIT, $0-0
	CALL ·x_cgo_notify_runtime_init_done(SB)
	RET

TEXT _x_cgo_bindm_trampoline(SB), NOSPLIT, $0-0
	CALL ·x_cgo_bindm(SB)
	RET
