// Code generated by 'go generate' with gen.go. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2022 The Ebitengine Authors

//go:build !cgo && linux

#include "textflag.h"
#include "go_asm.h"

// these trampolines map the gcc ABI to Go ABI and then calls into the Go equivalent functions.

TEXT _x_cgo_init_trampoline(SB), NOSPLIT, $16
	MOVV ·_cgo_init_call(SB), R23
	MOVV (R23), R23
	CALL (R23)
	RET

TEXT _x_cgo_thread_start_trampoline(SB), NOSPLIT, $8
	MOVV ·_cgo_thread_start_call(SB), R23
	MOVV (R23), R23
	CALL (R23)
	RET

TEXT _x_cgo_setenv_trampoline(SB), NOSPLIT, $8
	MOVV ·_cgo_setenv_call(SB), R23
	MOVV (R23), R23
	CALL (R23)
	RET

TEXT _x_cgo_unsetenv_trampoline(SB), NOSPLIT, $8
	MOVV ·_cgo_unsetenv_call(SB), R23
	MOVV (R23), R23
	CALL (R23)
	RET

TEXT _x_cgo_notify_runtime_init_done_trampoline(SB), NOSPLIT, $0
	MOVV ·_cgo_notify_runtime_init_done_call(SB), R23
	MOVV (R23), R23
	CALL (R23)
	RET

TEXT _x_cgo_bindm_trampoline(SB), NOSPLIT, $0
	MOVV ·_cgo_bindm_call(SB), R23
	MOVV (R23), R23
	CALL (R23)
	RET
