// Code generated by 'go generate' with gen.go. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2022 The Ebitengine Authors

//go:build !cgo && (freebsd || linux)

#include "textflag.h"
#include "go_asm.h"

// these trampolines map the gcc ABI to Go ABI and then calls into the Go equivalent functions.

TEXT _x_cgo_init_trampoline(SB), NOSPLIT, $8-0
	MOVL 12(SP), AX
	MOVL AX, 0(SP)
	MOVL 16(SP), AX
	MOVL AX, 4(SP)
	MOVL ·_cgo_init_call(SB), CX
	MOVL (CX), CX
	CALL CX
	RET

TEXT _x_cgo_thread_start_trampoline(SB), NOSPLIT, $4-0
	MOVL 8(SP), AX
	MOVL AX, 0(SP)
	MOVL ·_cgo_thread_start_call(SB), CX
	MOVL (CX), CX
	CALL CX
	RET

TEXT _x_cgo_setenv_trampoline(SB), NOSPLIT, $4-0
	MOVL 8(SP), AX
	MOVL AX, 0(SP)
	MOVL ·_cgo_setenv_call(SB), CX
	MOVL (CX), CX
	CALL CX
	RET

TEXT _x_cgo_unsetenv_trampoline(SB), NOSPLIT, $4-0
	MOVL 8(SP), AX
	MOVL AX, 0(SP)
	MOVL ·_cgo_unsetenv_call(SB), CX
	MOVL (CX), CX
	CALL CX
	RET

TEXT _x_cgo_notify_runtime_init_done_trampoline(SB), NOSPLIT, $0-0
	CALL ·x_cgo_notify_runtime_init_done(SB)
	RET

TEXT _x_cgo_bindm_trampoline(SB), NOSPLIT, $0-0
	CALL ·x_cgo_bindm(SB)
	RET
