// Code generated by 'go generate' with gen.go. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2022 The Ebitengine Authors

//go:build !cgo && linux

#include "textflag.h"
#include "go_asm.h"

// these trampolines map the gcc ABI to Go ABI and then calls into the Go equivalent functions.

TEXT _x_cgo_init_trampoline(SB), NOSPLIT, $16
	MOV  ·_cgo_init_call(SB), X5
	MOV  (X5), X5
	CALL X5
	RET

TEXT _x_cgo_thread_start_trampoline(SB), NOSPLIT, $8
	MOV  ·_cgo_thread_start_call(SB), X5
	MOV  (X5), X5
	CALL X5
	RET

TEXT _x_cgo_setenv_trampoline(SB), NOSPLIT, $8
	MOV  ·_cgo_setenv_call(SB), X5
	MOV  (X5), X5
	CALL X5
	RET

TEXT _x_cgo_unsetenv_trampoline(SB), NOSPLIT, $8
	MOV  ·_cgo_unsetenv_call(SB), X5
	MOV  (X5), X5
	CALL X5
	RET

TEXT _x_cgo_notify_runtime_init_done_trampoline(SB), NOSPLIT, $0
	MOV  ·_cgo_notify_runtime_init_done_call(SB), X5
	MOV  (X5), X5
	CALL X5
	RET

TEXT _x_cgo_bindm_trampoline(SB), NOSPLIT, $0
	MOV  ·_cgo_bindm_call(SB), X5
	MOV  (X5), X5
	CALL X5
	RET
