// Code generated by 'go generate' with gen.go. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2022 The Ebitengine Authors

//go:build !cgo

#include "textflag.h"


TEXT ___errno_location(SB), NOSPLIT, $0-0
	JMP purego___errno_location(SB)

TEXT _cgo_purego_setegid_trampoline(SB), NOSPLIT, $0
	MOVD	R0, 8(RSP)
	MOVD	·x_cgo_purego_setegid_call(SB), R26
	MOVD	(R26), R2
	CALL	(R2)
	RET

TEXT _setegid(SB), NOSPLIT, $0-0
	JMP purego_setegid(SB)

TEXT _cgo_purego_seteuid_trampoline(SB), NOSPLIT, $0
	MOVD	R0, 8(RSP)
	MOVD	·x_cgo_purego_seteuid_call(SB), R26
	MOVD	(R26), R2
	CALL	(R2)
	RET

TEXT _seteuid(SB), NOSPLIT, $0-0
	JMP purego_seteuid(SB)

TEXT _cgo_purego_setgid_trampoline(SB), NOSPLIT, $0
	MOVD	R0, 8(RSP)
	MOVD	·x_cgo_purego_setgid_call(SB), R26
	MOVD	(R26), R2
	CALL	(R2)
	RET

TEXT _setgid(SB), NOSPLIT, $0-0
	JMP purego_setgid(SB)

TEXT _cgo_purego_setregid_trampoline(SB), NOSPLIT, $0
	MOVD	R0, 8(RSP)
	MOVD	·x_cgo_purego_setregid_call(SB), R26
	MOVD	(R26), R2
	CALL	(R2)
	RET

TEXT _setregid(SB), NOSPLIT, $0-0
	JMP purego_setregid(SB)

TEXT _cgo_purego_setresgid_trampoline(SB), NOSPLIT, $0
	MOVD	R0, 8(RSP)
	MOVD	·x_cgo_purego_setresgid_call(SB), R26
	MOVD	(R26), R2
	CALL	(R2)
	RET

TEXT _setresgid(SB), NOSPLIT, $0-0
	JMP purego_setresgid(SB)

TEXT _cgo_purego_setresuid_trampoline(SB), NOSPLIT, $0
	MOVD	R0, 8(RSP)
	MOVD	·x_cgo_purego_setresuid_call(SB), R26
	MOVD	(R26), R2
	CALL	(R2)
	RET

TEXT _setresuid(SB), NOSPLIT, $0-0
	JMP purego_setresuid(SB)

TEXT _cgo_purego_setreuid_trampoline(SB), NOSPLIT, $0
	MOVD	R0, 8(RSP)
	MOVD	·x_cgo_purego_setreuid_call(SB), R26
	MOVD	(R26), R2
	CALL	(R2)
	RET

TEXT _setreuid(SB), NOSPLIT, $0-0
	JMP purego_setreuid(SB)

TEXT _cgo_purego_setuid_trampoline(SB), NOSPLIT, $0
	MOVD	R0, 8(RSP)
	MOVD	·x_cgo_purego_setuid_call(SB), R26
	MOVD	(R26), R2
	CALL	(R2)
	RET

TEXT _setuid(SB), NOSPLIT, $0-0
	JMP purego_setuid(SB)

TEXT _cgo_purego_setgroups_trampoline(SB), NOSPLIT, $0
	MOVD	R0, 8(RSP)
	MOVD	·x_cgo_purego_setgroups_call(SB), R26
	MOVD	(R26), R2
	CALL	(R2)
	RET

TEXT _setgroups(SB), NOSPLIT, $0-0
	JMP purego_setgroups(SB)

