// Code generated by 'go generate' with gen.go. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2022 The Ebitengine Authors

//go:build !cgo

#include "textflag.h"

// these stubs are here because it is not possible to go:linkname directly the C functions

TEXT ___errno_location(SB), NOSPLIT, $0-0
	CALL purego___errno_location(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _setegid(SB), NOSPLIT, $0-0
	CALL purego_setegid(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _seteuid(SB), NOSPLIT, $0-0
	CALL purego_seteuid(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _setgid(SB), NOSPLIT, $0-0
	CALL purego_setgid(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _setregid(SB), NOSPLIT, $0-0
	CALL purego_setregid(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _setresgid(SB), NOSPLIT, $0-0
	CALL purego_setresgid(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _setresuid(SB), NOSPLIT, $0-0
	CALL purego_setresuid(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _setreuid(SB), NOSPLIT, $0-0
	CALL purego_setreuid(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _setuid(SB), NOSPLIT, $0-0
	CALL purego_setuid(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _setgroups(SB), NOSPLIT, $0-0
	CALL purego_setgroups(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _pthread_attr_getstacksize(SB), NOSPLIT, $0-0
	CALL purego_pthread_attr_getstacksize(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _pthread_attr_destroy(SB), NOSPLIT, $0-0
	CALL purego_pthread_attr_destroy(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET
