// Code generated by 'go generate' with gen.go. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2022 The Ebitengine Authors

//go:build !cgo

#include "textflag.h"

// these stubs are here because it is not possible to go:linkname directly the C functions

TEXT _malloc(SB), NOSPLIT, $0-0
	CALL purego_malloc(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _free(SB), NOSPLIT, $0-0
	CALL purego_free(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _setenv(SB), NOSPLIT, $0-0
	CALL purego_setenv(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _unsetenv(SB), NOSPLIT, $0-0
	CALL purego_unsetenv(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _sigfillset(SB), NOSPLIT, $0-0
	CALL purego_sigfillset(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _nanosleep(SB), NOSPLIT, $0-0
	CALL purego_nanosleep(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _abort(SB), NOSPLIT, $0-0
	CALL purego_abort(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _pthread_attr_init(SB), NOSPLIT, $0-0
	CALL purego_pthread_attr_init(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _pthread_create(SB), NOSPLIT, $0-0
	CALL purego_pthread_create(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _pthread_detach(SB), NOSPLIT, $0-0
	CALL purego_pthread_detach(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _pthread_sigmask(SB), NOSPLIT, $0-0
	CALL purego_pthread_sigmask(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _pthread_mutex_lock(SB), NOSPLIT, $0-0
	CALL purego_pthread_mutex_lock(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _pthread_mutex_unlock(SB), NOSPLIT, $0-0
	CALL purego_pthread_mutex_unlock(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _pthread_cond_broadcast(SB), NOSPLIT, $0-0
	CALL purego_pthread_cond_broadcast(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

TEXT _pthread_setspecific(SB), NOSPLIT, $0-0
	CALL purego_pthread_setspecific(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET
